### ISSUE TITLE
Data URI:s that work in IE6 and IE7

### ISSUE THREAD

**Issue by EmilStenstrom** [django-compressor/django-compressor#10]
Nice to see that you've taken over the project! :) Let me move a feature request from the old repo here:

Data URI:s are great, but IE6 and IE7 does not support them. Good thing is, they can be emulated with MHTML, and it actually isn't that tricky:

http://www.phpied.com/the-proper-mhtml-syntax/

This would be an excellent addition to django_compressor, don't you think?

**Comment by karyon** [comment]
i vote for closing this, it's about IE6 and 7.

**Comment by diox** [comment]
I agree, and the workaround from https://github.com/django-compressor/django-compressor/issues/10#issuecomment-16651771 should be sufficient (or at least, be a good start) for people that still need IE6/7 support.
