### ISSUE TITLE
django-cookie-consent creates new cache files on page refresh

### ISSUE THREAD

**Issue by 9mido** [django-compressor/django-compressor#1000]
https://github.com/bmihelac/django-cookie-consent/blob/master/docs/index.rst

Django-cookie-consent has javascript code that creates a new cookie age for how long a cookie will be in the user's browser when they accept. When cookies are not accepted, and the user keeps refreshing the page with a cookie banner shown, new files get inserted into the CACHE folder that django-compressor uses. This seems to be because each cookie javascript code has a brand new timestamp for the cookie age that generates each time the page refreshes. Because of the new timestamps on each page refresh, the cookie javascript code changes each time, thus creating a new CACHE file instead of just having one. 

This could be problematic if the website has tons of users visiting the site since it will create lots of cache files. What is the best way to deal with that - either get rid of the extra files (cron job maybe), or only create 1 cache file even though the javascript file changes each time? Maybe there is a way to deal with this already in django-compressor that I am missing?

**Comment by diox** [comment]
Hi,

If you have some JavaScript code that is always changing, then you should probably not use compressor with it. That being said, this is not a support forum, please head to sites like stackoverflow for these kind of questions.
