### ISSUE TITLE
Javascript modules do not work correctly

### ISSUE THREAD

**Issue by ananthb** [django-compressor/django-compressor#1001]
I have a few js scripts that have script type set to module in my HTML. My javascript code depends on being run as a module. Django compressor does not output the script type currently.

**Comment by carltongibson** [comment]
Yeah, OK, this would be a new feature. @ananthb Would you fancy working on a PR for it?

**Comment by ananthb** [comment]
Yeah! Would a new file type work? Something like `{% compress js_module %}...{% endcompress %}`, and each file in that block could be treated as a module?

**Comment by ananthb** [comment]
I'm not sure what this would look like though. Modules are not really meant to be bundled up like normal scripts. Maybe just leaving them out of django-compressor and printing a warning would be better?
