### ISSUE TITLE
compressor and memcached question

### ISSUE THREAD

**Issue by yesyves** [django-compressor/django-compressor#1004]
Hi

This is really more a question than an issue. I'm pretty new to this stuff so my question may even be a bit silly, but the docs seem to say compressor is better used along with memcached, but from what I understand, memcached is optimized for DB caching, not static files caching ?

Thanks

**Comment by gh640** [comment]
The doc says:

> For production sites it is strongly recommended to use a real cache backend such as memcached to speed up the checks of compressed files.

- https://django-compressor.readthedocs.io/en/stable/usage/

It says using Memcached is good for speeding up the checks of compressed files. I recommend you to see the actual code to confirm what it means.

If you don't know well what Memcached is, Django documentation would help:

> The fastest, most efficient type of cache supported natively by Django, Memcached is an entirely memory-based cache server, originally developed to handle high loads at LiveJournal.com and subsequently open-sourced by Danga Interactive. It is used by sites such as Facebook and Wikipedia to reduce database access and dramatically increase site performance.
> 
> Memcached runs as a daemon and is allotted a specified amount of RAM. All it does is provide a fast interface for adding, retrieving and deleting data in the cache. All data is stored directly in memory, so there’s no overhead of database or filesystem usage.

- https://docs.djangoproject.com/en/3.1/topics/cache/#memcached

I hope these help.

**Comment by diox** [comment]
https://django-compressor.readthedocs.io/en/stable/behind-the-scenes/ explains how compressor uses caching.
