### ISSUE TITLE
Please stick to PEP 427

### ISSUE THREAD

**Issue by Fluepke** [django-compressor/django-compressor#1005]
Naming of you releases on PyPi is not compliant to [PEP427](https://www.python.org/dev/peps/pep-0427/#file-name-convention).

Please fix, as it causes stuff to break, e.g. [NixOS](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/interpreters/python/fetchpypi.nix#L10).

**Comment by diox** [comment]
Could you please elaborate of what's non compliant to PEP 427 about them ? This is just generated from our fairly standard [setup.py](https://github.com/django-compressor/django-compressor/blob/develop/setup.py) and `python bdist_wheel`.

I'll be happy to review any pull request you submit to fix this.

**Comment by Fluepke** [comment]
The files released under https://pypi.org/project/django-compressor/#files should be named as described in PEP427.

**Comment by diox** [comment]
Yes, I understand that's what you're asking, but could you elaborate as to why you think they aren't ? I'm talking specifically about the `.whl` file, since that's this PEP is about.

**Comment by karyon** [comment]
not enough information, closing. With more details I'll gladly reopen!
