### ISSUE TITLE
latest version of appconf does not support python 2.7

### ISSUE THREAD

**Issue by jstacoder** [django-compressor/django-compressor#1008]
currently you say you support python 2.7, but your requirement on django-appconf>=1.0.2 breaks my environment because i am using python 2.7 still. i can fix on my end by pinning appconf to 1.0.3 but just wanted to let you know

**Comment by carltongibson** [comment]
App conf dropped Python 3 support. It's probably time for compressor to do the same.

**Comment by karyon** [comment]
that actually already happened on master, but there hasn't been a release since then. since this only affects python 2.7 and is easy to fix, I'd rather not do a bugfix release, but I'll leave this open for others to see until we have a new release. thanks for the report!

**Comment by diox** [comment]
django-compressor 3.0 will officially drop Python 2.7 support.
