### ISSUE TITLE
RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().

### ISSUE THREAD

**Issue by gh640** [django-compressor/django-compressor#1009]
This warning is printed on Django 3.1.

```text
/usr/local/lib/python3.7/site-packages/compressor/cache.py:29: 
RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
    return 'django_compressor.%s' % force_text(key)
```

**Comment by gh640** [comment]
Sorry, this was already fixed with #988 .

**Comment by Steckelfisch** [comment]
But it has missed the 2.4.1 release. !t seems.

**Comment by diox** [comment]
2.4.1 was branched off 2.4.0, so that's expected. 3.0 will fix this when this is released, in the meantime you can help by testing the `develop` branch.

**Comment by Steckelfisch** [comment]
Ok. Thanks. will do

**Comment by nijel** [comment]
Any plans to release this fix? Django 4.0 removes force_text and Django 4.0 alpha 1 is now out, so people will be running into this:

```
django.template.library.InvalidTemplateLibrary: Invalid template library specified. ImportError raised when trying to load 'compressor.templatetags.compress': cannot import name 'force_text' from 'django.utils.encoding' (/opt/hostedtoolcache/Python/3.9.7/x64/lib/python3.9/site-packages/django/utils/encoding.py)
```

**Comment by diox** [comment]
You can help test the `develop` branch against Django 4.0 alpha 1 and report back, or help fix https://github.com/django-compressor/django-compressor/issues/1060 so that I can release 3.0, which would contain the fix for this issue.

**Comment by carltongibson** [comment]
I've added testing against 4.0a1 in #1072 — there's a couple of unrelated failures, but it's generally green.

**Comment by nijel** [comment]
I've added `develop` branch to our CI where we test against Django pre-releases, that should give it some testing as well.

**Comment by sumanthratna** [comment]
Sorry to bump an old thread, but when is the ETA for 3.0? Django 4.0 was just realized but unfortunately, it can't be used with django-compressor because of the force-text error. 

Happy to try and help with any minor remaining bug fixes.

**Comment by tomwojcik** [comment]
@sumanthratna for the time being install django_compressor with

`git+git://github.com/django-compressor/django-compressor.git@ce972890f017a363c63bf41ab24a923b493ae97a`

As Carl mentioned in another ticket, it should be released within a week.

**Comment by carltongibson** [comment]
Yep. It's all done bar the administration for the release. It's coming. Installing from GitHub will have to do you if you can't wait a few days.
