### ISSUE TITLE
Add copyright to the top

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [django-compressor/django-compressor#1013]
I'm using Django-compressor and noticed the CACHE outputs delete all the comments. There isn't much magnification going on either, but that might be me not configuring too much of the settings.

Anyhow, is there a way to leave in the copyright header for a file besides offline compression? Thanks!

**Comment by karyon** [comment]
Whether comments are removed or not is up to the actual minifier (which one you use is up to you), django-compressor shouldn't touch them. Offline compression shouldn't affect the output, it just makes it faster.

**Comment by Andrew-Chen-Wang** [comment]
I just want to mention to anyone else that this was actually fixed a long time ago in #399 for both rJSMin and rCSSMin.

All you have to do is add a bang to your comment like so:

```
/*!
*
*
*/
```

Docs for the bang comments for JS (same as css too): http://opensource.perlig.de/rjsmin/#rjsmin.jsmin
