### ISSUE TITLE
Now have Memcached, should I switch to online compression instead?

### ISSUE THREAD

**Issue by SHxKM** [django-compressor/django-compressor#1015]
This is more of a question rather than an issue.

I recently set-up a separate Memcached server to cache some resource-hungry views in my Django app which is hosted in Heroku. I don't have a huge budget so my static-files are served with Whitenoise, and reside on the server itself.

I've been very happily using `django-compressor` up until now in `OFFLINE_COMPRESSION` mode. My question now is this: now that I have Memcached, , should I switch to online compression instead and use Memcached as the cache storage? as I understand it at least, there isn't much for me to gain in making this switch because my files are hosted locally, and in any case a deployment in my case means rebuilding the whole cache anyway. But I admit I'm not well-versed in the particularities.

Thanks in advance!

**Comment by diox** [comment]
If offline compression works for you there isn't really a reason to switch to online - you'll only lose in performance (when you get a cache miss). https://django-compressor.readthedocs.io/en/stable/behind-the-scenes/ can help you understand the tradeoffs.
