### ISSUE TITLE
When in DEBUG mode, can you add in a way to output compressed files via an endpoint instead of a real file?

### ISSUE THREAD

**Issue by benlei** [django-compressor/django-compressor#1016]
When developing locally (especially for a new project), I make modifications frequently and as a result django-compressor generates MANY css/js files. This also can make my IDE search for references of css/js in the CACHE directory, which is a bit undesirable.

Can you add in a way so that those files aren't created when in DEBUG mode, and instead a different URL/view is used to output the compressed css/js?

**Comment by karyon** [comment]
I don't 100% remember the specifics, but COMPRESS_ENABLED is `not DEBUG` by default. so, by default, compressor shouldn't generate any output in DEBUG mode. the exception is when you have `COMPRESS_PRECOMPILERS` set, then it has to generate that output.

I'm afraid the added complexity is not really worth the added value of not having to clear that directory occasionally. With regards to the IDE, i think it makes sense to configure it to not look into the CACHE directory regardless of how many files are in there, the files in there are generated artifacts and shouldn't be used when browsing code.
