### ISSUE TITLE
compressor.exceptions.OfflineGenerationError: No 'compress' template tags found in templates.

### ISSUE THREAD

**Issue by kumarpandian86** [django-compressor/django-compressor#1031]
Hi ,
 i am using django 2.2 and python 3.6,  when i try to run the command  **python manage.py compres**s  i am getting the following error 👍 

_File "C:\Users\kumarpandian.r\envs\assessment_env\lib\site-packages\compressor\management\commands\compress.py", line 246, in compress   
    "No 'compress' template tags found in templates."
compressor.exceptions.OfflineGenerationError: No 'compress' template tags found in templates.Try running compress command with --follow-links and/or--extension=EXTENSIONS_

**my settings :**
COMPRESS_ENABLED = True
COMPRESS_OFFLINE =True
COMPRESS_ROOT = STATIC_ROOT
COMPRESS_OFFLINE_MANIFEST = "manifest.json"
COMPRESS_OUTPUT_DIR ="compressed"
#COMPRESS_STORAGE = "compressor.storage.GzipCompressorFileStorage"
COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter',  'compressor.filters.cssmin.CSSMinFilter']
COMPRESS_JS_FILTERS = ['compressor.filters.jsmin.JSMinFilter']

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)
COMPRESS_PARSER = 'compressor.parser.HtmlParser'

**my template code :** 
{% load compress %}
{% compress css %}
    <link href="/assets/css/exam_main.css" rel="stylesheet">
    <link href="/assets/vendor/percentageCircle/css/circle.css" rel="stylesheet">
    <link href="/assets/css/calculator.css" rel="stylesheet">
    <link href="/assets/css/QuestionImage.css" rel="stylesheet">
{% endcompress %}

**Comment by karyon** [comment]
I suggest you ask this on stackoverflow or similar, along with more details on your setup (the rest of your settings.py, and e.g. where the template is located).
