### ISSUE TITLE
Does not work with Django 3.x

### ISSUE THREAD

**Issue by magicl** [django-compressor/django-compressor#1036]
`  
  File "/home/..../lib/python3.6/site-packages/compressor/parser/default_htmlparser.py", line 77, in elem_content
    return smart_text(elem['text'])
  File "/home/..../lib/python3.6/site-packages/django/utils/encoding.py", line 105, in smart_text
    RemovedInDjango40Warning, stacklevel=2,
django.utils.deprecation.RemovedInDjango40Warning: smart_text() is deprecated in favor of smart_str().
`

There might be more uses of smart_text that need to be replaced as well

**Comment by carltongibson** [comment]
Fixed in 86db93e3bd9abdfaa53726d87e9e37cc5d754c60. Will be part of the next release. This is just a warning until Django 4.0 (`RemovedInDjango40Warning`) which won't be released until December 2021.

**Comment by magicl** [comment]
Thank you! I cannot find a way to disable this RemovedInDjango40Warning.. E.g. -Wignore::RemovedInDjango40Warning does not seem to work.
When is the next release planned for?

**Comment by carltongibson** [comment]
`-Wignore` will work if you get the incantation right. I'd try the full path to begin `django.utils.deprecation.RemovedInDjango40Warning`, but you want to limit it to specific files, rather than globally I'd guess.
