### ISSUE TITLE
Document COMPRESS_URL_PLACEHOLDER

### ISSUE THREAD

**Issue by thenewguy** [django-compressor/django-compressor#1040]
[COMPRESS_URL_PLACEHOLDER](https://github.com/django-compressor/django-compressor/blob/6ac42adeba9922fd1ebf80aa37c21390cbb4854b/compressor/templatetags/compress.py#L71) appears to be missing from the docs.

**Comment by karyon** [comment]
True, although I don't see why anyone would want to modify it?

**Comment by thenewguy** [comment]
Probably not. I meant to come back and close this.  I was tracking down an issue I was working on and saw this before working my way through to see what it did.
