### ISSUE TITLE
Defer non-critical CSS (preload)

### ISSUE THREAD

**Issue by brunoprograma** [django-compressor/django-compressor#1044]
Well, in my case the "preload" didn't even work for CSS files. Browsers don't even load them. But, even for those who are using and working, I believe there is a lack of optimization for an asynchronous load, according to the documentation available at:

https://web.dev/defer-non-critical-css/

The program is creating only new attributes in a <link> tag (rel="preload" and as="style"), but the correct thing would be to make it look like the example below (taken from the previous link):

`<link rel="preload" href="styles.css" as="style" onload="this.onload=null;this.rel='stylesheet'">`
`<noscript><link rel="stylesheet" href="styles.css"></noscript>`

Actually, web.dev is a great source of information to any new feature in this project.

Check #1045

**Comment by diox** [comment]
See https://github.com/django-compressor/django-compressor/pull/1045#issuecomment-803134423
