### ISSUE TITLE
Use a hash of the file's contents instead of the last modified time

### ISSUE THREAD

**Issue by simonw** [django-compressor/django-compressor#105]
django_compressor uses the file's last modified time to generate the cachebusting component of the file name. This makes me slightly nervous, since different computers may have different clock times. I suggest instead using a sha1 hash of the contents of the file, which is guaranteed to change when the file contents changes.

**Comment by hbmartin** [comment]
@jezdez @diox is there an analog for this for JS?
I seem to be having a problem where JS files aren't being re-compressed after their contents change.
