### ISSUE TITLE
Incompatible with Jinja2 v3

### ISSUE THREAD

**Issue by magicl** [django-compressor/django-compressor#1060]
`
File "django-compressor/compressor/management/commands/compress.py", line 207, in compress
    template_nodes = compressor_nodes.setdefault(template, OrderedDict())
  File "jinja2/nodes.py", line 245, in __hash__
    return hash(tuple(self.iter_fields()))
TypeError: unhashable type: 'list'
`

Also tried the latest version on develop (as of today).

**Comment by jonaseriksson84** [comment]
Also running into this problem.

**Comment by carltongibson** [comment]
This is a change in behaviour between Jinja2 v2 and Jinja2 v3.

**Comment by AlekseiKhatkevich** [comment]
Same issue

**Comment by carltongibson** [comment]
The change here was reverted in Jinga v3.0.3 See https://github.com/pallets/jinja/pull/1522. 

Anyone want to confirm?
