### ISSUE TITLE
Any method to combine but does not compress (min.css) files?

### ISSUE THREAD

**Issue by BoPeng** [django-compressor/django-compressor#1068]
I have a `compress` block with a bunch of system css files such as `font-awesome` and `boostrap`.

```html
{% compress css %}
  <link rel="stylesheet" href="{{ static('css/font-awesome.min.css') }}">
  <link rel="stylesheet" href="{{ static('css/bootstrap/bootstrap.min.css') }}">
{% endcompress %}
 ```
However, for whatever reason that I do not want to spend time to investigate, some features of css do not work after the `css` files are compressed by `CSSMinFilter` as defined in

```python
COMPRESS_FILTERS = {
    'css': [
        'compressor.filters.css_default.CssAbsoluteFilter',
        'compressor.filters.cssmin.CSSMinFilter'
    ],
    'js': ['compressor.filters.jsmin.JSMinFilter']
}
```
(I confirmed the problem by removing the `CSSminFilter` or moving `bootstrap.min.css` outside of the compression block.)

Since these `.min.css` files do not need to be compressed, is there anyway that I can simply combine them without compressing (which could cause trouble)?

**Comment by carltongibson** [comment]
Hi. 

I think you either need to remove the CSSMinFilter, or else use the un-minified Bootstrap files. 

I've use the latter option myself for many years, in order to run the Sass preprocessor. (So it works.)

If your web server uses GZIP compression (or similar) it may be that minification doesn't make much difference to final size. (The algorithms are very good at compression.) 

Hopefully that helps.

**Comment by BoPeng** [comment]
Thanks for the quick reply. My problem is that my website has a bunch of un-minified css/js files, as well as those third-party ones that are minified. 

1. If I remove `CSSMinFilter`, my own `.css` will not be minified, so it is not an option for me.

2. I have a bunch of these third-party css files so it is a bit difficult for me to find the un-minified versions of them. I guess this can be done though.

3. A easier method is to move `.min.css` outside of `{% compress css %}`. This will result in a number of separate `.min.css` files in the generated webpage. I thought that combining them would result in better performance (thus this ticket), but it appears that [combining css/js is not recommend](https://wpjohnny.com/why-you-shouldnt-combine-css-js-performance-reasons/).

I suppose that I will stick to option 3.

**Comment by carltongibson** [comment]
Yes. It's complex. And profiling your individual site is the only really way to know for sure. Good luck!

**Comment by BoPeng** [comment]
Just realized another complication. The stuff I put in `{% compress %}`  will be hosted separately on a CDN, and the stuff outside of it will be hosted from `/static/` from my own website. 

So to use cdn, the `min.css` and `.min.js` file would better be hosted from a public CDN to reduce loads of my own server.

**Comment by BoPeng** [comment]
So in the end I think something like

```html
  {% compress js-join %}
  <script src="{{ static('js/vendor/jquery/jquery-3.5.1.min.js') }}"></script>
  <script src="{{ static('js/vendor/jquery/popper.min.js') }}"></script>
  <script src="{{ static('js/vendor/jquery/uikit.min.js') }}"></script>
  <script src="{{ static('js/vendor/jquery-ui.min.js') }}"></script>
  <script src="{{ static('js/vendor/jquery.barrating.min.js') }}"></script>
 {% endcompress %}
```

that joins but does not compress included `min.js` and `min.css` files would be helpful since it allow the processed files to be served through `COMPRESS_URL`.

Or `django-compressor` could allow the use of an alternative filter so that I can implement a no-compression filter just for the minified files.

**Comment by diox** [comment]
You're free to implement your own `{% compress %}` tag extending the one compressor provides, or to implement your own filters and have some additional logic in there.

**Comment by BoPeng** [comment]
> You're free to implement your own {% compress %} tag extending the one compressor provides, or to implement your own filters and have some additional logic in there.

@diox Could you elaborate on how I can expand `{% compress %}` to concatenate minified `css` and `js` files, basically skipping the specified filters? I can imagine something like an additional option `verbatim` to skip filters for minified js files, use the default for my customized code, but I do not see a way to add such an option.

```html
  {% compress js verbatim %}
  <script src="{{ static('js/vendor/jquery/jquery-3.5.1.min.js') }}"></script>
  <script src="{{ static('js/vendor/jquery/popper.min.js') }}"></script>
  { % endcompress %}
 
  {% compress js %}
  <script src="{{ static('custom.js') }}"></script>
  {% endcompress %}

```

**Comment by diox** [comment]
You can register your own tag inheriting from compressor's and implement whatever custom logic you want there.
