### ISSUE TITLE
Unable to apply CompilerFilter

### ISSUE THREAD

**Issue by gati** [django-compressor/django-compressor#107]
Struggling to work out what I'm doing wrong. Trying to parse less and coffeescript in a template, both throw a similar error. With coffeescript I get:

Unable to apply CompilerFilter ('coffee --compile --stdio'): [Errno 32] Broken pipe

And when I remove the coffeescript I get:

Unable to apply CompilerFilter ('lessc {infile} {outfile}'): [Errno 2] No such file or directory

I think I have my precompilers set correctly, but am I forgetting something else?

COMPRESS_PRECOMPILERS = (
    ('text/coffeescript', 'coffee --compile --stdio'),
    ('text/less', 'lessc {infile} {outfile}'),
)

Any help would be appreciated.

Thanks!

**Comment by JackLeo** [comment]
check if coffee and lessc commands are actually callable. If they produce nothing - purge node. On some repositories node != nodejs

**Comment by neic** [comment]
I had the same issue. My problem was that I had doublequotes around `{infile}`.

I changed:
```python
COMPRESS_PRECOMPILERS = (
    ('text/less', 'lessc "{infile}" "{outfile}"'),
)
```
to:
```python
COMPRESS_PRECOMPILERS = (
    ('text/less', 'lessc {infile} {outfile}'),
)
```
django-compress will put in quotes itself.

I hope this will spare someones headache.
