### ISSUE TITLE
RemovedInDjango40Warning: force_text and  providing_args

### ISSUE THREAD

**Issue by jnoortheen** [django-compressor/django-compressor#1076]
These are the warning messages generated from `django-compressor` when using with recent Django versions  `>=3.2`

```
python3.9/site-packages/compressor/signals.py:4: RemovedInDjango40Warning: The providing_args argument is deprecated. As it is purely documentational, it has no replacement. If you rely on this argument as documentation, you can move the text to a code comment or docstring.
    post_compress = django.dispatch.Signal(providing_args=['type', 'mode', 'context'])
```

```
lib/python3.9/site-packages/compressor/cache.py:29: RemovedInDjango40Warning: force_text() is deprecated in favor of force_str().
    return 'django_compressor.%s' % force_text(key)
```

**Comment by cuu508** [comment]
Both are already fixed in the develop branch.

providing_args: https://github.com/django-compressor/django-compressor/pull/1020

force_text: https://github.com/django-compressor/django-compressor/pull/988

**Comment by jnoortheen** [comment]
@cuu508 thanks for letting me know. When can we expect an release?

**Comment by cuu508** [comment]
@jnoortheen I don't know... 

Django 4 is out in December 6, it would be awesome if django-compressor could get a release ready before then.
