### ISSUE TITLE
Test failure when running tests in reverse

### ISSUE THREAD

**Issue by cuu508** [django-compressor/django-compressor#1077]
(I'm opening an issue instead of a PR because I'm unfamiliar with the codebase and have no idea if my naive fix is any good)

If I run compressor tests like so, they succeed:

```
django-admin test --settings=compressor.test_settings compressor
[...]
Ran 387 tests in 1.604s

OK (skipped=12)
```

If I run them in reverse, then `compressor.tests.test_filters.PrecompilerTestCase.test_precompiler_cache` fails:

```
django-admin test --settings=compressor.test_settings compressor -r
[...]
FAIL: test_precompiler_cache (compressor.tests.test_filters.PrecompilerTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/cepe/repos/django-compressor/compressor/tests/test_filters.py", line 103, in test_precompiler_cache
    self.assertEqual("body { color:#990; }", compiler.input())
AssertionError: 'body { color:#990; }' != ''
- body { color:#990; }
+ 
```

`CachedCompilerFilter` looks up a cache key. In the successful case, the cache returns `None`, and in the failing case it returns an empty string. So looks like a previous test has clobbered the cache. 

As an experiment, I added `cache.clear()` at the start of `test_precompiler_cache()`:

```
    def test_precompiler_cache(self):
        cache.clear()
        command = '%s %s -f {infile} -o {outfile}' % (sys.executable, self.test_precompiler)
        compiler = CachedCompilerFilter(command=command, **self.cached_precompiler_args)
[...]
```

And now the tests pass:

```
django-admin test --settings=compressor.test_settings compressor -r
[...]
Ran 387 tests in 1.641s

OK (skipped=12)
```

I'm not sure if the `cache.clear()` is an acceptable fix, or if tests are even supposed to pass when not run in the default order.

I was experimenting with this because I wanted to reproduce the test failures in Github Actions, but no luck with those yet.

**Comment by carltongibson** [comment]
Hey @cuu508 -- that sounds like a good PR. Good catch. 


Ref the GHA tests: if you can get a lead that would be amazing. It's on my list, but I've not had time to dig in again. (Failure to reproduce locally was the issue...)

**Comment by cuu508** [comment]
@carltongibson on the GHA tests: I did a bunch of experimenting, haven't cracked it, but at least I have an isolated testcase:

```python
from urllib.parse import urljoin

from django.test import TestCase


def script_prefix():
    return "hey/"


class Lazy(str):
    def __str__(self):
        return script_prefix() + self[1:] if self.startswith('/') else self

    def __unicode__(self):
        return str(self)

    def split(self, *args, **kwargs):
        """
        Override ``.split()`` method to make it work with ``{% static %}``.
        """
        return str(self).split(*args, **kwargs)


class OfflineCompressBasicTestCase(TestCase):
    def test_it(self):
        foo = Lazy("/static/")
        self.assertEqual(urljoin(foo, "foo/bar"), "hey/static/foo/bar")

```

On my local system it works. On Github Actions – 

```
 ======================================================================
FAIL: test_it (compressor.tests.test_isolated.OfflineCompressBasicTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/django-compressor/django-compressor/compressor/tests/test_isolated.py", line 27, in test_it
    self.assertEqual(urljoin(foo, "foo/bar"), "hey/static/foo/bar")
AssertionError: '/static/foo/bar' != 'hey/static/foo/bar'
- /static/foo/bar
+ hey/static/foo/bar
? +++
```

The `compressor.tests.test_offline.LazyScriptNamePrefixedUrl` class is not mimicking `str` well enough to fool `urllib.urlparse.urljoin`. Not quite sure what it is missing.

**Comment by cuu508** [comment]
I think I figured it out: https://github.com/django-compressor/django-compressor/pull/1079
