### ISSUE TITLE
Large JS cache folder

### ISSUE THREAD

**Issue by MrPiethon** [django-compressor/django-compressor#1084]
Compressor seems to be creating new js cache files on every request. I'm currently at 10GB and my entire project only has ~15 script files.

Related SO: https://stackoverflow.com/questions/70059888/django-compressor-has-a-js-cache-folder-that-is-using-an-absurd-amount-of-space

**Comment by MrPiethon** [comment]
**Cause**
Template variables that change on every request. 

**Solution**
Move it out of the tags. For cases where you need a csrf_token, due it through getCookie or a third party library js-cookie.
For more information, reference: https://docs.djangoproject.com/en/3.1/ref/csrf/#acquiring-the-token-if-csrf-use-sessions-and-csrf-cookie-httponly-are-false

---

Would be nice to include this in the docs.

**Comment by carltongibson** [comment]
I kind of think this **is** documented, but if you'd like to suggest an adjustment, happy to take a look.

**Comment by carltongibson** [comment]
@RanaNematollahi Just delete the cache folder in `STATIC_ROOT`. It'll be recreated as needed. 

Short of an actual suggestion (PR) for a change to the docs, I don't think this is actionable, so I'm going to close it. 

Happy to look at a PR!
