### ISSUE TITLE
Create a new release on PyPI

### ISSUE THREAD

**Issue by albertyw** [django-compressor/django-compressor#1088]
Django 4 is out now but the most current PyPI release (v2.4.1) isn't compatible.  It seems like some work like #1072 and #1076 has already been put in to make django-compressor compatible with Django 4.  A v3.0 release of django-compressor has already been cut (bff5be8c3c1e1772c3bce30167c3a4c94f7a9c49) though it doesn't have the commits for Django 4 compatibility.  Can we release v3.0.0 and a current v3.1.0 to PyPI?

I'd be happy to make changelog and version number PRs if that would speed things along.

**Comment by carltongibson** [comment]
Hi @albertyw. Yes. We've just been pulling together the last release blockers, which are resolved as of yesterday, and will now turn to a release. I hope to get it together in the next week. 

In the meantime you can install the develop branch which is compatible.

**Comment by diox** [comment]
I can take care of this later today or tomorrow, @carltongibson. Thanks for your work on getting the blockers dealt with.

**Comment by diox** [comment]
3.0 has been released. https://pypi.org/project/django-compressor/3.0/#files 

I had already prepared a changelog, which I updated in 101cc45b4a2af45fea418be8f636bc6d0b22ada9 and 4455ecec2e5cfac73f463957ab0f8efc9e0b8645 so it should be pretty good. Shout if anything is missing.

**Comment by carltongibson** [comment]
Super, thanks @diox! 🎁

**Comment by carltongibson** [comment]
Hey @diox — can you push the 3.0.0 tag when you get a moment? Thanks!

**Comment by diox** [comment]
Woops, here it is https://github.com/django-compressor/django-compressor/tree/3.0
