### ISSUE TITLE
There is no tag 3.1

### ISSUE THREAD

**Issue by DmytroLitvinov** [django-compressor/django-compressor#1094]
Create tag `3.1` to see changelog between 3.0 and 3.1. Mention of 3.1 is in [Changelog](https://github.com/django-compressor/django-compressor/blob/a78587f8c68915a2b46c9492722a3cb1f23578f6/docs/changelog.txt#L7)

**Comment by diox** [comment]
Oops, forgot to push it, thanks for raising this. [Fixed](https://github.com/django-compressor/django-compressor/tree/3.1).
