### ISSUE TITLE
Add custom filter to django-compressor

### ISSUE THREAD

**Issue by foobar-translate** [django-compressor/django-compressor#1106]
Hello. I read the readme and searched for the document, the readme says "other post-processing tool" and "fairly easy to implement a custom filter" you can see, so I thought it's amazing that I can do something like: 

```
# templatetags

@register.filter
def justTestFilter(value):
    return "this is test." + value

# an html 

{% compress js inline | justTestFilter %}
<script> console.log("hi.") </script> 
{% endcompress %}
```

and this results 

```
this is test.<script> console.log("hi.") </script> 
```

But this didn't work and I have no idea how to implement something similar to this. The above is just an example but in my case I want to add an obfuscation filter to the scripts for example. Is it possible? Thanks

**Comment by diox** [comment]
Hi,

Compressor filters are not templatetag filters. Look at https://django-compressor.readthedocs.io/en/latest/settings.html#django.conf.settings.COMPRESS_FILTERS and at the code in https://github.com/django-compressor/django-compressor/tree/develop/compressor/filters for inspiration for how to write custom ones. If you need further assistance, please head over to stackoverflow or similar.
