### ISSUE TITLE
Incompatibility with Django 4.1

### ISSUE THREAD

**Issue by th3hamm0r** [django-compressor/django-compressor#1114]
The CI run for #1113 triggered this error, because 4.1a1 has been released a few days ago.

The issue:
https://github.com/django-compressor/django-compressor/blob/14cf93d413cc0f8e5438bbf184dc18b613733dc1/compressor/management/commands/compress.py#L326
Django 4.1 removes the ability to set a boolean value here (see https://docs.djangoproject.com/en/dev/releases/4.1/#features-removed-in-4-1).

A fix could be to set it to an empty list starting with django 3.2? see https://docs.djangoproject.com/en/3.2/howto/custom-management-commands/#django.core.management.BaseCommand.requires_system_checks

**Comment by diox** [comment]
> A fix could be to set it to an empty list starting with django 3.2?

That works for me.

**Comment by thezentrader** [comment]
Will there be a new release with this fix anytime soon?

**Comment by diox** [comment]
Yes. In the meantime, you can pip install the `develop` branch.

**Comment by thezentrader** [comment]
I am doing that already but wanted to know if you had a ETA for the release. I would like to use that in prod 😄

**Comment by diox** [comment]
I'm planning for the new django-compressor release to coincide with Django 4.1 (stable, non-beta/rc) release date.
