### ISSUE TITLE
SuspiciousFileOperation at / The joined path (/styling/tenant/ltr/assets/plugins/iconfonts/icons.css) is located outside of the base path component (/home/user/projects/code/tara/taraproject/tara/static)

### ISSUE THREAD

**Issue by eugenewere** [django-compressor/django-compressor#1119]
Trying to intergrate MINIO , Django and Django Compressor for  serving static files but I get this error on running 

`python manage.py compress --force`

The Error is: 

`CommandError: An error occurred during rendering /home/user/projects/code/itara/taraproject/tara/tenant/templates/pages/tara/userAccount/settings.html: The joined path (/styling/tenant/ltr/assets/css/color-theme.css) is located outside of the base path component (/home/user/projects/code/tara/taraproject/tara/static)
`

My Configuration for MINIO and Compressor:

`

    HTML_MINIFY = True
    KEEP_COMMENTS_ON_MINIFYING = True
    STATICFILES_DIRS = [
        os.path.join(BASE_DIR, 'static'),
    ]

    STATICFILES_FINDERS = (
        'django.contrib.staticfiles.finders.FileSystemFinder',
        'django.contrib.staticfiles.finders.AppDirectoriesFinder',
        'compressor.finders.CompressorFinder',
    )
    STATIC_ROOT = f"http://{os.getenv('MINIO_ENDPOINT')}/"
    COMPRESS_ROOT = STATIC_ROOT

    STATIC_URL = f"http://{os.getenv('MINIO_ENDPOINT')}/"
    COMPRESS_URL = STATIC_URL

    STATICFILES_STORAGE = 'django_minio_backend.models.MinioBackendStatic'
    COMPRESS_STORAGE = STATICFILES_STORAGE

    COMPRESS_OUTPUT_DIR = f"http://{os.getenv('MINIO_ENDPOINT')}/styling/CACHE/"
    # COMPRESS_OUTPUT_DIR = '/styling/CACHE/'
    COMPRESS_OFFLINE_MANIFEST = 'manifest.json'
    COMPRESS_ENABLED = True
    COMPRESS_OFFLINE = False
    COMPRESS_CSS_HASHING_METHOD = 'content'
    COMPRESS_FILTERS = {
        'css': [
            'compressor.filters.css_default.CssAbsoluteFilter',
            'compressor.filters.cssmin.rCSSMinFilter',
        ],
        'js': [
            'compressor.filters.jsmin.JSMinFilter',
        ]
    }

    DEFAULT_FILE_STORAGE = 'django_minio_backend.models.MinioBackend'
    MINIO_ENDPOINT = os.getenv('MINIO_ENDPOINT')

    MINIO_MEDIA_FILES_BUCKET = 'local-media'  # replacement for STATIC_ROOT
    MINIO_STATIC_FILES_BUCKET = 'styling'  # replacement for MEDIA_ROOT
    MINIO_BUCKET_CHECK_ON_SAVE = False  # Create bucket if missing, then save

    MINIO_ACCESS_KEY = os.getenv('MINIO_ACCESS_KEY')
    MINIO_SECRET_KEY = os.getenv('MINIO_SECRET_KEY')
    MINIO_USE_HTTPS = eval(str(os.getenv('MINIO_USE_HTTPS', False)))
    MINIO_URL_EXPIRY_HOURS = timedelta(days=5)  # Default is 7 days (longest) if not defined
    MINIO_CONSISTENCY_CHECK_ON_START = False

    MINIO_PUBLIC_BUCKETS = [
        MINIO_MEDIA_FILES_BUCKET,
        MINIO_STATIC_FILES_BUCKET
    ]
`

**Comment by toabi** [comment]
I have the same issue. Did you find out anything more?

**Comment by carltongibson** [comment]
You're trying to include a file that's located outside your (presumably) `STATIC_ROOT`. Django doesn't allow this, since it might imply file system traversal. 

It's essentially a config error. You'll need to review the staticfiles docs, and make sure you've added all the staticfiles dirs and run collectstatic etc.

https://docs.djangoproject.com/en/4.1/howto/static-files/#deployment

It's not really a compressor issue I think.
