### ISSUE TITLE
Release a version with the Django 4.1 fix

### ISSUE THREAD

**Issue by cuu508** [django-compressor/django-compressor#1133]
I ran into a compatibility issue with django-compressor 4.0 and Django 4.1, which was released today.

I'm happy to see the fix has already been commited and merged: https://github.com/django-compressor/django-compressor/commit/219b00b7375d2531f4c8f8e8f3b84ddcf48c673c

It would be great to also have a new release with this fix. Are there currently any blockers?

**Comment by diox** [comment]
I was waiting on Django 4.1 stable to be released. I'll ship django-compressor 4.1 shortly.

**Comment by carltongibson** [comment]
Thanks @diox! 🏅

**Comment by diox** [comment]
https://pypi.org/project/django-compressor/4.1/ should now be available.

**Comment by cuu508** [comment]
Awesome, thank you!
