### ISSUE TITLE
4.1 caused an outage

### ISSUE THREAD

**Issue by alexei** [django-compressor/django-compressor#1138]
I don't know what you did in 4.1, but it didn't work. I have about 500 alerts in my inbox all saying the same thing:

```
OfflineGenerationError at ... You have offline compression enabled but key "..." is missing from offline manifest. You may need to run "python manage.py compress".
```

Reverting to 4.0 brought the site back online.

**Comment by alexei** [comment]
Note this is more of a warning for other users, rather than a critique for django-compressor and its authors.

**Comment by diox** [comment]
Hi,

Could you please submit a testcase ?

**Comment by carltongibson** [comment]
I'd have to say, can you 100% verify that you updated the manifest live? (Can you provide a minimal project showing an incorrect manfiest being generated?)

(This kind of thing is usually a stale manifest issue in my years using compressor... )

**Comment by alexei** [comment]
I am ruling out human error, because our deployments are highly scripted and based on the same recipes we’ve been using for the past 4 years. All low level commands are wrapped, so when processing static files, the computer runs essentially three commands: collect static files, remove the manifest file, then compress. When initiating a release, one decides whether to process static files or not, but they don’t decide on the underlying commands.

On Wednesday, the changes we had were about 10 dependencies which got updated the day before, and a bug fix. In this case the release consisted of just pushing the code i.e. `git push …` (deps are installed automatically)

And that I did. I ran it inside a GH Action and the command itself completed successfully. Thus I’m also ruling out system failure and anything of that sort.

Given I only pushed the code, and there were no changes to the static files, it should have just worked. However as soon as the deployment completed, I started getting alerts. The first thing I did was to manually run the command that processes static files. That didn’t help. Then I checked the bucket and saw no trace of the manifest file. Thinking I must have done something wrong, I initiated a new automatic release with all options turned on: db migrations and static files processing. That didn’t help either.

At this point I started re-reviewing the changes, when I noticed django-compressor got updated the day before so it became my #1 suspect. I reverted that particular commit, then did another automatic release (push changes + process static files). When that completed, the site got back up.

That’s all I know for now. I’ll give django-compressor 4.1 another shot as soon as I can and see what happens.

**Comment by diox** [comment]
As it stands we don't have enough information to go on. Please submit your settings and ideally a testcase with some of the templates triggering the issue too, otherwise there isn't much we can do.

**Comment by mdunc** [comment]
Same issue here with Django 3.2.14 with static assets stored in S3 (using django-storages for that).  Upgraded to the latest django-compressor and ran in to the exact same error.  I tried recompressing and running "manage.py collectstatic", but no such luck.  I disabled offline compression, but then the error changed to not being able to find a referenced static asset.

```
Traceback (most recent call last):
  File "/var/task/django/core/handlers/exception.py", line 47, in inner
  response = get_response(request)
  File "/var/task/django/core/handlers/base.py", line 204, in _get_response
  response = response.render()
  File "/var/task/django/template/response.py", line 105, in render
  self.content = self.rendered_content
  File "/var/task/django/template/response.py", line 83, in rendered_content
  return template.render(context, self._request)
  File "/var/task/django/template/backends/django.py", line 61, in render
  return self.template.render(context)
  File "/var/task/django/template/base.py", line 170, in render
  return self._render(context)
  File "/var/task/django/template/base.py", line 162, in _render
  return self.nodelist.render(context)
  File "/var/task/django/template/base.py", line 938, in render
  bit = node.render_annotated(context)
  File "/var/task/django/template/base.py", line 905, in render_annotated
  return self.render(context)
  File "/var/task/django/template/loader_tags.py", line 150, in render
  return compiled_parent._render(context)
  File "/var/task/django/template/base.py", line 162, in _render
  return self.nodelist.render(context)
  File "/var/task/django/template/base.py", line 938, in render
  bit = node.render_annotated(context)
  File "/var/task/django/template/base.py", line 905, in render_annotated
  return self.render(context)
  File "/var/task/compressor/templatetags/compress.py", line 151, in render
  return self.render_compressed(context, self.kind, self.mode, forced=forced, log=log, verbosity=verbosity)
  File "/var/task/compressor/templatetags/compress.py", line 113, in render_compressed
  cache_key, cache_content = self.render_cached(compressor, kind, mode)
  File "/var/task/compressor/templatetags/compress.py", line 91, in render_cached
  cache_key = get_templatetag_cachekey(compressor, mode, kind)
  File "/var/task/compressor/cache.py", line 97, in get_templatetag_cachekey
  "templatetag.%s.%s.%s" % (compressor.cachekey, mode, kind))
  File "/var/task/django/utils/functional.py", line 48, in __get__
  res = instance.__dict__[self.name] = self.func(instance)
  File "/var/task/compressor/base.py", line 209, in cachekey
  [self.content] + self.mtimes).encode(self.charset), 12)
  File "/var/task/django/utils/functional.py", line 48, in __get__
  res = instance.__dict__[self.name] = self.func(instance)
  File "/var/task/compressor/base.py", line 203, in mtimes
  for kind, value, basename, elem in self.split_contents()
  File "/var/task/compressor/js.py", line 17, in split_contents
  filename = self.get_filename(basename)
  File "/var/task/compressor/base.py", line 168, in get_filename
  raise UncompressableFileError(
compressor.exceptions.UncompressableFileError: 'js/chart.min.js' could not be found in the COMPRESS_ROOT '/var/task/static' or with staticfiles.
```

Reverting to a previous version fixed the issue.

**Comment by petewalker** [comment]
It looks like a breaking change was introduced - the introduction of `COMPRESS_OFFLINE_MANIFEST_STORAGE`

As [per the documentation](https://django-compressor.readthedocs.io/en/4.1/remote-storages.html#using-staticfiles), I have the following setup:

**settings.py**

```py
COMPRESS_STORAGE = 'myapp.storage.CachedS3Boto3Storage'
STATICFILES_STORAGE = 'myapp.storage.CachedS3Boto3Storage'
```

**storage.py**

```py
from django.core.files.storage import get_storage_class
from storages.backends.s3boto3 import S3Boto3Storage

class CachedS3Boto3Storage(S3Boto3Storage):
    """
    S3 storage backend that saves the files locally, too.
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.local_storage = get_storage_class(
            "compressor.storage.CompressorFileStorage")()

    def save(self, name, content):
        self.local_storage._save(name, content)
        super().save(name, self.local_storage._open(name))
        return name
```

In order to have the manifest upload again, I had to add the following to my `settings.py`:

```py
COMPRESS_OFFLINE_MANIFEST_STORAGE = 'myapp.storage.CachedS3Boto3Storage'
```
