### ISSUE TITLE
Too many JS files cached, literally dozens of GBs

### ISSUE THREAD

**Issue by tanjyeyee** [django-compressor/django-compressor#1149]
I use database cache, and my cache table is always filling up with in this cache key format:

```
...
django_compressor.templatetag.f06ee0a86962.inline.js
django_compressor.templatetag.a49affe0c1e1.inline.js
django_compressor.templatetag.6e37d013d080.inline.js
...
```

There are literally 100,000s of these in my cache table.

I've deleted them, but they just keep accumulating.

I'm guessing that every user is getting their own cached output files, instead of the same cached files being shared for everyone.

My settings.py:

```

COMPRESS_ENABLED = True
COMPRESS_CSS_HASHING_METHOD = 'content'
COMPRESS_FILTERS = {
    'css':[
        'compressor.filters.css_default.CssAbsoluteFilter',
        'compressor.filters.cssmin.rCSSMinFilter',
    ],
    'js':[
        'compressor.filters.jsmin.JSMinFilter',
    ]
}
HTML_MINIFY = False

...

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.db.DatabaseCache',
        'LOCATION': 'cache_table',
        'TIMEOUT': None,
        'OPTIONS': { 'MAX_ENTRIES': 1000000 },
    }
}
```

How do I fix this?

**Comment by diox** [comment]
Hi,

This is impossible to tell without seeing your templates and calls to `{% compress %}`.

**Comment by tanjyeyee** [comment]
Hi @diox, apparently if I generate a different CSRF token within the {% compress js inline %} clauses, it caches a new version of it each time a user reloads.

That's fine with me.

But is there a way to limit the cache timeout?

The default seems to be 30 days, maybe I can cut it down to 3 or 7?

**Comment by diox** [comment]
You could customize `COMPRESS_REBUILD_TIMEOUT` but really, there is no reason to use `{% compress %}` on something that includes a csrf token generation. I'd suggest you move that outside of the `{% compress %}` call or remove that call entirely, it's doing you more harm than good.

Closing as there is no compressor issue here.
