### ISSUE TITLE
New release to have `rcssmin` and `rjsmin` Python 3.11 wheels

### ISSUE THREAD

**Issue by stegayet** [django-compressor/django-compressor#1167]
## Context
I've seen that https://github.com/django-compressor/django-compressor/pull/1131 and https://github.com/django-compressor/django-compressor/pull/1130 have been merged to upgrade `rcssmin` and `rjsmin` dependencies, however no release has been made since, may I ask for a new release ?

## Rationale
`rcssmin` and `rjsmin`  have Python 3.11 wheels (see https://pypi.org/project/rcssmin/#files and https://pypi.org/project/rjsmin/#files) and having a new `django-compressor` release would enable projects using this library to upgrade to Python 3.11 without loosing wheels.

**Comment by diox** [comment]
I can, yes, thanks for pointing that out.

This new release will drop Django 2.2 and Python 3.7 support (at least officially - it may still work, but I removed these versions from the test matrix), but I think that's acceptable.

**Comment by diox** [comment]
I released 4.2: 

If you're using it with Python 3.11, be aware https://github.com/django-compressor/django-compressor/issues/1158 has been reported. Also, it looks like tests are failing because of a setup issue, I'll fix them, might have to release 4.2.1 ...

**Comment by diox** [comment]
Released 4.3 with official Python 3.11 support.

**Comment by stegayet** [comment]
Thanks a lot for your quick reply !
