### ISSUE TITLE
Please update readthedocs with release 4.2 and 4.3

### ISSUE THREAD

**Issue by dgilmanAIDENTIFIED** [django-compressor/django-compressor#1171]

**Comment by diox** [comment]
Hi,

I had not noticed the build had failed. I'll take a look.

**Comment by diox** [comment]
`latest` is fixed - https://django-compressor.readthedocs.io/en/latest/changelog.html

`stable` and 4.3, 4.2 tags don't build because of the outdated configuration file that messes up the dependencies. I'll have to release a 4.3.1 to fix that (and forget 4.2, or release 4.2.1 as well...)

**Comment by diox** [comment]
I released 4.3.1, fixing https://django-compressor.readthedocs.io/en/stable/changelog.html. I can't upload 4.2 and 4.3 docs without messing up with the repos, as the contents of the repos for those tags contain an obsolete readthedocs configuration that is not working.

**Comment by dgilmanAIDENTIFIED** [comment]
Not a problem, glad to have caught a legit issue!
