### ISSUE TITLE
Slim down package

### ISSUE THREAD

**Issue by lociii** [django-compressor/django-compressor#1174]
The [`MANIFEST`](https://github.com/django-compressor/django-compressor/blob/develop/MANIFEST.in) includes lots of files in the distribution package that are not necessary to run `django-compresssor`. All of these statements are more than 10 years old - it may be time to reconsider these choices.

More specifically, I would question why the following are shipped with the package:
- `include Makefile`
  - only required to run tests and build coverage report
- `include tox.ini`
  - only required to run tests
- `recursive-include docs *`
  - docs on https://django-compressor.readthedocs.io/en/latest/
- `recursive-include requirements *`
  - required packages to run tests
- `recursive-include compressor/templates/compressor *.html`
  - example templates on how to integrate compressed files
- `recursive-include compressor/tests/media *.js *.css *.png *.coffee`
  - doesn't even exist anymore
- `recursive-include compressor/tests/test_templates *.html`
  - templates used in tests

It's not much but could help slim down installs, docker images, etc.

**Comment by carltongibson** [comment]
Outdated includes can be removed but downstream packaging folks (for Linux distributions and such) like to have the tests and other such things included so they can test the package themselves.
