### ISSUE TITLE
Django's `get_storage_class` is deprecated in 4.2 (Django 5.1 compat.)

### ISSUE THREAD

**Issue by AngellusMortis** [django-compressor/django-compressor#1187]
Got the following warning running tests in Django 4.2:

```
/usr/local/lib/python3.11/site-packages/django/core/files/storage/__init__.py:32 RemovedInDjango51Warning: django.core.files.storage.get_storage_class is deprecated in favor of using django.core.files.storage.storages.
```

**Comment by carltongibson** [comment]
Hi @AngellusMortis thanks for the report. 

The progress here would be to make a compatibility shim using the new approach on 4.2+, which we'd drop when that's the minimum supported version. 

Is that something you'd like to have a go at doing?

**Comment by jvacek** [comment]
This won't be deprecated until 5.1, so I don't think this should block Django 4.2 compat just yet

**Comment by carltongibson** [comment]
Yep. It's just a warning at this stage. 

```pytb
  File ".../compressor/storage.py", line 115, in _setup
    self._wrapped = get_storage_class(settings.COMPRESS_STORAGE)()
  File ".../django/core/files/storage/__init__.py", line 32, in get_storage_class
    warnings.warn(GET_STORAGE_CLASS_DEPRECATED_MSG, RemovedInDjango51Warning)
django.utils.deprecation.RemovedInDjango51Warning: django.core.files.storage.get_storage_class is deprecated in favor of using django.core.files.storage.storages.
```

**Comment by adnathanail** [comment]
Hi - I've just had a go at creating a shim in #1216, please let me know if there are any issues with it!

**Comment by carltongibson** [comment]
#1244 was a duplicate. Copying comment from there: 

> We need to adjust how we reference the storages. There are a couple of PRs pointing in that direction, but we need to sit down and decide the pattern.
>
> My current thinking is that we need to add a COMPRESS_STORAGE_ALIAS setting, and then have compressor use that if defined, or add an entry using COMPRESS_STORAGE if not, probably at the moment of populating the AppRegistry, i.e. when INSTALLED_APPS is processed.
>
> It's on my radar to address this (if still pending) after DjangoCon Europe, so in the next few weeks.
