### ISSUE TITLE
Releasing a new version with Django 4.2 support

### ISSUE THREAD

**Issue by irtazaakram** [django-compressor/django-compressor#1190]
When can we expect the release of the new version with Django 4.2, considering that the master branch has already been updated?

Thanks,

**Comment by diox** [comment]
Hi,

I wasn't in a rush to do it since the latest release should already work with Django 4.2, despite missing the classifier in `setup.py`. I'll probably do it later this week/month.

**Comment by diox** [comment]
Released 4.4. Tests are currently broken but that's a separate issue (which I believe only affects tests), https://github.com/django-compressor/django-compressor/issues/1194
