### ISSUE TITLE
Fix tests with Python 3.9.17, 3.10.12 and 3.11.4

### ISSUE THREAD

**Issue by diox** [django-compressor/django-compressor#1194]
The fixes in the latest minor versions of Python 3.9, 3.10 and 3.11 broke our tests. This is visible [in the CI tests results for the django-compressor 4.4 release](https://github.com/django-compressor/django-compressor/actions/runs/5395081264/).

Changelogs:
- https://www.python.org/downloads/release/python-3917/
- https://www.python.org/downloads/release/python-31012/
- https://www.python.org/downloads/release/python-3114/

The breakage occurs in offline compression tests that play with Django's `get_script_prefix()` and `set_script_prefix()`. My best guess is that something is cached that shouldn't be, or maybe something is meant to stay lazy and isn't. That feature and the tests is quite brittle, it depends on being able to render a dynamic `STATIC_URL` setting depending on the request.

**Comment by carltongibson** [comment]
0679e97bfe99257b983a7d716992b39cc49b406d changed to `importlib`. I wonder if there's a subtle difference of behaviour in the `reload` implementations. 🤔


(But this not currently reproducing locally for me... Gah. )

**Comment by carltongibson** [comment]
Sorry, doh. I don't read... 

> ...  latest minor versions of Python 3.9, 3.10 and 3.11 ... 

Indeed, updating Python surfaces the issue. 

🤦‍♀️

**Comment by diox** [comment]
Yeah... I've edited the description with some findings. I tried to convert `LazyScriptNamePrefixedUrl` in the affected test file to use django's `lazy()` instead but that makes things worse - there is a reason why that was a custom implementation in the first place...

**Comment by bcail** [comment]
Adding the following to `LazyScriptNamePrefixedUrl` seems to help for me locally:
```
    def lstrip(self, *args, **kwargs):
        """
        Override ``.lstrip()`` method to make it work with ``{% static %}``.
        """
        return str(self).lstrip(*args, **kwargs)
```

Looks like the cpython commit causing the issue may be https://github.com/python/cpython/pull/104575.

**Comment by diox** [comment]
@bcail definitely the culprit and the fix - would you mind submitting a PR with that change, so you can get the credit ?

**Comment by bcail** [comment]
Sure - submitted #1196.

**Comment by diox** [comment]
This only affected tests so I'm going to do a release with that fix eventually, but not today.
