### ISSUE TITLE
OSSFuzz Integration

### ISSUE THREAD

**Issue by capuanob** [django-compressor/django-compressor#1215]
Good evening,

I am looking to integrate django-compressor into OSSFuzz. If you are not familiar with OSSFuzz, it is Google's platform for continuous fuzzing of open-source software. In order to get the most out of this program, it would be greatly beneficial to be able to merge in my fuzz harness and build scripts into the upstream repository and contribute bug fixes if they come up. Is this something that you would support me putting the effort into?

Thank you in advance!

**Comment by carltongibson** [comment]
Hi @capuanob — thanks for the interest! 

Could you open a branch with what you have in mind? 

It sounds interesting. I don't know much about the OSS Fuzz project, but IIRC @apollo13 was involved in discussions for tests on Django.

**Comment by capuanob** [comment]
@carltongibson Hi Carlton,

I have yet to implement anything, as I wanted to make sure I had permission to do before getting started! I would submit a fuzzing harness, a CIfuzz.yml to integrate PRs into fuzz-testing, and a build.sh to build a Dockerfile for fuzzing.

Does this sound like something you would support me pursuing? All I would need from you is the eventual PR reviews!

**Comment by apollo13** [comment]
I wonder what benefit django-compressor has from OSSFuzz integration. django-compressor runs "offline" on (mostly?) trusted data. I'd imagine that there are other libraries handling userinput (markdown stuff etc?) would benefit way more from OSSFuzz integration. That should not hold you off but the cost/benefit ratio seems rather low to me personally.

**Comment by carltongibson** [comment]
Thanks @apollo13 — good insight. 

@capuanob I'll close based on that, but happy if you want to follow up. 

🎄
