### ISSUE TITLE
Set compressor_file_storage to CompressorFileStorage

### ISSUE THREAD

**Issue by dbartenstein** [django-compressor/django-compressor#1253]
With the latest django-compressor release 4.5, the `compressor_file_storage` was set to `COMPRESS_STORAGE`:
https://github.com/django-compressor/django-compressor/commit/752edfaf0c4c10212792474479cca90d918c9d6a#diff-d2bf8e4739c94f5a9a6091b67159fc008af6e6ada59770261133cd3d854effc6R64

When using s3 as storage backend, the following error is returned:
`NotImplementedError: This backend doesn't support absolute paths.`

### Possible solution
```
compressor_file_storage = SimpleLazyObject(
    lambda: get_storage(alias="compressor_file_storage", storage_class="compressor.storage.CompressorFileStorage"
)
```

**Comment by bigEvilBanana** [comment]
same for me. downgraded to 4.4

**Comment by dbartenstein** [comment]
> same for me. downgraded to 4.4

@bigEvilBanana thanks for the confirmation. We also downgraded to 4.4 - let’s wait for 4.6.

**Comment by carltongibson** [comment]
@dbartenstein you should be able to configure the S3 storage for the `compressor` alias in the new `storages` setting no? 

What would that look like? (It would help to resolve this to see a working config)

**Comment by dbartenstein** [comment]
> @dbartenstein you should be able to configure the S3 storage for the `compressor` alias in the new `storages` setting no?
> 
> What would that look like? (It would help to resolve this to see a working config)

@carltongibson thanks for your reply!

It might be a misconfiguration on our side. Do I get it correctly that the following steps should yield a correct configuration?

1. Create S3 StaticStorage according to https://django-compressor.readthedocs.io/en/stable/remote-storages.html# - especially the definition of `self.local_storage`
2. Remove COMPRESS_STORAGE and COMPRESS_OFFLINE_MANIFEST_STORAGE config entries
3. Add "compressor" and "compressor-offline" entries to storages: 
```
STORAGES = {
    "default": {
        "BACKEND": "project.storages.PublicMediaStorage",
    },
    "staticfiles": {"BACKEND": project.storages.StaticStorage"},
    "compressor": {"BACKEND": "project.storages.StaticStorage"},
    "compressor-offline": {"BACKEND": "project.storages.StaticStorage"},
}
```

@bigEvilBanana can you please also give it another try with 4.5?

**Comment by carltongibson** [comment]
@dbartenstein I'm on holiday 😅 but yes that **should** work IMO. 

If it doesn't, if you had the time, a minimal reproduction project would speed me up debugging it when I get home.

**Comment by dbartenstein** [comment]
> @dbartenstein I'm on holiday 😅 but yes that **should** work IMO.
> 
> If it doesn't, if you had the time, a minimal reproduction project would speed me up debugging it when I get home.

@carltongibson enjoy your holiday!

**Comment by dbartenstein** [comment]
> @dbartenstein you should be able to configure the S3 storage for the `compressor` alias in the new `storages` setting no?
> 
> What would that look like? (It would help to resolve this to see a working config)

@carltongibson 
I discovered the issue when running unit tests.
```
  File "/opt/zemtu/.local/lib/python3.11/site-packages/compressor/css.py", line 23, in split_contents
    filename = self.get_filename(basename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zemtu/.local/lib/python3.11/site-packages/compressor/base.py", line 177, in get_filename
    filename = compressor_file_storage.path(basename)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/zemtu/.local/lib/python3.11/site-packages/django/core/files/storage/base.py", line 122, in path
    raise NotImplementedError("This backend doesn't support absolute paths.")
NotImplementedError: This backend doesn't support absolute paths.
```

The S3 storage does **not** implement `path` and therefore `compress_file_storage.path` is called as fallback. https://github.com/django-compressor/django-compressor/blob/cf38cee1da39bc1fbcf8c10bd2ba30b7f297b51a/compressor/base.py#L175

`compress_file_storage` is retrieved via `get_storage`() and therefore is also set to S3 storage ... instead it should be of type `compressor.storage.CompressorFileStorage`
https://github.com/django-compressor/django-compressor/blob/cf38cee1da39bc1fbcf8c10bd2ba30b7f297b51a/compressor/storage.py#L63

**Comment by saadmk11** [comment]
We ran into the same issue trying to upgrade `django-compressor` to `4.5` (using S3 Backend). After doing some debugging we came to the same conclusion as @dbartenstein. i.e `compressor_file_storage` was set to a storage backend that does not implement `.path(...)`

**Comment by carltongibson** [comment]
@saadmk11 Does setting `STORAGES` as per the comment above resolve the issue? 

Is there a change we need to make here? A  minimal reproduce would still be handy.

**Comment by saadmk11** [comment]
@carltongibson Applying this diff should reproduce the issue.

```diff
diff --git a/compressor/storage.py b/compressor/storage.py
index a3978ad..28bb9ab 100644
--- a/compressor/storage.py
+++ b/compressor/storage.py
@@ -5,6 +5,7 @@ import time
 from urllib.parse import urljoin
 
 from django.core.files.storage import FileSystemStorage, InvalidStorageError, storages
+from django.core.files.storage.base import Storage
 from django.utils.functional import LazyObject, SimpleLazyObject
 
 from compressor.conf import settings
@@ -23,6 +24,15 @@ def get_storage(
         return storages[alias]
 
 
+class DummyPathNotImplementedStorage(Storage):
+    """
+    A dummy storage backend that mimics a remote storage that does not implement `.path()`
+    e.g. `storages.backends.s3.S3Storage`
+    """
+    def exists(self, name):
+        return True
+
+
 class CompressorFileStorage(FileSystemStorage):
     """
     Standard file system storage for files handled by django-compressor.
@@ -125,7 +135,11 @@ class BrotliCompressorFileStorage(CompressorFileStorage):
 
 class DefaultStorage(LazyObject):
     def _setup(self):
-        self._wrapped = get_storage()
+        # Passing the `storage_class` here so that we are able to override the
+        # `COMPRESS_STORAGE` settings in tests. Defaults arguments for
+        # functions are internally stored inside the function object.
+        # So, overriding the value in the settings does not make any difference
+        self._wrapped = get_storage(storage_class=settings.COMPRESS_STORAGE)
 
 
 default_storage = DefaultStorage()
diff --git a/compressor/tests/test_base.py b/compressor/tests/test_base.py
index 24280e1..f9170d7 100644
--- a/compressor/tests/test_base.py
+++ b/compressor/tests/test_base.py
@@ -552,3 +552,30 @@ class CompressorInDebugModeTestCase(SimpleTestCase):
         with open(result_filename, "r") as f:
             result = f.read()
         self.assertTrue(test_css_content not in result)
+
+
+class CompressorFileNameTestCase(SimpleTestCase):
+    def setUp(self):
+        self.override_settings = self.settings(
+            COMPRESS_ENABLED=True,
+            DEBUG=False,
+            COMPRESS_STORAGE=(
+                "compressor.storage.DummyPathNotImplementedStorage"
+            ),
+        )
+        self.override_settings.__enter__()
+
+    def tearDown(self):
+        self.override_settings.__exit__(None, None, None)
+
+    def test_get_filename(self):
+        css = (
+            '<link rel="stylesheet" href="/static/css/one.css" type="text/css" />'
+        )
+        compressor = CssCompressor("css", css)
+
+        with self.assertRaisesMessage(
+            NotImplementedError,
+            "This backend doesn't support absolute paths."
+        ):
+            compressor.get_filename("some-random-name")
```

**Comment by carltongibson** [comment]
OK, back from holiday, and got a chance to look at this properly. 

Yes, this looks like a bug in 752edfaf0c4c10212792474479cca90d918c9d6a — the fallback storage shouldn't be user defined in any way. 

When defining `compressor_file_storage` we should use `storages.create_storage()` directly I think. 

```
compressor_file_storage = SimpleLazyObject(
    lambda: storages.create_storage({"BACKEND: "compressor.storage.CompressorFileStorage"})
)
```


Also... 

```
+        # Passing the `storage_class` here so that we are able to override the
+        # `COMPRESS_STORAGE` settings in tests. Defaults arguments for
+        # functions are internally stored inside the function object.
+        # So, overriding the value in the settings does not make any difference
```

Ah, yes. Those a likely captured at the point of defining the function. The default should probably be `None` and then rebinding to use the settings value in that case at the start of the function. 

@dbartenstein @saadmk11 Would either of you like to make a PR here?

**Comment by carltongibson** [comment]
@dbartenstein @saadmk11 I opened #1257 to address this. Could you take a look? Thanks.

**Comment by carltongibson** [comment]
Version 4.5.1 is available now on PyPI. https://pypi.org/project/django-compressor/4.5.1/
