### ISSUE TITLE
Support for defer and async JavaScript loading

### ISSUE THREAD

**Issue by overshard** [django-compressor/django-compressor#132]
Would be awesome to have javascript support for defer and async loading of scripts.

{% compress js defer %}{% endcompress %}

Or it just recognizes <script defer src="script.js"></script> and keeps the tag on compression if all the scripts have it.

**Comment by prikhi** [comment]
I'd like to add this info to the docs, is Usage -> Examples an OK place?

**Comment by diox** [comment]
@prikhi : sure, that'd be great.
