### ISSUE TITLE
A way to flush the template cache / remove old files

### ISSUE THREAD

**Issue by defcube** [django-compressor/django-compressor#158]
I had several old cache files on disk that I wanted to clean up. The problem is that the templatetag_cachekey remembers the path of the old compressed .js. 

Short of flushing all of my memcache keys, is there a way to flush just the compressor templatetag keys?

**Comment by ivensrocha** [comment]
Does anybody knows if there is a clear cache command at this moment? How to make django-compressor begin to compress files all over again, setting new keys into the cache, since the cache files were deleted?

**Comment by Alcolo47** [comment]
I don't know any such python or management command but if you use the
default COMPRESS_STORAGE (ie file storage), You can use:

python: shutil.rmtree(os.path.join(settings.STATIC_ROOT,
settings.COMPRESS_OUTPUT_DIR))
sh: rm -rf  \$STATIC_ROOT/$COMPRESS_OUTPUT_DIR # (I add a mistake to
prevent from stupid copy/paste consequence.)

2015-11-19 13:04 GMT+01:00 Ivens Rocha <notifications@github.com>:

**Comment by julianklotz** [comment]
This one is old, but here are some notes:

* Clearing the cache directory (either its contents or the directory itself) didn't do the job for me
* What works for me is clearing the contents of the static folder like `cd /data/static; rm -rf .` (don’t copy-paste this, `rm -rf` is dangerous)
* Then run `./manage.py collectstatic`
* If you use offline compression, run `./manage.py compress`
