### ISSUE TITLE
You have offline compression enabled but key is missing from offline manifest

### ISSUE THREAD

**Issue by markstahler** [django-compressor/django-compressor#169]
I am not sure what this issue is but I am using offline generation and this error occurs after using the compress management command and accessing the website. Should each of those css files have their own key?

My Settings:
COMPRESS_URL = STATIC_URL
COMPRESS_ROOT = STATIC_ROOT
COMPRESS_OFFLINE = True
COMPRESS_OFFLINE_MANIFEST = "manifest.json"     # Is created in CACHE directory
COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter','compressor.filters.cssmin.CSSMinFilter']
COMPRESS_YUI_BINARY = os.path.join(PROJECT_ROOT, 'bin/yui.sh')
COMPRESS_JS_FILTERS = ['compressor.filters.closure.ClosureCompilerFilter']
COMPRESS_CLOSURE_COMPILER_BINARY = os.path.join(PROJECT_ROOT, 'bin/closure.sh')
COMPRESS_CLOSURE_COMPILER_ARGUMENTS = "--language_in=ECMASCRIPT5"
# COMPRESS_STORAGE = 'compressor.storage.GzipCompressorFileStorage' # DOES NOT WORK WTF

You have offline compression enabled but key "b68ba4d2116295c56138e439f1b03a03" is missing from offline manifest. You may need to run "python manage.py compress".

Request Method: GET
Request URL:    http://127.0.0.1:8000/
Django Version: 1.3.1
Exception Type: OfflineGenerationError
Exception Value:  
You have offline compression enabled but key "b68ba4d2116295c56138e439f1b03a03" is missing from offline manifest. You may need to run "python manage.py compress".
Exception Location: /srv/www/project/lib/python2.6/site-packages/compressor/templatetags/compress.py in render_offline, line 56

``` error
Variable    Value
forced  
False
self    
<compressor.templatetags.compress.CompressorNode object at 0x966764c>
compressor  
<compressor.js.JsCompressor object at 0x966732c>
key 
'b68ba4d2116295c56138e439f1b03a03'
offline_manifest    
{u'32e9172ad82f3b6d238cc7423a7f10c7': u'<link rel="stylesheet" href="/static/CACHE/css/a50381ce7ba9.css" type="text/css" media="screen" /><link rel="stylesheet" href="/static/CACHE/css/62afac347423.css" type="text/css" /><link rel="stylesheet" href="/static/CACHE/css/f336d54a5423.css" type="text/css" media="screen" /><link rel="stylesheet" href="/static/CACHE/css/5cf783d07673.css" type="text/css" />',
 u'b1bd8f68f96dfa53380b10881f8eb691': u'<script type="text/javascript" src="/static/CACHE/js/19522c6ee302.js"></script>',
 u'c6d6d2948d18188277e7a987c71e2bc3': u'<script type="text/javascript" src="/static/CACHE/js/90bda37980a5.js"></script>',
 u'dbe0b22545cd64193d8a875c3226b1ea': u'<script type="text/javascript" src="/static/CACHE/js/71056921eb77.js"></script>'}
```

**Comment by Ugandharnrs** [comment]
You have offline compression enabled but key is missing from offline manifest -Fix!!
check here..
https://www.youtube.com/watch?v=P7a6PgnWL1s

**Comment by morenoh149** [comment]
I'm seeing this in my deployment. I use compress like so

```
{% compress css %}
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-social.css' %}">
<link rel="stylesheet" type="text/css" href="{% sass_src 'css/base.scss' %}">
{% endcompress %}
```
could it be that compress cannot process the `sass_src` tag?

**Comment by amiknyc** [comment]
> I'm seeing this in my deployment. I use compress like so
> 
> ```
> {% compress css %}
> <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
> <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap-social.css' %}">
> <link rel="stylesheet" type="text/css" href="{% sass_src 'css/base.scss' %}">
> {% endcompress %}
> ```
> 
> could it be that compress cannot process the `sass_src` tag?

I ran into this issue and it has to do with the use of the "bootstrap.min.css" - if you use the non-minified version of bootstrap it should work.

Basically, compressor is trying to minify an already minified file in this case so it throws the error.
