### ISSUE TITLE
COMPRESS_PRECOMPILERS break css url()

### ISSUE THREAD

**Issue by domoritz** [django-compressor/django-compressor#226]
Since the precompiled files are served from another location, relative links in css files do not work anymore. 

The Problem can be solved by setting the output dir to an empty string.

    COMPRESS_OUTPUT_DIR = ''

However, it would be great to have processed urls in the css file that link to the right locations of images.

**Comment by gasman** [comment]
@woeye Having just stumbled across this problem myself, I propose to incorporate this workaround into django-libsass: https://github.com/torchbox/django-libsass/issues/8

+1 for a general solution to this within django-compressor, though!

**Comment by jsSenanga** [comment]
With django-compressor 1.5: 
the fix for #467 (db731cf01685001cf36188c4a70c44d3eb4dcc94) changed the CSSAbsoluteFilter, which makes breaks the  'PatchedSCSSCompiler' workaround.
Quickfix for that is adding the filename argument to the filter call:

```python

from compressor.filters.css_default import CssAbsoluteFilter
from django_libsass import SassCompiler

class PatchedSCSSCompiler(SassCompiler):
    def input(self, **kwargs):
        content = super(PatchedSCSSCompiler, self).input(**kwargs)
        kwargs.setdefault('filename', self.filename)
        return CssAbsoluteFilter(content).input(**kwargs)
```

**Comment by martyzz1** [comment]
Thanks @jsSenanga  I was just trying to track this issue down. Thanks @woeye for the original patch... 
I now have this working under Local dev mode and Heroku Deployment with herokuside collectstatic and compression....

**Comment by rafadev** [comment]
+1 for a permanent solution. In my case, I've had the problem with django-libsass, and solved it by using @jsSenanga 's solution. Thank you!

**Comment by karyon** [comment]
shoutout to @domoritz :) i thought it was really funny and random to see you here. (johannes linke speaking)

**Comment by domoritz** [comment]
Haha, awesome to meet you here @karyon and thanks for working on this issue. I don't quite remember what I was working on back then but it looks like a relevant issue judging from the number of people in this thread.
