### ISSUE TITLE
HMTLParser breaks on html attributes without spaces

### ISSUE THREAD

**Issue by ogirardot** [django-compressor/django-compressor#245]
Hi, 
playing around in regards to #241, i found out that the HTMLParser of django-compressor broke on this line (i must admin that the w3c validator told me about it and i forgot) 

    <script type="text/javascript"charset="utf-8" src="{{ STATIC_URL|default:"my_default_url/static/" }}js/libs/modernizr.min.js"></script>

changing it to this line :

    <script type="text/javascript" charset="utf-8" src="{{ STATIC_URL|default:"my_default_url/static/" }}js/libs/modernizr.min.js"></script>

make it work perfectly.
So it's all due to the  **type="text/javascript"charset="utf-8"** attributes with no space separating them.

**Comment by karyon** [comment]
i vote for closing this. it's in the realm of the parsers, and either one of the four supported ones can deal with this or this is just too broken.
