### ISSUE TITLE
Be more verbose when encountering an invalid template when running compress

### ISSUE THREAD

**Issue by lazerscience** [django-compressor/django-compressor#266]
If an invalid template is encountered during a run of the `compress` management command only a "Invalid Template..." message is logged which isn't very helpful for the user. It would be much nicer to log a unicode representation of the Exception as well to give a better debgging opportunity (of course depending on the verbosity level).

I'd add a pull request, but I'd like to know if this would be considered a good idea or if there's a reason for not doing so, and of course which verbosity level would be fine for this additional logging...

**Comment by karyon** [comment]
looks like this has been fixed in ec45b3e7c620b7d91fd92df08f2e4f72ed9211bb.
