### ISSUE TITLE
Compressing fails on current jquery-1.7.2.js with IE

### ISSUE THREAD

**Issue by pannal** [django-compressor/django-compressor#267]
Using Internet Explorer with a compressed JS file including jquery-1.7.2.js (included as the first .js file in source) results in an error in IE:
"Identifier expected, Code: 0, row: 1, symbol: 32568"

I've updated to the current django-compressor version to be sure.

```
COMPRESS_JS_FILTERS = [
    'compressor.filters.template.TemplateFilter',
    'compressor.filters.jsmin.SlimItFilter',
]
COMPRESS_PARSER = 'compressor.parser.LxmlParser'
```

**Comment by karyon** [comment]
if it works with another filter, i guess it shouldn't be fixed inside django-compressor, voting for closing this.

**Comment by diox** [comment]
Yeah, sounds like a bug in slimit.
