### ISSUE TITLE
AppConf not update Settings in compressor/conf.py in Django 1.4

### ISSUE THREAD

**Issue by mtdb** [django-compressor/django-compressor#273]
When get up the server I got this error

'Settings' object has no attribute 'COMPRESS_DEBUG_TOGGLE'
...
/home/.../compressor/templatetags/compress.py in render
        if self.debug_mode(context): ...
▶ Local vars
/home/.../compressor/templatetags/compress.py in debug_mode
        if settings.COMPRESS_DEBUG_TOGGLE: ...
▶ Local vars

I'm using Django 1.4 with dev version of django compressor

**Comment by marchss** [comment]
This is still an issue in Django 1.8. Even if 'compressor' is added into the INSTALLED_APPS list, the conf.py file is not imported to settings.py

**Comment by diox** [comment]
It only happens if there is something in your settings file that causes django to be loaded prematurely. Fix that, and the issue should go away.

**Comment by Tordek** [comment]
This is, like, 9 months later, but since it's been driving me nuts...

In my case the issue was related to django-celery indirectly; it's because it recommends to create a `__init__.py` file with `from .celery import app as celery_app`, which causes this whole issue.
