### ISSUE TITLE
CssAbsoluteFilter doesn't work when using runserver --insecure

### ISSUE THREAD

**Issue by bradleyayers** [django-compressor/django-compressor#278]
If I don't run `./manage.py collectstatic` first, `CssAbsoluteFilter` sees that css files aren't under `CssAbsoluteFilter.root` (they're in each app's `static/`) so it doesn't touch them.

**Comment by diox** [comment]
Hi,

This is a super old issue, but I'd be interested in knowing if you ever got to the bottom of this. `CssAbsoluteFilter` expects the files it's working with to be under `root` because it works on compressed files, that's where they should be.

**Comment by karyon** [comment]
most likely fixed in db731cf01685001cf36188c4a70c44d3eb4dcc94 for `CssAbsoluteFilter`. CssDataUriFilter is dealt with in #776.
