### ISSUE TITLE
Default the value of COMPRESS_STORAGE to STATICFILES_STORAGE

### ISSUE THREAD

**Issue by mjtamlyn** [django-compressor/django-compressor#301]
Seems a sensible default to me and fits with defaulting `COMPRESS_ROOT` and `COMPRESS_URL`

**Comment by karyon** [comment]
@diox i guess there is good reason why it defaults to CompressorFileStorage...?

**Comment by diox** [comment]
Yes, if only for the `get_available_name()` implementation (and the fact that it uses `COMPRESS_ROOT` and `COMPRESS_URL` by default) - we never want a different name from the one we chose.
