### ISSUE TITLE
Wish: A way to cache precompiler output in development

### ISSUE THREAD

**Issue by akheron** [django-compressor/django-compressor#309]
I currently have approx. 40 files per page that need precompilation. In production, I use offline cache and everything works great and fast. However in development, precompiling the 40 files takes over 10 seconds. Having to wait this long for each page to load is just too much.

As a workaround, I created wrapper scripts for the compilers (coffeescript, lessc, handlebars) that cache the compilation results in a file, using sha256(input_data + input_filename) as the filename. If the cached file is found, it's contents are returned instead of invoking the compiler. This cuts my page load times to around 3 seconds, which is far more acceptable.

I wonder if it's possible to add this functionality to django_compressor itself. I would be just fine if it compared the mtime of the cached output file to the source file and wouldn't recompile when the cached file is newer. This would only be done when DEBUG=True and COMPRESS_ENABLED=False, of course.

What do you think?

**Comment by diox** [comment]
#650 introduces a `COMPRESS_CACHEABLE_PRECOMPILERS` setting to fix this.
