### ISSUE TITLE
Spaces in filenames cause issues with precompilers

### ISSUE THREAD

**Issue by catoworld** [django-compressor/django-compressor#318]
The recommended way to set up a LESS precompiler in the documentation is as follows:

```python
COMPRESS_PRECOMPILERS = (
    ('text/coffeescript', 'coffee --compile --stdio'),
    ('text/less', 'lessc {infile} {outfile}'),
    ('text/x-sass', 'sass {infile} {outfile}'),
    ('text/x-scss', 'sass --scss {infile} {outfile}'),
    ('text/foobar', 'path.to.MyPrecompilerFilter'),
)
```

Source: http://django_compressor.readthedocs.org/en/latest/settings/#django.conf.settings.COMPRESS_PRECOMPILERS

This doesn't seem to work if the filename contains spaces. A good example is the default Aptana workspace directory:

"Aptana Studio 3 Workspace"

I was able to fix it by putting quotes around the file name:
```python
COMPRESS_PRECOMPILERS = (
   ('text/less', 'lessc "{infile}" "{outfile}"'),
)
```

However, this could be unreliable if the input file name contains special characters.

Given that the input is ultimately coming from a URL, it might be better to escape the input the way the subprocess module does it.

**Comment by karyon** [comment]
should be fixed since #536 :)
