### ISSUE TITLE
SyntaxError when combining JS files without ending semicolons

### ISSUE THREAD

**Issue by fletom** [django-compressor/django-compressor#319]
Since the files are just concatenated, if one of them doesn't have a semicolon at the end you end up with a SyntaxError. Something like this

```
... }(window.Raphael) [next file] var foo = ...
```

Many pre-compressed files (e.g. raphael-min.js) do not have semicolons at the end because they are unnecessary, the interpreter knows that the end of the file is the end of the line.

**Comment by karyon** [comment]
fixed in #813
