### ISSUE TITLE
Issue with django-storages and S3

### ISSUE THREAD

**Issue by camilonova** [django-compressor/django-compressor#328]
Hi, I'm getting this issue:

```
Error: An error occured during rendering /Users/cam../app/templates/layout/base.html: 'https://bucket-dev.s3.amazonaws.com/js/main.js?Signature=...&Expires=1351119323&AWSAccessKeyId=...' isn't accessible via COMPRESS_URL ('http://bucket-dev.s3.amazonaws.com/') and can't be compressed
```

I'm not sure how this file is not accessible since is the same STATIC_URL that works fine with COMPRESS_ENABLED = False and i did all steps documented in http://django_compressor.readthedocs.org/en/latest/remote-storages/

Thanks,

**Comment by RemyAlves** [comment]
If somebody get into the same mistake, I solved this issue thanks to @diox comment : "Note https vs http.".

Instead of having : "STATIC_URL = "http://lambda.s3.amazonaws.com/", I switched to "STATIC_URL = "httpS://lamdba.s3.amazonaws.com/""
