### ISSUE TITLE
Unable to apply ClosureCompilerFilter 

### ISSUE THREAD

**Issue by anilshanbhag** [django-compressor/django-compressor#350]
Exception Value:	
    Unable to apply ClosureCompilerFilter ({binary} {args})

Current Settings for Compressor:

	COMPRESS_ENABLED = True
	COMPRESS_OUTPUT_DIR = 'c'
	COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter', 'compressor.filters.cssmin.CSSMinFilter']
	COMPRESS_JS_FILTERS = ['compressor.filters.jsmin.JSMinFilter', 'compressor.filters.closure.ClosureCompilerFilter']
	COMPRESS_CLOSURE_COMPILER_BINARY = 'java -jar /Users/anil/virtualenvs/twiler/twiler/twiler/utils/compiler.jar'
	COMPRESS_PRECOMPILERS = (
	    ('text/coffeescript', 'coffee --compile --stdio'),
	    ('text/less', 'lessc {infile} {outfile}'),
	    ('text/x-sass', 'sass {infile} {outfile}'),
	    ('text/x-scss', 'sass --scss {infile} {outfile}'),
	    ('text/stylus', 'stylus < {infile} > {outfile}'),
	)

Exception Location:	/Users/anil/virtualenvs/twiler/lib/python2.7/site-packages/compressor/filters/base.py in input, line 133

The Popen is going wrong , any pointers as to what I am doing wrong ?

**Comment by diox** [comment]
Hi,

Apologies for the lack of response till now. I imagine you have either fixed/worked around the issue by now, or switched to different tools, but just in case you haven't or you still remember: what's the exact exception ? Does it still happen with the latest version of compressor ? Thanks.

**Comment by karyon** [comment]
not enough information and no response, closing.
