### ISSUE TITLE
sekizai postprocessor reparses the Template

### ISSUE THREAD

**Issue by aarcro** [django-compressor/django-compressor#361]
This seems to be a better solution for the sekizai postprocessor.

The data passed in has already been rendered, so no need to create a Template object. By passing it in to Template, any swig templates in javascript (or text created by {% templatetag %}) will get parsed as django template source, which is probably not intended.

    from compressor.templatetags.compress import CompressorNode
    from django.template.base import TextNode

    def compress(context, data, name):
        """
        Data is the string from the template (the list of js files in this case)
        Name is either 'js' or 'css' (the sekizai namespace)
        Basically passes the string through the {% compress 'js' %} template tag
        """
        return CompressorNode(nodelist=TextNode(data), kind=name, mode='file').render(context=context)

**Comment by blueyed** [comment]
The initial PR: #362.
My follow-up: #623.
