### ISSUE TITLE
Offline compression enabled, files generated, but still getting OfflineGenerationError 

### ISSUE THREAD

**Issue by jkeesh** [django-compressor/django-compressor#367]
I tried to deploy it with request based compression on my server, but for some reason the website just started to hang, and I didn't know where in the process to debug it. No errors were being thrown as far as I could tell. The static files were not being generated. I thought maybe it was a permissions issue but I couldn't figure it out.

I tried offline generation locally, and get the error:

You have offline compression enabled but key "c1db677edc93b7d862b6bec406845604" is     missing from offline manifest. You may need to run "python manage.py compress".

However, I run this command, and have this as the content of my manifest.json

{
  "c1db677edc93b7d862b6bec406845604": "<script type=\"text/javascript\" src=\"/static/CACHE/js/e52cf397152e.js\"></script>", 
  "a0d84548b124ffc23106ec63aac7d3cb": "<link rel=\"stylesheet\" href=\"/static/CACHE/css/dab68770dc4b.css\" type=\"text/css\" />"
}

Showing that the key "c1d...." is there. So I'm not quite sure how to proceed from this error message. From googling around it says that the best bet is I have dynamic content in the compress tag, but all I have is the {{STATIC_URL}}, which comes in the context with the default settings. 

If I run the command subsequent times, the content doesnt change, which leads me to believe I dont have any dynamic content in the tags.

I am using django-compressor==1.2, which I installed with pip.

Any tips on how to debug the OfflineGenerationError? Or What might be going wrong with the standard In-Request compression.

**Comment by Ugandharnrs** [comment]
You have offline compression enabled but key is missing from offline manifest -Fix!!
check here..
https://www.youtube.com/watch?v=P7a6PgnWL1s
