### ISSUE TITLE
COMPRESS_PRECOMPILERS doesn't accept callback filters

### ISSUE THREAD

**Issue by ForSpareParts** [django-compressor/django-compressor#369]
If I specify a class path to a CallbackOutputFilter in COMPRESS_PRECOMPILERS (allowed, according to the docs) I receive the error "bin/sh: [path.to.class]: command not found".

i.e.:

settings.py:

    COMPRESS_PRECOMPILERS = (
    ('text/some-media-type', 'main.myFilters.MyFilterClass),
    )

main/myFilters.py:

    from compressor.filters.base import CallbackOutputFilter
    
    class MyFilterClass(CallbackOutputFilter):
        etc

By examining the stack trace, it appears that compressor isn't actually checking to see whether the "command" specified in COMPRESS_PRECOMPILERS, but I could well be wrong about that. Incidentally, I discovered this while looking for a workaround for #91 / #97.

**Comment by karyon** [comment]
by now there are tests for this (the last one i implemented myself in 006ec0fcb6c4bfb8f51dd969d78174e8e14a45b0), i'm pretty sure it's working :)
