### ISSUE TITLE
Generated link/script tag: make type attribute optional (HTML5)

### ISSUE THREAD

**Issue by benebun** [django-compressor/django-compressor#395]
Are there any plans on making type="text/css" and "text/javascript" optional for the generated link/script tags? Since they are optional in HTML5 it would shave a few more bytes off.

**Comment by diox** [comment]
Apologies for getting back to you years after you submitted the issue... especially with a negative answer: there are no plans to do that at the moment. You can customize it yourself by overriding the templates compressor uses (`compressor/css_file.html`, `compressor/css_inline.html`, `compressor/js_file.html` and `compressor/js_inline.html`) in your project.
