### ISSUE TITLE
Javascript compression on zepto gives invald result

### ISSUE THREAD

**Issue by AJHMvR** [django-compressor/django-compressor#413]
When compressing something like

    {% compress js %}
    <script type="text/javascript" src="{% static "js/zepto.js" %}"></script>
    <script type="text/javascript" src="{% static "js/script.js" %}"></script>
    {% endcompress %}

using zepto v1.0-1-ga3cab6c and django-compressor 1.2, the result is invalid in chromium. Adding a semicolon a the end of the zepto js file does not change that, so this is not #319.

For the JSMinFilter, the chromium error is: Uncaught SyntaxError: Unexpected string
For the SlimItFilter, the chromium error is: Uncaught TypeError: number is not a function
Without any filters, there are no errors and the js works fine.

**Comment by karyon** [comment]
to me this sounds like non-compliant javascript that gets further messed up by the filters. besides, if the filters are causing this, the problem is probably not inside django-compressor.

**Comment by diox** [comment]
I would have liked to get to the bottom of this, but it's so old I'm just going to close and hope that it's been fixed since. I'll re-open to evaluate our options if not.

**Comment by pythdasch** [comment]
HI, I'm having this issue when I compress with yuglify.
Uncaught SyntaxError: Unexpected string

I don't understand the error. I'll create a new issue
