### ISSUE TITLE
OSError silently ignored when DEBUG=False

### ISSUE THREAD

**Issue by kylegibson** [django-compressor/django-compressor#423]
I have django-compressor configured to to use the Data URI filter that converts images less than a certain size into a data uri.

When the image path does not exist, `os.stat` throws an `OSError` ([source](https://github.com/jezdez/django_compressor/blob/develop/compressor/filters/datauri.py#L42))

When `DEBUG=False`, this exception is [silently ignored](https://github.com/jezdez/django_compressor/blob/develop/compressor/templatetags/compress.py#L114).

According to [django docs](https://docs.djangoproject.com/en/1.3/topics/testing/#other-test-conditions):

> Regardless of the value of the DEBUG setting in your configuration file, all Django tests run with DEBUG=False. This is to ensure that the observed output of your code matches what will be seen in a production setting.

I would actually prefer that errors like these not be silently ignored in production or in tests.

**Comment by karyon** [comment]
this was fixed by https://github.com/django-compressor/django-compressor/pull/657

**Comment by diox** [comment]
closing, thanks.
