### ISSUE TITLE
Files to be precompiled first served from STATIC_ROOT instead of STATICFILES_DIRS

### ISSUE THREAD

**Issue by croby** [django-compressor/django-compressor#425]
This appears to be related to #85, and this commit: https://github.com/jezdez/django_compressor/commit/02809e396bcce18f340c7f4759e065efe94122f5

After running `collectstatic`, any `.scss` files that have been included are moved to `/static` (`STATIC_ROOT`). When this happens, no edits to the `.scss` file are picked up, as the compressor finds that file first before looking at the app directory where this file exists.

If I move (in `compressor/base.py`)

```python
filename = self.finders.find(urllib.url2pathname(basename))
```

to the top of the `try/except` block, it works as I'd like it to. The commit referenced above inverted this behavior, causing the issue to manifest as I see it.

I'm completely open to the fact that I might not have my settings set up properly, and it seems as though (through my reading of the code in `get_filename` if I didn't have any storages set up, it would work properly. That doesn't seem to work for me, as serving up files seems to bomb right away. When I set a breakpoint in `get_filename`, this is what I see.

```python
(Pdb) print self.storage.path(basename)
/home/vagrant/web/static/css/default.scss

(Pdb) print compressor_file_storage.path(basename)
/home/vagrant/web/static/css/default.scss

(Pdb) print self.finders.find(urllib.url2pathname(basename))
/home/vagrant/web/src/static/css/default.scss
```

I want it to be served from the last location, but it would never have a chance to get there.

**Comment by diox** [comment]
Fixed by #658
