### ISSUE TITLE
Redis Backend

### ISSUE THREAD

**Issue by nicpottier** [django-compressor/django-compressor#431]
Not so much an issue, but a question as to whether this sounds like a sane approach.

Our prod environment is multiple web boxes behind a load balancer, a redis instance and a db instance.

We make heavy use of django-compressor (thanks!) to compile coffeescript, combine files etc.. (we also use hamlpy which is another issue entirely).

My first inclination was to use offline compression, but there's an issue with hamlpy that is preventing that from working without forking the compress management command. (referenced here: #417)  Honestly that's not the root of it though since that would be easy enough to do.  Though for some reason my looks are failing even after hacking that, so I need to look around some more.

Anyways, while pondering other options I started to wonder why Redis isn't a commonly used backend. If nobody is doing that I'm guessing there must be a reason but I'd love to know what it is.  Seems like it would be plenty fast and in typical cases we are talking about only a few MBs of css and javascript at most, so having things be in memory on the Redis side sounds just fine.

Is there a reason going back to not using offline compression but using a Redis instance for the backend wouldn't work well?  Happy to do that work myself and contribute it, but if someone can save me the time and point out my folly that'd be great.

PS. Didn't see a mailing, but if there is a more appropriate place for such discussions, please point me there.

**Comment by karyon** [comment]
not a bug and i guess the help isn't needed anymore...
