### ISSUE TITLE
django compressor raises exception with external files

### ISSUE THREAD

**Issue by malik-vxt** [django-compressor/django-compressor#440]
hi,

first thank you for this good piece of code.
My issue is that django compressor always raises exceptions with external files like 

[code]
{% block bottom_js %}
  {% compress% }
    [script_tag] type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.18/jquery-ui.min.js">[/script_tag]
   {%endcompress %}
{% endblock %}
[/code]

However the doc states that these files should just be ignored https://django_compressor.readthedocs.org/en/1.3/usage/#examples

with local(on site) files everything is ok.

thanks

**Comment by helderco** [comment]
But why not? Sometimes it's out of our control.

I'm using Django CMS, and the Google Maps plugin is adding with sekizai an external reference to google's js. This means I can't use django compressor with sekizai even though it's supported.

Seems to me it would be simple enough to instead of stripping external references, **just delay them to the end**. So if you have (addtoblock in different template files):

```
{% addtoblock "js" %}<script src="{% static "libs/jquery/dist/jquery.min.js" %}"></script>{% endaddtoblock %}
{% addtoblock "js" %}<script src="https://maps-api-ssl.google.com/maps/api/js..."></script>{% endaddtoblock %}
{% addtoblock "js" %}<script src="{% static "libs/some-other-plugin.min.js" %}"></script>{% endaddtoblock %}

{% render_block "js" postprocessor "compressor.contrib.sekizai.compress" %}
```

It would then be rendered as

```
<script type="text/javascript" src="/static/CACHE/js/b3583c9a3647.js"></script>
<script type="text/javascript" src="https://maps-api-ssl.google.com/maps/api/js..."></script>
```

Isn't this possible to implement?

**Comment by carltongibson** [comment]
> ...just delay them to the end.

Isn't this going to introduce ordering problems? (Often/Normally it matters that the scripts end up in the order specified.) 

Short of a PR solving this I'd be inclined to think it's not in scope — just for simple reasons of capacity. 

Edit the plugin to not include the external dependency and inject that outside the `compress` tag yourself.  Not ideal I grant you, but simple enough I'd hope.

**Comment by theangular** [comment]
https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api ?

**Comment by theangular** [comment]
look over this answer https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
QUOTE_REPLY



https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
Look this way for the answer



https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
QUOTE_REPLY



https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api Look at this noteworthy response

**Comment by theangular** [comment]
I found the solution https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
See this https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api response

**Comment by theangular** [comment]
I got the response https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
I came to the answer https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
I had the same concern and worked out an answer https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
Here’s an interesting note https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api

**Comment by theangular** [comment]
Check this https://jquerys.space/questions/is-it-necessary-to-have-the-jquery-ui-key-in-order-to-utilize-the-google-ajax-api clarification
