### ISSUE TITLE
precompiler subprocess exception

### ISSUE THREAD

**Issue by dulaccc** [django-compressor/django-compressor#442]
While deploying on Heroku I get an `AttributeError` exception with the message `'module' object has no attribute 'poll'`.

I've been able to track it down to [`compressor/filters/base.py:120`](https://github.com/jezdez/django_compressor/blob/master/compressor/filters/base.py#L120) then it raise the exception on the python `subprocess` module.

Any guess why the subprocess might not work on Heroku ?

**Comment by karyon** [comment]
very old issue, and very limited information. i just tried and couldn't find out which line exactly was meant.
