### ISSUE TITLE
Unable to handle "for loop"

### ISSUE THREAD

**Issue by lucastan** [django-compressor/django-compressor#487]
When I add a "for" loop to test_with_context, the test case fails. The reason is that the rendered HTML using normal Django templating engine vs the patched engine in compress() are different. The "for" loop in the patched version somehow does not execute 3 times as expected.

```
{% load compress %}{% spaceless %}

{% compress js %}
  {% for g in content %}
    <script type="text/javascript">
        alert("{{ content|default:"Ooops!" }}");
    </script>
  {% endfor %}
{% endcompress %}{% endspaceless %}
```

**Comment by diox** [comment]
Super old issue I know, but did you ever find out what the problem was ? Do you know if you were correctly setting the context for offline compression in the test settings ? (your loop depends on a `content` variable).

**Comment by lucastan** [comment]
This is really old. I have forgotten what the exact cause is. 
Is 'for' loop supported?

**Comment by diox** [comment]
It should be, yes, as any other template bits.

I built a test locally with this template:

```
{% load compress %}{% spaceless %}

{% compress js %}
  {% for g in content %}
    <script type="text/javascript">
        alert("{{ g|default:"Ooops!" }}");
    </script>
  {% endfor %}
{% endcompress %}{% endspaceless %}
```

And this python code:
```
class OfflineCompressTestCaseWithForLoop(OfflineTestCaseMixin, TestCase):
    templates_dir = 'test_with_forloop'
    expected_hash = '1c723505cd43'
    additional_test_settings = {
        'COMPRESS_OFFLINE_CONTEXT': {
            'content': [1, 2, 3]
        }
    }
    engines = ('django',)
```

And it passed, the generated content was `alert("1");alert("2");alert("3");` as expected.
