### ISSUE TITLE
How to configure COMPRESS_PRECOMPILERS with rvm-based sass installation?

### ISSUE THREAD

**Issue by stefanocrosta** [django-compressor/django-compressor#490]
Hello!

Any hint on how to use django-compressor with sass/scss installed through rvm ?

I tried specifying the exact path to the local sass in the `COMPRESS_PRECOMPILERS`, I tried setting `os.environ['GEM_HOME']` but i keep getting all errors as if, of course, trying to use the system ruby/gems.

In particular I get stuck at: `/usr/bin/env: ruby_executable_hooks: No such file or directory`

Thanks!

**Comment by devjon** [comment]
@stefanocrosta : Any solution to this?

**Comment by stefanocrosta** [comment]
sorry @devjon , I completed that project for a customer more than a year ago and I really don't remember how (if ever) I went around this issue... it was definitely something related to environment variables..

**Comment by carltongibson** [comment]
This isn't a compressor issue really. (@diox can we close?)

StackOverflow offers this if you try looking for you error message: http://stackoverflow.com/questions/19661147/usr-bin-env-ruby-executable-hooks-no-such-file-or-directory

**Comment by karyon** [comment]
@diox, what @carltongibson said.
