### ISSUE TITLE
Is there any way to skip a file in a compress block?

### ISSUE THREAD

**Issue by arctelix** [django-compressor/django-compressor#513]
During development if you have many js/css files page load times can be very slow.  It would be great if you could enable compression and skip files that you are working on.  For example:

    {% compress js %}
        <script language="javascript"><script language="javascript" src="src1"></script>
        <script language="javascript"><script language="javascript" src="src2"></script>
        {% compress_exclude %}<script language="javascript"><script language="javascript" src="scr3"></script> {% endcompress_exclude %}
        <script language="javascript"><script language="javascript" src="src4"></script>
        <script language="javascript"><script language="javascript" src="src5"></script>
    {% endcompress %}

this would result in 3 js files:
- src1&scr2 as compressedA
- src3 (uncompressed)
- src4&scr5 as compressedB

Is there currently any way to do this? If not it would be really useful!

**Comment by karyon** [comment]
why not use two compress blocks?
```
{% compress js %}
    <script language="javascript"><script language="javascript" src="src1"></script>
    <script language="javascript"><script language="javascript" src="src2"></script>
{% endcompress %}
<script language="javascript"><script language="javascript" src="scr3"></script>
{% compress js %}
    <script language="javascript"><script language="javascript" src="src4"></script>
    <script language="javascript"><script language="javascript" src="src5"></script>
{% endcompress %}
```

**Comment by diox** [comment]
Agreed.

**Comment by arctelix** [comment]
This is what i currently do. However, with multiple js dependancies and many js files i end up with many compress blocks which have to be removed each time i push an update to the production server. 

My proposed {% compress_exclude %} tag would be ignored when debug is set to false.  Making your dev and production set up dynamic.  Perapse {% compress_debug %} would be clearer..

**Comment by karyon** [comment]
you lost me there, why do you need to remove these blocks each time you update production? and what is the actual reason you want to exclude some files, what exactly is slow? because as far as i know, compressor should do about nothing when it is disabled, exept for precompilers, which are not the problem here afaics.

**Comment by arctelix** [comment]
Lets say you have 20 .js files and 10 of those are part of your development & 10 are std libraries.

During dev the more .js files that the browser has to load slows down page load times.  With that being said i have compression enabled in my dev environment regardless of the debug var state .  Reduces 20 files to one = fast page laod.  I use an environment var to determine dev vs production.  Not debug.

If you are debugging  2 of these files simply add my proposed exclude_debug tag and those two files will be compressed when debug===True and uncompressed when debug===False even when compression is enabled.

I hope that clarifies...

Sent from my iPhone

On Sep 25, 2015, at 2:11 PM, karyon <notifications@github.com<mailto:notifications@github.com>> wrote:


you lost me there, why do you need to remove these blocks each time you update production? and what is the actual reason you want to exclude some files, what exactly is slow? because as far as i know, compressor should do about nothing when it is disabled, exept for precompilers, which are not the problem here afaics.

**Comment by arctelix** [comment]
Also its not that the compress tags have to be removed.  I need to add the uncompessed files back into the compress block when i push to production.

**Comment by diox** [comment]
Sorry, this is too much of an edge case to have in compressor itself. If you truly care about this you can inherit from the compress template tag and do it yourself.

**Comment by arctelix** [comment]
Understood.  Im just surprised nobody else uses compression when debugging to decrease page load times.  

Out of curiosity.  How do you deal with this issue when working with a large quantity of files.  Maybe my strategy is overly complex?

**Comment by diox** [comment]
I generally deal with the load times on my local machine. Even loading 20 js files locally is not that bad IMHO. Compressing would not necessarily be faster, because it still has to parse the HTML (unless you are using offline compression, but I usually don't want that for debugging, it's too easy to forget to re-run the command)

**Comment by arctelix** [comment]
Thanks for your input. I must have some strange issue with chrome on a very large project.  This project (all files hosted on local machine) takes about 5-15 seconds longer to load uncompressed.  One uncompressed file (2 total files) has a negligible difference.  It drives me crazy, and compression was the best solution i found.

Sent from my iPhone

On Sep 25, 2015, at 4:13 PM, Mathieu Pillard <notifications@github.com<mailto:notifications@github.com>> wrote:


I generally deal with the load times on my local machine. Even loading 20 js files locally is not that bad IMHO. Compressing would not necessarily be faster, because it still has to parse the HTML (unless you are using offline compression, but I usually don't want that for debugging, it's too easy to forget to re-run the command)
