### ISSUE TITLE
Not able to use django-compressor on a productive website with alot of traffic

### ISSUE THREAD

**Issue by Morpho** [django-compressor/django-compressor#529]
I have a staging and a productive webserver with the exact same configuration. On the staging server everything is fine when updating css or js files, but whenever I update a css or js file on the production server, the whole python/django process just freezes and cpu/load goes to 100%. Also django-compressor doesnt create new compressed files. It seems like the threads are blocking each other, as on the production server there are many requests every second. So this seems to be some kind of race condition. Do you have any idea how to fix that?

Here is my config:
- Django 1.5.4 running on uwsgi (same problem with gunicorn)
- django-compressor 1.3 (from pypi)
- django-compressor relevant settings:

```
PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..'))
CACHES = {
    'default': {
        'BACKEND': 'redis_cache.cache.RedisCache',
        'LOCATION': 'localhost:6379:25',
        'OPTIONS': {
            'PARSER_CLASS': 'redis.connection.HiredisParser'
        },
    },
}
MEDIA_ROOT = os.path.join(PROJECT_ROOT, 'media')
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(PROJECT_ROOT, 'static')
STATICFILES_DIRS = (
    os.path.join(PROJECT_ROOT, 'site-static'),
)
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
COMPRESS_ENABLED = True
COMPRESS_CSS_FILTERS = (
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',
)
```

base.html Template:

```
{% compress css %}
  <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css">
  ...
  <link rel="stylesheet" href="{{ STATIC_URL }}css/styles.css">
  <link rel="stylesheet" href="{{ STATIC_URL }}css/font-awesome.css">
{% endcompress %}
```

Any help is very appreciated! Thanks!

**Comment by kennydust** [comment]
hi diox,
having this same issue, looking for the local manifest, but dont see it. where should this file be located by default?
