### ISSUE TITLE
TypeError Exception using TemplateFilter as Precompiler

### ISSUE THREAD

**Issue by thenewguy** [django-compressor/django-compressor#533]
```
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'sass --scss {infile} {outfile}'),
    ('text/django', 'compressor.filters.template.TemplateFilter'),
)
```
```
{% compress css %}
	<link rel="stylesheet" href="foo.css" />
	<link type="text/django" rel="stylesheet" href="bar.css.djt" />
{% endcompress %}
```
Raises a TypeError:
```
Exception Type:	TypeError
Exception Value:	
__init__() got multiple values for keyword argument 'filter_type'
```

According to the traceback, it seems that an "attrs" variable is passed to the filter.  However, compressor.filters.base.FilterBase does not accept the attrs positional argument.  See https://github.com/django-compressor/django-compressor/blob/develop/compressor/filters/base.py#L27 and https://github.com/django-compressor/django-compressor/blob/develop/compressor/base.py#L262

I think this is causing the issue.

**Comment by rotherfuchs** [comment]
+1
