### ISSUE TITLE
Not testable in a project

### ISSUE THREAD

**Issue by melvyn-sopacua** [django-compressor/django-compressor#534]
The current test suite isn't runnable from within a project as `./manage.py test compressor`. While I appreciate being able to test the code in a virtualenv, I also would like to test if the code behaves with my project settings and other applications.
Some tests do complete after defining some variables, most notably TEST_DIR, so perhaps the test suite can be setup a bit differently so that it can run as is now and that some tests are skipped that rely on specific scenario's that can only run if test_settings.py is the current DJANGO_SETTINGS_MODULE.

**Comment by diox** [comment]
Sorry, this is unlikely to be changed for a long time. If you want to test how compressor behaves in your project with your own settings, you'll have to write your own set of tests.
