### ISSUE TITLE
CSSMinFilter should not remove spaces from inside calc() expression

### ISSUE THREAD

**Issue by derek73** [django-compressor/django-compressor#541]
CSSMinFilter removes the space from inside of `calc()` expressions, making them invalid.

`calc(100% + 20px)` becomes `calc(100%+20px)`, which is invalid. The spaces are required.

https://developer.mozilla.org/en-US/docs/Web/CSS/calc

"Note: The + and - operators must always be surrounded by whitespace"

**Comment by heres** [comment]
+1

**Comment by kayluhb** [comment]
+1

**Comment by brmc** [comment]
Here ya go.  I hope this helps
@derek73 @heres @kayluhb

**Comment by chriddyp** [comment]
thanks for the fix @brmc ! is this fix going to get merged into the official version and version bumped on pip?

**Comment by diox** [comment]
2.0 has the fix (not this one in particular, instead we changed the dependencies).
