### ISSUE TITLE
Race condition with COMPRESS_MTIME_DELAY > 0 and multiple servers sharing the same cache

### ISSUE THREAD

**Issue by kylegibson** [django-compressor/django-compressor#550]
It seems it is possible for an updated mtime based cache key to have old content. This requires you have `COMPRESS_MTIME_DELAY` > 0.

If I am correct, I believe the issue occurs between lines 102 and 110 in `compressor.templatetags.compress`:

```python
        # Prepare the actual compressor and check cache
        cache_key, cache_content = self.render_cached(compressor, kind, mode, forced=forced)
        if cache_content is not None:
            return cache_content

        # call compressor output method and handle exceptions
        try:
            rendered_output = self.render_output(compressor, mode, forced=forced)
            if cache_key:
                cache_set(cache_key, rendered_output)
            assert isinstance(rendered_output, six.string_types)
            return rendered_output
        except Exception:
            if settings.DEBUG or forced:
                raise
```

The problem occurs given the following criteria:

* Multiple servers sharing the same cache backend
* An updated media file with the old version on one server, and the new version on another server
* The media file path must be the same between the two servers

Scenario: A request hits the new server (the mtime for the path is cached), and then before the new server is able to generate the compressed media and set the cache, another request hits the old server before `COMPRESS_MTIME_DELAY`. In this case, it gets the cached mtime (which is invalid for the file) and proceeds to generate the compressed media. This will overwrite the cache set by the request on the server with the new content. Until the mtime of all of the files changes, the old version will continue to be used.

Some work-arounds for this issue:

* Move media compression to deploy, not the request response cycle
* After the deploy is finished, `touch` all of the media files that changed

**Comment by diox** [comment]
As mentioned in #560, with multiple servers you probably want to use offline compression instead.
