### ISSUE TITLE
'utf8' codec can't decode byte 0xbf in position 393: invalid start byte on css and js compression with Yui

### ISSUE THREAD

**Issue by fedetorre** [django-compressor/django-compressor#552]
Hi,
I have configured django-compressor with jinja2 enviroment for compressing js and css files with Yui compressor but the application give me this error during compressing operation.

CommandError: An error occured during rendering <file name>: 'utf8' codec can't decode byte 0xbf in position 393: invalid start byte

If I use CSSMinFilter and JSMinFilter the compression works fine.
Any help appreciated!

Thank you,
best regards

Federico

**Comment by lucastan** [comment]
sounds like an UTF8 encoding error. mind if you post the relevant part here?

**Comment by diox** [comment]
No reply in a year, closing.
