### ISSUE TITLE
Suspicious Operation: Access denied.

### ISSUE THREAD

**Issue by waqasjaved160** [django-compressor/django-compressor#553]
On my local machine compress tags are working fine but on dev machine it throws me an error of Suspicious Operation : Access denied on "js/abc.js".

Following are my settings:

MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(os.path.dirname(__file__), 'static')
STATIC_URL = '/static/'

**Comment by WoLpH** [comment]
Be careful with double slashes, in my case I had something like this:

```
<script type="text/javascript" src="{{ STATIC_URL }}/some_javascript_file.js"></script>
```

That does not work... you really need this instead:
```
<script type="text/javascript" src="{{ STATIC_URL }}some_javascript_file.js"></script>
```
Imho this is a bug as the file `/foo//bar/` should be the same as `/foo/bar/` but that's a different issue.

**Comment by tezro** [comment]
Use this:
```
{% static "some_javascript_file.j" %}
```

**Comment by WoLpH** [comment]
That doesn't change the fact that a slash in front of the url breaks the system, the result is the same.

**Comment by carltongibson** [comment]
I'm going to close this: it's not an addressable issue for Django Compressor.
