### ISSUE TITLE
CommandError: An error occured during rendering /home/youngershen/dev/company_project/hiveall_project/hiveall_new/hiveall/templates/html/base.html: compressor/css_file.html

### ISSUE THREAD

**Issue by youngershen** [django-compressor/django-compressor#557]
have no idea about what happened , do not understand what the message mean, how about css_file.html page working?  I use the same settings in a blank djangp project works well , I use coffin for jinja2 support  , I really need some help. thanks

**Comment by diox** [comment]
Hi,

Sorry your issue didn't receive any attention till now. I know it's one year later, but are you still experiencing it ? I would need more info to investigate, like the template, the settings etc.

**Comment by STurner97** [comment]
I know this thread is 10 years old but I was hoping someone had a solution to this?

As far as I can tell, my `settings.py` is set up correctly and I can verify using the `manage.py shell` [that sass is installed and able to be used](https://github.com/torchbox/django-libsass/wiki/Troubleshooting#3-test-python-libsass-in-isolation).

base.html
```html
<head>
    {% compress css %}
    <link rel="stylesheet" type="text/x-scss" href="{% static "css/styles.scss" %}" />
    {% endcompress %}
</head>
```

When I run `python manage.py compress` I get this error
> CommandError: An error occurred during rendering base.html: compressor/css_file.html

Here are my settings
```python

INSTALLED_APPS = [
    'compressor',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'integrations',
    'dashboard',
]

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]


# Sass Compiler settings. Packages: django-compressor django-libsass
# TODO: add documentation link

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)
COMPRESS_OFFLINE = True
COMPRESS_ENABLED = True
# LIBSASS_OUTPUT_STYLE = 'compressed'
```
