### ISSUE TITLE
Slow just in time compression

### ISSUE THREAD

**Issue by RRMoelker** [django-compressor/django-compressor#566]
Compressor is a great tool, but there is the problem of it being a resource hog. Not using offline compression and having around 10 css files my sites load 2 seconds slower (some even 5 seconds). The cause seems to be compressor statting each file for changes, having massive IO interrupts.

Now I know offline compression is a way to solve this, but for local development I want instant compression without having to use offline compression. There are several simmilar issues:

* https://github.com/django-compressor/django-compressor/issues/364
* https://github.com/django-compressor/django-compressor/issues/18

But they have been closed. I feel this is a serious issue and want to help to resolve this. My idea would be to first group IO operations together and make them async if possible. I'm currious if anyone has any better ideas before I try something. For example can directories be checked for changes rather than individual files first?

**Comment by diox** [comment]
#650 added a way to cache precompilers. That should be enough for your issue.
