### ISSUE TITLE
Compressor not compiling scss files

### ISSUE THREAD

**Issue by felipellrocha** [django-compressor/django-compressor#573]
Hey guys. I'm running into a weird issue.
Compressor is not compiling my scss files, for some reason, on production only. I checked the uwsgi logs, but I get no errors there.

This is my source:
```django
{% block header %}
{% compress css %}
<link rel="stylesheet" href="/static/css/base.scss" type="text/scss" charset="utf-8" />
{% endcompress %}
{% endblock %}
```

This is what I'm getting in the browser:
```html
<link rel="stylesheet" href="/static/css/base.scss" type="text/scss" charset="utf-8" />
```

Instead of the usual:
```html
<link rel="stylesheet" href="/static/CACHE/css/ee319c2872c5.css" type="text/css" />
```

Any help? I've been hunting this issue for a while now with no progress...

**Comment by melinath** [comment]
Just ran into this as well, with `text/sass`.

**Comment by carltongibson** [comment]
Hmmm. Curious. As it stands all I can say is that this _should_ be working. 

With these example settings, and the `sass` command on the `PATH` compressor is passing the file to Sass as expected: 
 
```
SASS_COMMAND = 'sass --scss {infile} {outfile}'
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', SASS_COMMAND),
)
```

Everything still works altering the Mime type in the HTML and `COMPRESS_PRECOMPILERS` setting to `text/scss`. 

There must be something else going on. Is it possible to reduce this to a minimal reproduce case which shows the issue? Without that there's not much that can be done. 

@diox — This isn't really actionable as it stands. Can we close? If a reproduce turns up we can re-open then.

**Comment by felipellrocha** [comment]
Sorry for not having replied earlier. This turned out to be a permission issue on my side. Totally unrelated to compressor!

**Comment by diegoponciano** [comment]
@felipellrocha looks like I'm facing the same issue, it works on my devbox but on the production server it won't precompile the ```scss``` stlyesheet.
What was the permission issue you were seeing? And how did you fix it?
Thanks

**Comment by felipellrocha** [comment]
@diegoponciano If I remember correctly, I had originally setup uwsgi to run my django app as root by accident. Compressor then created all the caching folders. I noticed that, and I fixed it, but by then the folders were already owned by root:root. It was just changing the owner of the folders and files and it started to work again!

**Comment by karyon** [comment]
@diox doesn't seem to be an issue of django-compressor
