### ISSUE TITLE
CssDataUriFilter with DEBUG=False makes COMPRESS_PRECOMPILERS to be skipped

### ISSUE THREAD

**Issue by oblalex** [django-compressor/django-compressor#578]
I don't know how, but if you include `CssDataUriFilter` to `COMPRESS_CSS_FILTERS` and set `DEBUG=False` (or `COMPRESS_ENABLED=True`), then compressor will skip `COMPRESS_PRECOMPILERS`.

Got it with Django 1.4.16 and SCSS:

```
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'sass --scss {infile} {outfile}'),
)
```

**Comment by karyon** [comment]
just tested this and could not reproduce. given that this issue is two years old, let's assume it has fixed itself :) if anyone still experiences this, we can re-open it of course.
