### ISSUE TITLE
Compressor class refactoring

### ISSUE THREAD

**Issue by GermanoGuerrini** [django-compressor/django-compressor#587]
The provided `Compressor` subclasses (`JsCompressor` and `CssCompressor`) share a *very* similar `output` method. I'm not even sure that the parent method is called anymore outside the test suite.
I was thinking to replace the current implementation with one from one of the subclasses, but I should even remove the tests for the base class.
Before proceeding I thought to ask, as I don't know if it's been already scheduled by someone else.

**Comment by diox** [comment]
If you are still interested in doing that, feel free to submit a pull request. Thanks.
