### ISSUE TITLE
Management command broken with 1.8

### ISSUE THREAD

**Issue by carltongibson** [django-compressor/django-compressor#588]
```
  File "/Users/carlton/ve/notwatch/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 56, in get_loaders
    from django.template.loader import template_source_loaders
ImportError: cannot import name template_source_loaders
```

On the fly still works but offline is failing. 

Still stepping through the new 1.8 template code to be able to say more.

**Comment by a1tus** [comment]
Ran into this issue too. I've dealt with changes in template loaders (so that `compress` command loop through all th templates) but stopped on `handle_extendsnode` function which I couldn't get to work.
I've changed it to `return []` and it successfully found compress tags in base templates but its still not usable coz appropriate cache keys for extended templates does not exist.

**Comment by diox** [comment]
Yeah, that's not surprising given the changes around template loading in 1.8.

Sadly, there is almost no one actively working on this (or compressor itself) right now. I'll accept pull requests fixing this, but it's not trivial.

**Comment by carltongibson** [comment]
@diox — I'm happy to help maintain here. I submitted #599 to get the build passing again.

**Comment by carltongibson** [comment]
Hmmm. I added 1.8 to tox. Executive Summary: Didn't go well. 

1. A lot of tests depend on offline compression — so need a fix here.
2. There were import errors for jingo — I wasn't able to (see how to) quickly skip this. 
3. At first glance inexplicably, a small change in one test case led to a whole load of `OfflineGenerationErrors` elsewhere (perhaps related to #579)
4. Are the `expected_hash = "a27e1d3a619a"` type values all derived by hand? 
5. All of that meant it's not easy to see where to begin even. 

I'll have a pop at the `compress` command this week.

**Comment by diox** [comment]
Regarding 4, yes - if you get different results, you should check the resulting compressed contents to see what looks suspicious.

**Comment by carltongibson** [comment]
Again, "Hmmm". :) 

I've stepped through trying to implement the [`compress` command](https://github.com/django-compressor/django-compressor/blob/develop/compressor/management/commands/compress.py#L107) with 1.8. The template loading section is simple enough (and much nicer than the existing method.) 

Like @a1tus when it gets into [compressor.offline.django.DjangoParser.walk_nodes](https://github.com/django-compressor/django-compressor/blob/develop/compressor/offline/django.py#L137) I'm currently unsure how to proceed. There's a good bit of rooting around in django.template.base to work out how to map what there to what we need. 

@aaugustin Would it be at all possible for you to look at the `walk_nodes` function linked and perhaps indicate how a 1.8 version might run? I'd be very grateful if you could! (Thank you.)

If we can get the node list then the rest of the command should run through smoothly enough (he says): the DTL `Node` and `NodeList` classes provides a `render` which will either Just Work™ or shouldn't provide too much trouble (he says)

**Comment by aaugustin** [comment]
At line 98, on Django 1.8, replace `return get_template(template_name)` by `return get_template(template_name).template`.

`get_template` returns a wrapper around the `django.template.Tempalte`. Accessing the `template` attribute extracts the underlying template.

**Comment by carltongibson** [comment]
Brilliant. Thank you! I'll give that a run shortly. 👍
