### ISSUE TITLE
Release new version to pypi

### ISSUE THREAD

**Issue by sephii** [django-compressor/django-compressor#595]
The latest release (1.4) has been released in May 2014, that's almost 1 year from now. There have been numerous fixes since then so a new version should be released.

**Comment by diox** [comment]
Yeah, we should work on that.

The plan is to:
- Merge #601 
- Merge #525 (I need someone to have a look at it, bonus points if we can figure out a way to unit test this easily)
- Update docs / release notes (check authors file too)
- Test things locally quickly
- Make the release

**Comment by carltongibson** [comment]
#571 Looks like it might not be far off.

**Comment by diox** [comment]
Added to the plan (which I also updated, todo-list style)

**Comment by rotherfuchs** [comment]
#593 would be splendid, too !

**Comment by diox** [comment]
Since we have a very limited amount of manpower here, we're only considering pull requests for this release. So unless someone comes up with a pull request that includes tests and is easy to review, this will have to wait, sorry.

**Comment by carltongibson** [comment]
I'll have a look over the docs today/tomorrow.

**Comment by diox** [comment]
#607 was merged, so we're almost there. I'll update the AUTHORS file and test things locally.

**Comment by carltongibson** [comment]
Hey @diox — Sorry for the silence; I've been _otherwise engaged_. I need to push a release for Django Filter (which too needs some 1.8 love) but is there anything I can do to help wrap this one up?

**Comment by diox** [comment]
Hey - thanks for your work, I forgot to close this, but I released 1.5 earlier this week!

**Comment by carltongibson** [comment]
Ha! OK, I really have been absent. Well done. Awesome.

**Comment by sephii** [comment]
Awesome, thanks a lot!
