### ISSUE TITLE
Handle IE's selector limit

### ISSUE THREAD

**Issue by jproffitt** [django-compressor/django-compressor#598]
IE (up to version 9) has an interesting limit on the number of css selectors it can read in a single style sheet. It will read 4095 selectors only, then ignore the rest. (http://blogs.msdn.com/b/ieinternals/archive/2011/05/14/10164546.aspx) 

To fix it, you need to break out your stylesheet into separate files. That is a little difficult when you use django-compressor, because it sticks everything into one file.

It would be nice if django-compressor could determine if there are two many selectors, and automatically break it out into multiple files for you. There are some tools that already do that, like http://blesscss.com. Maybe that could be integrated with compressor somehow.

**Comment by DylannCordel** [comment]
:+1:

**Comment by diox** [comment]
This is a good idea in theory, but in practice I think it'd make things quite messy. I'll look at a pull request that does that if someone writes one, but closing this issue in the meantime as it's unlikely to be implemented otherwise.
