### ISSUE TITLE
testsuite status for version -1.4 with latest django

### ISSUE THREAD

**Issue by idella** [django-compressor/django-compressor#603]
Running full testsuite with no tests excluded under py2.7;

----------------------------------------------------------------------
Ran 243 tests in 1.926s

FAILED (errors=45, skipped=1)
Creating test database for alias 'default'...
Destroying test database for alias 'default'...

Running full testsuite with no tests excluded under py3.3;

Ran 180 tests in 1.796s

FAILED (errors=29, skipped=2)
Creating test database for alias 'default'...
Destroying test database for alias 'default'...

Installed version of django :  1.7.6
Please fix the testsuite.  
For a build log see
https://bugs.gentoo.org/show_bug.cgi?id=541696

**Comment by diox** [comment]
Thanks, this is fixed on the `develop` branch so we simply need to make that new release. Closing in favor of #595.
