### ISSUE TITLE
RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9

### ISSUE THREAD

**Issue by ellipticaldoor** [django-compressor/django-compressor#608]
I recently updated to Django 1.8 and when I run the server this warning appears:

```
/Users/miguel/.virtualenvs/dfiid/lib/python3.4/importlib/_bootstrap.py:321: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  return f(*args, **kwds)
```

When I don't load django-compressor I'm not getting this message so I think it's probably because this project is using django.utils.importlib

**Comment by epicserve** [comment]
Using the following should give you a traceback:

```
$ python -W "error:django.utils.importlib:DeprecationWarning" manage.py runserver
```

**Comment by ellipticaldoor** [comment]
Thanks! I think the problem is the import the line 11 in the file /site-packages/compressor/cache.py

How I can fix this?

```
File "/Users/miguel/.virtualenvs/dfiid/lib/python3.4/importlib/__init__.py" in import_module
  109.     return _bootstrap._gcd_import(name[level:], package, level)
File "/Users/miguel/.virtualenvs/dfiid/lib/python3.4/site-packages/compressor/templatetags/compress.py" in <module>
  5. from compressor.cache import (cache_get, cache_set, get_offline_hexdigest,
File "/Users/miguel/.virtualenvs/dfiid/lib/python3.4/site-packages/compressor/cache.py" in <module>
  11. from django.utils.importlib import import_module
File "/Users/miguel/.virtualenvs/dfiid/lib/python3.4/site-packages/django/utils/importlib.py" in <module>
  9.     RemovedInDjango19Warning, stacklevel=2)

Exception Type: RemovedInDjango19Warning at /
Exception Value: django.utils.importlib will be removed in Django 1.9.
```

**Comment by epicserve** [comment]
I upgraded to Django-appconf 1.0.1, so maybe the fix is just to update the setup.py requirements to this version.

**Comment by epicserve** [comment]
I found some more deprecation warnings, but installing from https://github.com/django-compressor/django-compressor/archive/develop.zip, seemed to resolve the rest of the issues. Hopefully, this will be made into a release soon.

**Comment by ellipticaldoor** [comment]
Cool! Thanks

**Comment by epicserve** [comment]
@ellipticaldoor You wouldn't happen to know when this will be made into a release?

**Comment by dbrgn** [comment]
@epicserve see #595

**Comment by ellipticaldoor** [comment]
I shouldn't close this issue? I'm new with github and all of this.
