### ISSUE TITLE
test fails for python2.7 - FAIL: test_js_output (compressor.tests.test_base.JsAsyncDeferTestCase)

### ISSUE THREAD

**Issue by jlec** [django-compressor/django-compressor#616]
FAIL: test_js_output (compressor.tests.test_base.JsAsyncDeferTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/tmpfs/django-compressor/compressor/tests/test_base.py", line 316, in test_js_output
    self.assertEqual(output, attrs)
AssertionError: Lists differ: [None, u'async', u'defer', Non... != [None, None, '', None, None, N...

First differing element 1:
async
None

- [None, u'async', u'defer', None, u'async', None]
+ [None, None, '', None, None, None]

----------------------------------------------------------------------

**Comment by karyon** [comment]
this happens when trying to run tests with python 2.x and beautifulsoup 4.x in the current test setup. should get fixed with #663
