### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by zakuro9715** [django-compressor/django-compressor#619]
I want to django-compressor to work with TypeScript

I tried to use tsc(TypeScript compiler) with django-compressor this way:

```
COMPRESS_PRECOMPILED = ('text/typescript', 'tsc --out {outfile} {infile}')
```

But error occurred like this:

```
error TS6053: File '/tmp/tmpxxt3rmzl.ts' not found.
```

Then I found that tsc allow a '.ts' extension only.
By default, infile has no extension.

I want to create a pull-request for supporting TypeScript
Is it possible that you will merge it?

--

I am still learning English. Does it make sense?

**Comment by carltongibson** [comment]
Just out of interest, does this work?

    COMPRESS_PRECOMPILED = ('text/typescript', 'tsc --out {outfile} {infile}.ts')

**Comment by zakuro9715** [comment]
@carltongibson 

It does't work.

If input file has not extension, tsc appends '.ts' to end of filename.
So, this two commands are equal.

```
tsc --out foo bar
```

```
tsc --out foo bar.ts
```

**Comment by carltongibson** [comment]
OK, I see. 

My first thought is that you could write a very simple wrapper that took `infile` and made a copy with the required extension before passing that off to `tsc`. That might be better than a special case inside the compressor code itself...

**Comment by zakuro9715** [comment]
Do you mean this way?

```
COMPRESS_PRECOMPILED = ('text/typescript', 'cp {infile} {infile}.ts & tsc --out {outfile} {infile} & rm {infile}.ts')
```

**Comment by carltongibson** [comment]
That wasn't exactly what I had in mind, I thought a whole wrapper script, but that could work... Does it?

**Comment by zakuro9715** [comment]
OK.

You mean this way right?

```
COMPRESS_PRECOMPILED = ('text/typescript', 'my-tsc {infile} {outfile}')
```

and my-tsc is:

```sh
#!/bin/sh

cp $1 $1.ts
tsc $1 --out $2
rm $1.ts
```

I tried it and It works!
Thank you.

**Comment by carltongibson** [comment]
Awesome!

@diox please close

**Comment by VadymRud** [comment]
`'text/typescript', 'tsc {infile} --out {outfile}'),`

**Comment by rigobertomolina** [comment]
Have you tested this? @VadymRud

**Comment by lukeaus** [comment]
I couldn't get @VadymRud method to work using typescript 2.0.10

**Comment by karyon** [comment]
ref #374, i think that would fix the need for this helper script. if anyone wants to rebase it and add tests i'll be glad to merge it.

**Comment by lukeaus** [comment]
OK I got it working

just needed to do this

settings.py
```
COMPRESS_PRECOMPILERS = (
    ('text/typescript', 'tsc --out {outfile} {infile}'),
)
```

in your base.html file
```
{% load compress %}

{% compress js %}
  {% block ts %}
  {% endblock ts %}
{% endcompress %}
```

in example.html
```
{% block ts %}
{{ block.super }}
<script type="text/typescript" src="{% static 'path/to/example.ts' %}"></script>
{% endblock ts %}
```

Bonus
don't forget to gitignore the .js file
in .gitignore
```
path/to/typescript/*/*.js
```
