### ISSUE TITLE
CSSAbsoluteFilter can't be used with url encoded inline SVGs which use url()

### ISSUE THREAD

**Issue by benebun** [django-compressor/django-compressor#624]
Hi,

first of all, thank you for a great tool!

I just ran into the following issue:
I'm using inline SVGs in their url encoded form (for better gzip compression than base64, so I'm not using django-compressor's CSSDataUriFilter which automatically encodes in base64).
However now I can't use the CSSAbsoluteFilter because it replaces the url()s within the SVG which is used for [linking](http://www.w3.org/TR/SVG/linking.html) in SVGs.

So I guess there might be two ways of solving this:
1. Either let the CSSDataUriFilter use url encoding for SVGs
2. Or avoid the CSSAbsoluteFilter replacing url()s (the ones in the invline SVG) within another url() (the one in the CSS).

Maybe there is a better workaround?

**Comment by karyon** [comment]
i think this might be the same issue as #764 .
