### ISSUE TITLE
Compressor breaks when staticfiles added with AppConfig

### ISSUE THREAD

**Issue by jarshwah** [django-compressor/django-compressor#626]
https://github.com/django-compressor/django-compressor/blob/develop/compressor/utils/staticfiles.py#L7 ensures that:

```
if "django.contrib.staticfiles" in settings.INSTALLED_APPS:
```

But if you've added staticfiles like so:

```
INSTALLED_APPS = (
    ...
    'django.contrib.staticfiles.apps.StaticFilesConfig',
    ...
)
```

The check fails, and compressor breaks.

**Comment by rfleschenberg** [comment]
Why do you add it like that? Is that officially supported by Django?

**Comment by jarshwah** [comment]
Yes - that's the new way to add applications from 1.7, using AppConfigs. If you don't specify one yourself, you get the default. But that might not always be the case, so it's better to be forwards compatible.

**Comment by rfleschenberg** [comment]
Alright, thanks! I wrote a failing test and am working on a fix for this.

**Comment by diox** [comment]
Should be fixed in the `develop` branch thanks to  @rfleschenberg 's patch.
