### ISSUE TITLE
Variable request does not exist in Offline mode

### ISSUE THREAD

**Issue by mauricioabreu** [django-compressor/django-compressor#651]
Exception:

```
Traceback (most recent call last):
  File "manage.py", line 30, in <module>
    execute_from_command_line(sys.argv)
  File "/vagrant/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/vagrant/env/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/vagrant/env/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/vagrant/env/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "/vagrant/env/lib/python2.7/site-packages/django/core/management/base.py", line 660, in handle
    return self.handle_noargs(**options)
  File "/vagrant/env/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 282, in handle_noargs
    self.compress(sys.stdout, **options)
  File "/vagrant/env/lib/python2.7/site-packages/compressor/management/commands/compress.py", line 191, in compress
    nodes = list(parser.walk_nodes(template))
  File "/vagrant/env/lib/python2.7/site-packages/compressor/offline/django.py", line 153, in walk_nodes
    for node in self.walk_nodes(node, original):
  File "/vagrant/env/lib/python2.7/site-packages/compressor/offline/django.py", line 149, in walk_nodes
    for node in self.get_nodelist(node, original):
  File "/vagrant/env/lib/python2.7/site-packages/compressor/offline/django.py", line 131, in get_nodelist
    return handle_extendsnode(node, block_context=None, original=original)
  File "/vagrant/env/lib/python2.7/site-packages/compressor/offline/django.py", line 40, in handle_extendsnode
    return handle_extendsnode(node, block_context, original)
  File "/vagrant/env/lib/python2.7/site-packages/compressor/offline/django.py", line 33, in handle_extendsnode
    compiled_parent = extendsnode.get_parent(context)
  File "/vagrant/env/lib/python2.7/site-packages/django/template/loader_tags.py", line 96, in get_parent
    parent = self.parent_name.resolve(context)
  File "/vagrant/env/lib/python2.7/site-packages/django/template/base.py", line 668, in resolve
    arg_vals.append(arg.resolve(context))
  File "/vagrant/env/lib/python2.7/site-packages/django/template/base.py", line 787, in resolve
    value = self._resolve_lookup(context)
  File "/vagrant/env/lib/python2.7/site-packages/django/template/base.py", line 839, in _resolve_lookup
    (bit, current))  # missing attribute
django.template.base.VariableDoesNotExist: Failed lookup for key [request] in u"[{'False': False, 'None': None, 'True': True}, {u'STATIC_URL': '/static/'}]"
```

Command:
```python manage.py compress --traceback --settings=azionmanager.settings.deploy --verbosity=3```

```
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
```

Background:

I am migrating from Django 1.6 to Django 1.8 and I upgraded Django and Django Compressor.
**Django 1.8.4**
**Django Compressor 1.5**

Using Django Compressor 1.3 and Django 1.6 it was working fine. 

Debugging Django Compressor I checked that:
1) New versions of Django/Django Compressor are loading more templates with compress tags than before (when only my base.html has compress template tag).
2) I have only one template with compress tag (base.html) and all other templates inherit from it.
3) In this line https://github.com/django-compressor/django-compressor/blob/develop/compressor/management/commands/compress.py#L192 I added django.template.base.VariableDoesNotExist exception to debug and now my templates are being compressed.

Sorry for this long text.

**Comment by diox** [comment]
This is a result of the fixes that were merged to deal with inheritance in offline compression.

Can you show your full template ? I'd need to see where the variable is used to better understand the issue. Ccatching `VariableDoesNotExist` blindly is something we'll want to avoid.

**Comment by mauricioabreu** [comment]
I can show you my templates of course.

(templates in short versions)

base.html
```
{% load compress %}
<!DOCTYPE html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    {% compress css %}
        <link rel="stylesheet" type="text/css" href="{{ STATIC_URL }}css/style.css" />
    {% endcompress %}
    {% block extra_css %}{% endblock %}
</head>
...
```

base_logged.html
*this template inherits base.html*
```
{% extends "base.html"|pjax:request %}
{% load i18n %}
{% block header %}
<ul>
   <li><a href="{% url 'account:your_account' request.session.account %}">{% trans "Account Info" %}</a>
   </li>
{% endblock 
```

Others templates inherit from base_logged.html and have variables like request.session, request.user, request.GET. Do you need more info?

**Comment by diox** [comment]
`{% extends "base.html"|pjax:request %}` could cause this - I never used pjax so I don't know. Is it possible for you to try to write a reduced testcase with and without pjax to find out if it's linked ?

Also, your `base_logged.html` defines content for the `{% block header %}`, but it's not present in `base.html`, but I assume this is just because you truncated `base.html`, right ? Nothing important in the `base.html` concerning this block ?

**Comment by mauricioabreu** [comment]
Done.
Well, without pjax: request it works. :)
About the block headers: there is nothing important around. So I think the problem is that pjax:request

**Comment by mauricioabreu** [comment]
About django-easy-pjax: https://github.com/nigma/django-easy-pjax
For the library to work I need to append that template tag inside base_logged.html

Any idea? :)

**Comment by ddsstt** [comment]
Hey!

I somehow managed to get over this issue with PJAX by adding the following offline context to settings:

```
class Object(object):
    pass
fake_request = Object()
fake_request.META = {}

COMPRESS_OFFLINE_CONTEXT = {
    'STATIC_URL': STATIC_URL,
    'request': fake_request
}
```

**Comment by mauricioabreu** [comment]
@ddsstt I think it will work but I don't know if it is the best solution. Probably in our case it will work because we don't depend on anything inside request. Sorry for not providing a best solution than yours. Thanks anyways!

**Comment by mrmachine** [comment]
I'm getting the same error, triggered by a template with this code:

```
{% extends original_change_form_template|default:change_form_template %}
```

The problem seems to be that the filter is not failing silently like templates normally do when its argument cannot be resolved in the context. This seems to be a bug in Django, but it's so old there's no chance it will be fixed: https://code.djangoproject.com/ticket/13167

I had to "work around" it by just not passing a variable that might not exist to `|default`. Although my `COMPRESS_OFFLINE_CONTEXT` generator DOES include a `change_form_template` -- I'm not sure why this is not being used?

Does `django-compressor` not use the generated contexts when parsing templates (when `extends` is evaluated?)

If `django-compressor` only uses generated contexts when rendering templates, does this mean I can't properly render templates that use a variable in `extends` with all my generated contexts?

I also had to search my whole project for `{% extends [^"']` in an attempt to find the offending template that was causing the error. Perhaps `django-compressor` could help me narrow it down, at least?

**Comment by grzegorzswica** [comment]
@mauricioabreu @mrmachine Using offline context in template rendering was added in #758 though I don't think it has been released yet.

**Comment by mauricioabreu** [comment]
@grzegorzswica it sounds amazing. Thanks for pointing this out. :+1:

**Comment by karyon** [comment]
if i understood correctly, this has been fixed. if not, let me know!
