### ISSUE TITLE
django-appconf is unmaintained

### ISSUE THREAD

**Issue by simonsmiley** [django-compressor/django-compressor#654]
I just wanted to note that compressor is depending on an unmaintained python package.

**Comment by carltongibson** [comment]
Is it? @jezdez [was active on AppConf](https://github.com/jezdez-archive/django-appconf/issues/19#event-407077636) just today.

**Comment by carltongibson** [comment]
I just open jezdez-archive/django-appconf/issues/20 offering to take it on — lets see what @jezdez has to say.

**Comment by jezdez** [comment]
I'm happy to move the app from my archive to the compressor org

**Comment by diox** [comment]
Thanks for the initial report, @simonsmiley. @jezdez moved django-appconf to django-compressor org, we are now maintaining it.

**Comment by simonsmiley** [comment]
thank you for maintaining it
