### ISSUE TITLE
deal with the dependencies

### ISSUE THREAD

**Issue by karyon** [django-compressor/django-compressor#664]
i propose to:
* deprecate beatifulsoup v3. v4 works for all the python versions supported by compressor. support for v4 was done in #663.
* deprecate cssmin. it is unmaintained, has bugs (#541, PR for that is #600) and is slow (#655, probably #586).
* introduce https://github.com/sprymix/csscompressor instead, which is a more up-to-date port of the yuicompressor, specifically it has fixed #541
* make rcssmin and rjsmin a dependency, to not have some copied code lingering around. check beforehand whether there have been customizations to them in the compressor repo
* deprecate csstidy. its last release was in 2007.

questions @diox :
* does that above sound sensible to you?
* should the new dependencies (csscompressor, rcssmin, rjsmin) be optional?
* is there anything else you can think of?

**Comment by diox** [comment]
Sounds like a good plan. Will csscompressor solve the slowness issue we have with cssmin ?

I think the dependencies fro the default js and css filters should be mandatory. The rest optional and mentioned in the docs.

**Comment by diox** [comment]
Don't forget to update the docs : http://django-compressor.readthedocs.org/en/latest/quickstart/#dependencies

**Comment by diox** [comment]
Also: we ended up not making a release before October, so we should remove Django 1.4 support as well. According to https://www.djangoproject.com/download/ it's EOL.

**Comment by karyon** [comment]
while writing this i decided i will just go and implement the warnings. feel free to ignore the text below, i'll leave this here for future reference, in case i hit any obstacles :)

==========

i learned that deprecation warnings are silent by default in since python 2.7/3.2. django does some tricks to make their deprecation warnings appear during tests. so, i could probably do these tricks as well (but i don't really want to) or users won't see the warnings until they use `python -Wall`

that said, how important are the deprecation warnings to you? i mean it shouldn't get too complex, but will take quite some time, especially because the deprecated and new stuff should work both at the same time in the same release. simply removing or replacing all that stuff in a backcompat-breaking release would be a lot easier.

instead, in that release, we could detect settings that broke with that release and print a nice error message pointing to the release notes (maybe we should do that anyway). i think that's okay especially since it should take minimal effort for users to update their settings to work again. users wouldn't have the deprecation warnings in one release to smooth the transition progress, but then, i don't see much value in that (as i said, updating should take minimal effort), compared to the time i'd have to spend on it.

what do you think?

**Comment by karyon** [comment]
@diox as stated above, i'll remove rcssmin and rjsmin from the repo and make them mandatory dependencies in the setup.py. in quickstart.txt, there are instructions for installing django-appconf. since i guess it's highly unusual to install django-compressor via other ways than pip (you can even use pip to install it from git), i suggest removing that part or replacing it by "make sure to install the mandatory dependencies listed in setup.py". what do you think?

**Comment by diox** [comment]
Agreed with all that.
