### ISSUE TITLE
Broken url in exception

### ISSUE THREAD

**Issue by jsma** [django-compressor/django-compressor#671]
Attempting to update django-compressor to be Django 1.9 compatible and ran into this error:

    compressor.exceptions.OfflineGenerationError: No template paths found. None of the configured template loaders provided template paths. See http://django.me/template-loaders for more information on template loaders.

'django.me' no longer exists. Any ideas if this was just supposed to redirect to the official Django docs on template loaders or was this to some django-compressor specific article?

**Comment by diox** [comment]
Ah, this was just a short link to the django docs. We should replace it with the official (long) link.
