### ISSUE TITLE
Django 1.9: Switch to Python's OrderedDict/import_module, Origin

### ISSUE THREAD

**Issue by quinox** [django-compressor/django-compressor#675]
I haven't done extensive testing but there are at least 3 problems when running the `compress` management command with Django 1.9a1:

---
```python
File "virtual/lib/python3.4/site-packages/compressor/management/commands/compress.py", line 13, in <module>
    from django.utils.datastructures import SortedDict
ImportError: cannot import name 'SortedDict'
```

https://code.djangoproject.com/wiki/SortedDict:

> SortedDict is deprecated as of Django 1.7 and will be removed in Django 1.9. Use ​collections.OrderedDict instead. Available in Python 2.7 and 3.1+.

---

```python
  File "virtual/lib/python3.4/site-packages/compressor/management/commands/compress.py", line 14, in <module>
    from django.utils.importlib import import_module
ImportError: No module named 'django.utils.importlib'
```

import_module can be replaced by [Python's importlib.import_module](https://docs.python.org/2/library/importlib.html)

---

At this point it says "No templates found" because of a crash on line 140:
```python
  File "virtual/lib/python3.4/site-packages/compressor/management/commands/compress.py", line 139, in compress
    paths.update(list(get_template_sources('')))
TypeError: unhashable type: 'Origin'
```

I worked around this by changing that line to 
```python
paths.update([x.name for x in get_template_sources('')])
```

**Comment by carltongibson** [comment]
`import_lib` was fixed in dc35047f2e9f840de55305aa16003c

**Comment by carltongibson** [comment]
I've replaced `SortedDict` in #678

**Comment by carltongibson** [comment]
Not sure what to make of the last one. I added the change you provide to #677 in 93e1296 but it [lead to a lot of errors in the build](https://travis-ci.org/django-compressor/django-compressor/builds/84575210).

Can you look at those errors and see what you think? — If you look at [the previous passing build](https://travis-ci.org/django-compressor/django-compressor/builds/84574154) you can see that **it is working against Django 1.9** — and is being tested as such (since changing it breaks the build)

**Comment by quinox** [comment]
I'll do some testing tomorrow.

I'm not intimately familiar with the way Django template loaders work, but if I look at Django 1.9's `django/template/loaders/filesystem.py:31` where it defined `get_template_sources` it yields `Origin` objects. With 1.8 the same function seems to return strings.

**Comment by quinox** [comment]
It took me a while to get past all the packages (overextends, coffin, sekizai) that don't work with 1.9.

I get 23 errors from the test_offline testcases when running with 1.9, all of the `unhashable` flavour; looking at the ['passing' travis 1.9 job](https://travis-ci.org/django-compressor/django-compressor/jobs/84574171) I think something went wrong since I don't see it installing 1.9, at line 116 it install `Django==1.8.5` and no other mention of Django.

The `.name` change should not be applied to older Django versions, something like ee99176beb183e037e0d87f2db2c12995685cc21 works for me on both 1.8 and 1.9.

**Comment by carltongibson** [comment]
@quinox — Thanks for the good follow up. I'll have a play with this later.

**Comment by carlmjohnson** [comment]
I am attempting to use Django 1.9 and django-compressor, and I ran into this issue and came up with a similar fix. Any timeline for integrating ee99176 into a new release?

**Comment by diox** [comment]
Follow #697 for official support news. Since we have dependencies in our tests that are not compatible with 1.9 yet it's a bit annoying and because nobody made a pull request with that fix I had simply missed it.
