### ISSUE TITLE
Django 1.9 compatibility blocked by `overextends` dependency. 

### ISSUE THREAD

**Issue by carltongibson** [django-compressor/django-compressor#676]
#670 introduced a tests-only dependency on django-overextends. This is currently blocking 1.9 compatibility work because `overextends` is not 1.9 compatible itself. 

```
django-compressor/.tox/py34-1.9.x/lib/python3.4/site-packages/overextends/models.py", line 5, in <module>
    from django.template.base import add_to_builtins
ImportError: cannot import name 'add_to_builtins'
```

The issue is here: stephenmcd/django-overextends#19

**Comment by carltongibson** [comment]
Argh! :-) Blocking out  `overextends` reveals that Coffin falls over on 1.9 as well.

**Comment by diox** [comment]
Feel free to add `skipIf` to both tests to unblock you for the time being.

**Comment by carltongibson** [comment]
I've opened stephenmcd/django-overextends#22 to hopefully fix.
