### ISSUE TITLE
Allow option for some compress blocks to skip filters

### ISSUE THREAD

**Issue by petroleyum** [django-compressor/django-compressor#688]
In my Django project I have some JS files that I want to run through JSmin and some JS files that I don't want to minify (because they're already minified, or minification causes a bug), but I still would like to concatenate and deploy using the offline compression feature.

Ideally I would be able to have to compress blocks like this:
```
{% compress js %}
    <script>
    <script>
{% endcompress %}

{% compress js no-filter %}
    <script>
    <script>
{% endcompress %}

```

As far as I can tell there isn't a way to do this yet. Would this be a good idea?

I'm not familiar with this project yet, but it was suggested in a stackoverflow thread that if I were implementing this I would skip the `.filter()` method in `base.py hunks()`. Maybe I can set a property on a `CompressorNode` in the template tag function that will cause the node to skip the filter?

**Comment by diox** [comment]
If you want to do this you should implement it in your own template tag inheriting from compressor, IMHO. This is too much of an edge case to be in core.

**Comment by petroleyum** [comment]
Sounds good. Thanks.
