### ISSUE TITLE
New release on PyPI

### ISSUE THREAD

**Issue by kottenator** [django-compressor/django-compressor#694]
Hi!

I was looking for a solution of some  `django-compressor`'s problem and found that it's already solved in `develop` branch. But it's still not released (last release on PyPI was more than 6 months ago).

Could you, please, release a new version on PyPI so I could use it in production?

**Comment by diox** [comment]
Yes. I planned to do that last month but haven't had the time to do it. Will do it in the coming weeks.

**Comment by kottenator** [comment]
Thanks in advance! Great lib, by the way! ;)

**Comment by diox** [comment]
I just released 1.6. 

- https://pypi.python.org/pypi/django_compressor/
- http://django-compressor.readthedocs.org/en/latest/changelog/

**Comment by kottenator** [comment]
Thanks a lot! The library is great!
