### ISSUE TITLE
Django template compress js parsing error: Could not parse some characters...

### ISSUE THREAD

**Issue by olivierpons** [django-compressor/django-compressor#699]
I've tried to use http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/pages/index.html

And there's a problem with one JavaScript file:

Try to import this file:

http://ironsummitmedia.github.io/startbootstrap-sb-admin-2/bower_components/raphael/raphael-min.js

You'll get this error: `Could not parse some characters: [blabla ]`

You can reproduce it if you copy / paste the file an try to add it in a basic template like this:

`{% compress js %}`
`<script src="{% static "bower_components/raphael/raphael-min.js" %}"></script>`
`{% endcompress %}`

**Comment by karyon** [comment]
original page is not accessible anymore. i tried with raphael-min.js v2.1.4 and could not reproduce.
