### ISSUE TITLE
Release new version to PyPi

### ISSUE THREAD

**Issue by pypetey** [django-compressor/django-compressor#711]
Hi

It would be great if new version with django 1.9 support would be released to PyPi.

**Comment by diox** [comment]
Hi,

It would be yes, but there hasn't been sufficient testing done to do that. So if you want the current develop version to be released, please test it and report back, thanks!

**Comment by pypetey** [comment]
Is there an official way of testing this? How would you like to have it tested?

**Comment by diox** [comment]
Install from the repo develop branch, and make sure it's working for you :)

**Comment by nikolas** [comment]
The develop branch (at least, at 94755c5aa62d0e659c863bbe75968f51c094be6e) is working for me with Django 1.9. I haven't seen any problems yet.

**Comment by kottenator** [comment]
I'm waiting for the new release too - I can't switch to Django 1.9 until then (can't use `develop` version)

**Comment by diox** [comment]
I'll release a new version this week or the next. In the meantime, please test/continue testing the develop branch, thanks.

**Comment by altryne** [comment]
Checking as well, looks like the only change we needed to do is change the `CSSMinFilter` to `rCSSMinFilter` for some reason?
Otherwise, at least the offline compression went well

**Comment by diox** [comment]
Ah, yeah, maybe we should have added an alias for backwards-compatibility. `CSSMinFilter` has been replaced by `CSSCompressorFilter`, but you can also use `rCSSMinFilter` as well. See #700.

**Comment by diox** [comment]
Fixed by #721. pypi.python.org/pypi/django_compressor
