### ISSUE TITLE
Manifest file incorrect when running multiple template engines

### ISSUE THREAD

**Issue by thenewguy** [django-compressor/django-compressor#724]
When I run the following

```
python manage.py compress --engine django
python manage.py compress --engine jinja2
```

the resulting manifest file only contains entries for the jinja2 engine and causes 

```
OfflineGenerationError at /dashboard/

You have offline compression enabled but key "e328d39c961b947e653b1a4712ce85e8" is missing from offline manifest. You may need to run "python manage.py compress".
```

when the django templates are used.

**Comment by diox** [comment]
Yeah, multiple engines is not supported at the moment, it's an edge case : most of the time you're going to pick one template engine and just have the other for templates from generic apps that you don't control anyway, like when you use jinja2 but want the django admin to work.

**Comment by thenewguy** [comment]
@diox That is the case that I needed multiple template engines for.  A 3rd party app uses django templates with compressor while the rest of the project is using jinja2 templates with compressor.  I submitted a pull request for a simple management command that compresses multiple engines and updates the manifest file appropriately.  I can see where it would probably be preferable to add the logic into the main compress command but this is an immediate fix that works for me

**Comment by thenewguy** [comment]
@diox I just realized that I submitted the pull request to my own repo.  The management command at https://github.com/thenewguy/django_compressor/pull/1/files seems to work just fine for handling multiple engines.  I think it would be pretty simple to modify the compress command's handle method to wrap multiple engines.  Are there any particular pain points that prevented something like this from being implemented?

**Comment by thenewguy** [comment]
@diox I have a little bit of time and was able to find a charger for my tablet so I could put it together if it is something that would be accepted

**Comment by diox** [comment]
I would prefer for the original compress command to parse the `--engine` parameter and accept multiple engines separated by commas, e.g. `--engine django,jinja2`  (or if you prefer, allow the parameter to be specified more than once, adding to a list of engines, e.g. `--engine django --engine jinja2`). I'd gladly review a pull request doing that as long as it has tests and documentation.

**Comment by thenewguy** [comment]
@diox yes with the original command.  The other was just to check the concept and get me by immediately

**Comment by thenewguy** [comment]
@diox Are you okay with https://github.com/django-compressor/django-compressor/pull/733 as written and cleaning up the implementation in a second PR?

**Comment by thenewguy** [comment]
And by cleanup I mean moving the loop from the command handler to inside the compress method

**Comment by thenewguy** [comment]
@diox Just checking back in on this issue.  Don't want to bug you but I haven't heard back about the pr so I just wanted to drop a quick note

**Comment by diox** [comment]
Hey, sorry I have been ignoring compressor stuff recently as I lack the time to work on it.

**Comment by thenewguy** [comment]
@diox understood
