### ISSUE TITLE
compressor unable to find binaries in my path

### ISSUE THREAD

**Issue by imaia** [django-compressor/django-compressor#735]
Hello folks, I was trying compressor today with coffee scripts. I have the coffee binary added to my path from .bashrc. The thing is I'm getting the error ```/bin/sh: 1: coffee: not found``` I think it should not occur as coffee is in my path.

My COMPRESS_PRECOMPILERS is like so:

COMPRESS_PRECOMPILERS = (
    ('text/coffeescript', 'coffee --compile --stdio'),
    ('text/x-sass', 'sass {infile} {outfile}'),
    ('text/x-scss', 'sass --scss {infile} {outfile}'),
)

My default bash is zsh (I don't think this matters, but, just saying)

**Comment by karyon** [comment]
my guess would be that the bashrc does not apply in your case, maybe you're running an apache/nginx from another user?

this is quite unlikely to be a compressor issue, so i'll close this. if you think otherwise, feel free to comment and i'll reopen.
