### ISSUE TITLE
Compression with CSS filters break image file name with space in CSS result

### ISSUE THREAD

**Issue by stasdavydov** [django-compressor/django-compressor#736]
I have the background image CSS rule used file with a space in the name:

```
#checkout_form .credit-cards {
    background-image: url("../imgs/Credit cards.png");
}
```

{% compress css inline %} block produce the following result:
`#checkout_form .credit-cards{background-image: url("../imgs/Creditcards.png")}`
Space in file name is removed.

I use the following CSS filters:
`COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter',  'compressor.filters.cssmin.CSSMinFilter']`

**Comment by karyon** [comment]
hey, it would be cool if you could check whether it's the AbsoluteFilter or the minifier!

**Comment by karyon** [comment]
So, it looks like rcssmin is causing this. i built a test to assert the CssAbsoluteFilter is working correctly (#805) and opened https://github.com/ndparker/rcssmin/issues/7.
