### ISSUE TITLE
self.get_original_content(context) doesnt work with Django 1.7.7 and staticfiles

### ISSUE THREAD

**Issue by Morpho** [django-compressor/django-compressor#739]
Hi there,
I am using Django 1.7.7 with django-compressor 1.6.

I started the debugger in this line and got the following output https://github.com/django-compressor/django-compressor/blob/1.6/compressor/templatetags/compress.py#L64 :

```
>>> self.nodelist
django.template.debug.DebugNodeList([<Text Node: '
    <link href="'>, <django.templatetags.static.StaticNode object at 0x000000000743E278>, <Text Node: '" rel="stylesheet">
    '>])
>>> self.get_original_content(context)
django.utils.safestring.SafeText(u'\r\n    stylesheet">\r\n    ')
>>> 
```

It seems like in the next line (https://github.com/django-compressor/django-compressor/blob/1.6/compressor/templatetags/compress.py#L64) this string is then used to generate the offline hexdigest. This seems to be not correct. This function is not working well with the static file template tag it seems: https://github.com/django-compressor/django-compressor/blob/1.6/compressor/templatetags/compress.py#L119

**Comment by karyon** [comment]
i must say i didn't quite understand what the issue is, maybe because i don't know the code in question :) could you do another attempt at explaining the problem? a test case with something actually breaking would be massively helpful.

**Comment by Morpho** [comment]
Hey, sorry I couldnt explain it any better. But after updating to a current version of django-compressor and Django everything worked properly so I guess the issue is already resolved anyway. Thanks for all your great work!

**Comment by karyon** [comment]
thanks for reporting back!
