### ISSUE TITLE
Uploaded filename miss matches with actual rendered file name

### ISSUE THREAD

**Issue by WayneYe** [django-compressor/django-compressor#742]
Hi, i've spent quit a lot of time in debugging with this but didn't have the luck to find the solution, I was using django compressor 1.6, my django version is 1.7, and I am using django storage (AWS backend) and [collectfast](https://github.com/antonagestam/collectfast) the steps I was doing during my CD process were:

`./manage.py compress --force -v 3`
`./manage.py collectstatic`

After this I verified my static/manifest.json:
```javascript
{
  "8022e7b5996e94ef6fdaf37f4986b5e6": "<script type=\"text/javascript\" src=\"[my-cloudfront-domain]/js/e3d6db98a69b.js\"></script>",
  "92136ffc22f7103cde98ba47a476dfeb": "<link rel=\"stylesheet\" href=\"[my-cloudfront-domain]/css/9fc0d03accca.css\" type=\"text/css\" />"
}
```

However, while my page got requested, it actually requested:
```
GET [my-domain]/css/81d6d68556dc.css 
GET  [my-domain]/js/327024817666.js 
```

I searched the entire compressor build log (I used -v 3), and I didn't see the tag "81d6d68556dc" at all.

Could you please guide me what would be the possible cause of this?  Thank you and highly appreciated!

**Comment by diox** [comment]
This probably means you've got something in your `{% compress %}` blocks that is dynamic and therefore the hash generated by the compress command won't match.

**Comment by WayneYe** [comment]
@diox thank you very much for your reply, could you kindly explain more detailed about "dynamic"?  I guess it might be caused by this: I forgot to mention I was using grunt to actually compress/uglify my css/js files, I only used django compressor to generate the tag name, meaning my process was:

```
grunt build
./manage.py compress --force -v 3
./manage.py collectstatic
```

For example, after grunt build, it generates a "app.min.js" located at my `{STATIC_ROOT}` dir, and it was wrapped in html like:

'{% compress %}
<script src="{{ static app.min.js }}"></script>
{% endcompress %}
'

**Comment by diox** [comment]
That's... a completely unsupported use-case. You don't need compressor, have a look at django file storage documentation, and more specifically `CachedStaticFilesStorage`.

**Comment by WayneYe** [comment]
Thanks a lot for confirming this, but why not support this in the later release? I don't see there is any hard part to do this:)

**Comment by diox** [comment]
There is simply no point in doing this in compressor. I don't want to add support for every little use case there is, as it will increase complexity. Using tools like grunt is fine: it means you no longer need compressor.

**Comment by WayneYe** [comment]
However, I do need the the "finger print" technology, just like [Rails Assets pipeline](http://guides.rubyonrails.org/asset_pipeline.html), you may also check this https://github.com/rickharrison/broccoli-asset-rev

Grunt doesn't provide this, in python eco, compressor was the first one I found to support this.

**Comment by diox** [comment]
Django storages can do that for you, as mentioned in my previous comment. https://docs.djangoproject.com/en/1.9/ref/contrib/staticfiles/#cachedstaticfilesstorage

**Comment by WayneYe** [comment]
@diox I am using S3 as my backend storage (I used the django-storages lib), and I use Cloudfront as my CDN, so when finally deployed to my production ENV, I am expecting the assets checksum was already correctly generated and my django template can correctly render the checksumed js/css.

So could you guide me how can I achieve this?

**Comment by diox** [comment]
Sorry, I don't have time to help you debug this. You should ask on stackoverflow or similar.
