### ISSUE TITLE
Less with relative `url()` statements broken again when DEBUG=True?

### ISSUE THREAD

**Issue by jaddison** [django-compressor/django-compressor#744]
With the release of 2.0, has https://github.com/django-compressor/django-compressor/issues/226 resurfaced (regression)?

**Comment by diox** [comment]
Can you provide a testcase that works before and is broken in 2.0 ?

**Comment by jaddison** [comment]
I think the only issue introduced here is me - I believe I had some path issues in my configuration. I'll reopen if needed. Apologies for the noise!
