### ISSUE TITLE
Doesn't work with ManifestStaticFilesStorage

### ISSUE THREAD

**Issue by SeanHayes** [django-compressor/django-compressor#746]
STATICFILES_STORAGE = 'django.contrib.staticfiles.storage.ManifestStaticFilesStorage'
    COMPRESS_STORAGE = STATICFILES_STORAGE

Everything else loads fine, but my compressed blocks get requested with URLs like:
/static/CACHE/css/223db5fd3ad7.223db5fd3ad7.css
/static/CACHE/js/3a7b74ca0e8f.3a7b74ca0e8f.js

But only these files exist:
CACHE/css/223db5fd3ad7.css
CACHE/js/3a7b74ca0e8f.js

I thought about changing COMPRESS_ROOT to another directory and adding it to STATICFILES_DIRS so I could run collectstatic on it, but the docs say COMPRESS_ROOT is also where files are read from.

**Comment by SeanHayes** [comment]
This might be solved by setting COMPRESS_STORAGE to the default filesystem storage.

**Comment by diox** [comment]
Yes, you shouldn't set `COMPRESS_STORAGE` in this case.
