### ISSUE TITLE
Setting order of js files during compression

### ISSUE THREAD

**Issue by studiorooster** [django-compressor/django-compressor#747]
Just started using the compressor in my 1.9 app but I was wondering if there is a way to control the order the files are compressed?  I have all js files in the order they need to load in the browser, but when compressed, they are not in the same order.  

Thank you.

**Comment by karyon** [comment]
i just checked and here they are in exactly the same order i specified them in my template. only using the default filters. what does your settings.py look like?

**Comment by karyon** [comment]
not enough information, closing. if you can help us debugging this let us know and i'll reopen.
