### ISSUE TITLE
problem: No module named utils

### ISSUE THREAD

**Issue by funktasmas** [django-compressor/django-compressor#748]
hi,
to install the latest version on pip compressor throws the following error:
> No module named utils

I have installed the version 1.8.4 django

Exception Type:ImportError
Exception Value: No module named utils
Exception Location:	/usr/local/lib/python2.7/dist-packages/compressor/conf.py in <module>, line 5
Python Executable:	/usr/bin/python
Python Version: 2.7.6

**Comment by karyon** [comment]
hi, django 1.8.4 definitely does have that utils package. check your installation whether django 1.8 is actually used (e.g. print `django.VERSION`). i'm closing this for now, if you still have that error i can reopen.
