### ISSUE TITLE
1.5 -> 2.0 upgrade instructions

### ISSUE THREAD

**Issue by chriddyp** [django-compressor/django-compressor#752]
hey folks! I'm upgrading our site's `django-compressor` so that we [can use CSS's calc](https://github.com/django-compressor/django-compressor/issues/541) but am running into some (unknown) issues.

Is there a `1.5-2.0` upgrade guide (that might contain e.g. any backwards-incompatible changes) that I can reference?

Many thanks!!

**Comment by karyon** [comment]
there is [the changelog](http://django-compressor.readthedocs.org/en/latest/changelog/) with a list of stuff that was removed, but apart from that, no. what kind of problems are you experiencing? apart from replacing the unsupported compressors in your settings, there should be nothing to do.

**Comment by chriddyp** [comment]
the upgrade turned out to be a red-herring! we were able to able to upgrade without issues in the end. big thanks!
