### ISSUE TITLE
High CPU usage when using compress command

### ISSUE THREAD

**Issue by vikasgulati** [django-compressor/django-compressor#753]
CPU usage goes as high 85-90% on my MacbookPro when using compress command

Laptop Configuration & Library versions

- 2.7 GHz Intel Core i5
- 8GB 1867 MHz DDR3 RAM
- Django compressor 1.5
- Django 1.8.3

Is there any relevant gotcha/performance consideration w.r.t. compress command that I might be missing?
It this normal?
Any workarounds?

Ran CProfile along with gprofdot to analyze what method is taking longer.

Pasting a snapshot of the same below: (This is a trimmed snapshot with only the method that take longer than 5%)

![output_compress_trimmed](https://cloud.githubusercontent.com/assets/1867142/14135425/fdf3510a-f67a-11e5-9e61-d8e7528e9972.png)

**Comment by vikasgulati** [comment]
Perf with Django compressor 2.0 & Django 1.9.4 also seems to be same (over 90% usage)

![output_compress_trimmed 1](https://cloud.githubusercontent.com/assets/1867142/14135722/baaecb98-f67c-11e5-89a0-bc14b3aa36a4.png)

**Comment by carltongibson** [comment]
Look at your graph. All the time is spent in `cssmin` or in `subprocess`. It's your precompilers. So, yes, it's normal. No, there's no work around. ("Don't precompile" isn't the answer you're looking for.)

In general there's nothing wrong with high CPU when performing computations. 

This isn't an issue.

**Comment by vikasgulati** [comment]
yes agreed this isn't an issue in that case. 

I'll still try to highlight a general problem here which other might also in regards to this.

I have a staging instance which we try to keep as similar to production box except in terms of its size. 

Now the staging instance CPU usages shoots up 100% and the server hangs up (micro instance). Upgrading the instance just for a command that needs to a run a few times a day isn't very efficient a solution. So probably an on-demand instance that runs this command would be a good option.

**Comment by carltongibson** [comment]
Yeah... or compress locally and rsync into place... 

If your box can't even handle running one compress — which only takes a few seconds — then you need a bigger box.

It's not just for one command. Doing something like running migrations would be equally or more taxing. I imagine you'd have issue there too. 

You must be running a lot of processes to totally hang the instance — even a micro instance is normally powerful enough just for staging — and even production — either get more instance and spread the load or get a bigger instance.

**Comment by vikasgulati** [comment]
Yeah thanks for the suggestions @carltongibson.

Your intuition/imagination is pretty accurate I must say, [migrate is equally taxing](http://stackoverflow.com/questions/36303147/django-migrate-consuming-too-much-cpu) for us at the moment.
