### ISSUE TITLE
Support for web-components and HTML imports, more notably Polymer

### ISSUE THREAD

**Issue by andrewebdev** [django-compressor/django-compressor#754]
This may be quite a tricky one, because a single html import can contain JS, CSS and HTML, all in the same file. Currently we are using a nodejs script "polybuild" which will take a base html import and then follow any imports within it and separate it out into 2 separate files, the -build.js and -build.html.

It would be really good if django-compressor couls support this, though I expect this is not a trivial feature request.

**Comment by diox** [comment]
IMHO this is out of scope for compressor itself. You may want to look at JavaScript build systems instead.
