### ISSUE TITLE
requiring settings.DEBUG is True in get_filename prevents working without staticfiles

### ISSUE THREAD

**Issue by palewire** [django-compressor/django-compressor#773]
Is there a reason why settings.DEBUG is called explicitly [right here](https://github.com/django-compressor/django-compressor/blob/develop/compressor/base.py#L118)? I'm attempting a slightly modified implementation of compressor without staticfiles installed and this is preventing me from finding local files with DEBUG on.

**Comment by karyon** [comment]
just to be sure, did you read the comment directly above this line? does it make sense to you? to me not immediately, but i'd dig into it or ask @diox if that doesn't help you already.

**Comment by palewire** [comment]
I *think* I understand it, but I'm not sure. I suspect that idea is intended to solve a problem in the most common compressor use cases. 

In my situation, I am aiming for an extremely light implementation using only "inline" compression with the templatetags, and if I can I'd like to do without ``staticfiles`` installed. 

To me, it seems more consistent for ``COMPRESS_ENABLED`` to be the global switch on what behavior to expect and this appears to be a circumstance where ``DEBUG`` is being used internally in a way that could "magically" conflict with my configuration.

As the comment suggests, there might be a practical reason for doing that aimed at helping out a large number of users, but I'm struggling to sort it out in my use case.

**Comment by diox** [comment]
The rationale behind this code is that, in local development, we want to avoid the artifacts of an old `collectstatic` or `compress` call, so we avoid looking in the storage that is used for the final file, and look through staticfiles finders instead.

Using compressor without staticfiles is not really supported, son sorry, but you're on your own. If you have your own modified compressor, you should alter the `get_filename` implementation to suit your needs.

**Comment by palewire** [comment]
Alrighty. Fair enough. Here's a related question: could you point me to any good examples of a subclassed variation on compressor? I'd love to be able to pull it off without having to fork the repo.

**Comment by diox** [comment]
`COMPRESS_CSS_COMPRESSOR` and `COMPRESS_JS_COMPRESSOR` settings control which class compressor instantiates. Those settings and the base classes are not documented but it should be pretty straightforward to understand by looking at the code (grep for those settings, then look at the classes implementations)

**Comment by palewire** [comment]
Thank you.
