### ISSUE TITLE
error 22 from memcached_get(:1:django_compressor.mtime.c4cd5): SUCCESS

### ISSUE THREAD

**Issue by dalou** [django-compressor/django-compressor#777]
Hello,

When i compress my assets the first time, it's work fine but step by step all caches crashes in my entire project with the error 22 from memcached (DELETED). What's wrong ? 
I 'm on django-compressor 2.0.

Thx

**Comment by dalou** [comment]
Note my production config is under dokku memcached. 
And an exemple of a complete traceback :

u'Failure: error 1 from memcached_get(:1:django_compressor.mtime.6f13e): SUCCESS', 
u'  File "django/core/handlers/base.py", line 174, in get_response', 
u'  File "django/core/handlers/base.py", line 172, in get_response', 
u'  File "django/template/response.py", line 160, in render', 
u'  File "django/template/response.py", line 137, in rendered_content',
u'  File "django/template/backends/django.py", line 95, in render', 
u'  File "django/template/base.py", line 206, in render', 
u'  File "django/template/base.py", line 197, in _render', 
u'  File "django/template/base.py", line 992, in render', 
u'  File "django/template/base.py", line 959, in render_annotated', 
u'  File "django/template/loader_tags.py", line 173, in render', 
u'  File "django/template/base.py", line 197, in _render', 
u'  File "django/template/base.py", line 992, in render', 
u'  File "django/template/base.py", line 959, in render_annotated', 
u'  File "django/template/loader_tags.py", line 173, in render', 
u'  File "django/template/base.py", line 197, in _render', 
u'  File "django/template/base.py", line 992, in render',
u'  File "django/template/base.py", line 959, in render_annotated', 
u'  File "compressor/templatetags/compress.py", line 127, in render', 
u'  File "compressor/templatetags/compress.py", line 99, in render_compressed', 
u'  File "compressor/templatetags/compress.py", line 78, in render_cached', 
u'  File "compressor/cache.py", line 94, in get_templatetag_cachekey', 
u'  File "compressor/utils/decorators.py", line 39, in __get__', 
u'  File "compressor/base.py", line 176, in cachekey', 
u'  File "compressor/utils/decorators.py", line 39, in __get__', 
u'  File "compressor/base.py", line 171, in mtimes', 
u'  File "compressor/cache.py", line 100, in get_mtime', 
u'  File "django/core/cache/backends/memcached.py", line 76, in get

**Comment by dalou** [comment]
And sorry my settings : 
########## COMPRESSION CONFIGURATION
# See: http://django_compressor.readthedocs.org/en/latest/settings/#django.conf.settings.COMPRESS_ENABLED
COMPRESS_ENABLED = bool(int(os.environ.get('COMPRESS_ENABLED', '0')))
COMPRESS_OFFLINE = bool(int(os.environ.get('COMPRESS_OFFLINE', '0')))
COMPRESS_CSS_HASHING_METHOD = 'content'
COMPRESS_OUTPUT_DIR = ''
COMPRESS_CSS_FILTERS = [
    'compressor.filters.template.TemplateFilter',
    'compressor.filters.css_default.CssAbsoluteFilter',
    # 'compressor.filters.cssmin.CSSCompressorFilter',
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.template.TemplateFilter',
    'compressor.filters.jsmin.JSMinFilter',
]
########## END COMPRESSION CONFIGURATION

**Comment by karyon** [comment]
have you made any progress with this or do you have any additional info what could be causing this? could you try using a different cache backend to rule out it's a memcached issue?

**Comment by karyon** [comment]
at a first glance it seems weird that mtime appears in your traceback but your setting says `content`. could you test setting it to `mtime`?

**Comment by karyon** [comment]
no answer :( if you have any additional information, let us know.
