### ISSUE TITLE
Make offline compression independent of STATIC_URL

### ISSUE THREAD

**Issue by kottenator** [django-compressor/django-compressor#778]
I use offline compression. I do `manage.py compress` once and then deploy the project with gathered static files to multiple servers. 

On different servers I can have different `STATIC_URL`, not the one used for compression. That's problematic for current `django-compressor` implementation because:
- it calculates _offline manifest keys_ using _actual_ `STATIC_URL` when in the `manifest.json` it corresponds to `STATIC_URL` used during `manage.py compress`. And it raises an exception - "the key is not found in the offline manifest"
- another problem is that in offline manifest you store pieces of HTML that also contain _obsolete_ `STATIC_URL` which doesn't work on deployed site instance because `STATIC_URL` is different now

You could change 3 things to make it work:
- when calculating manifest keys: substitute all `STATIC_URL` entries with some constant, e.g.: `/static/` → `$STATIC_URL`
- when generating offline manifest via `manage.py compress` - don't put actual `STATIC_URL` (e.g. `/static/`) into `manifest.json` but put some constant like `$STATIC_URL` instead
- when reading the manifest - replace all `$STATIC_URL` with actual `STATIC_URL`, e.g.: `$STATIC_URL` → `/new/static/`

**Comment by kottenator** [comment]
I've created [a gist](https://gist.github.com/kottenator/fe4b0a05d1645af6986fbfdd407c57a7) that _patches_ `django-compressor` - it's a quick-and-dirty solution for my project. Maybe you'll find it useful.

**Comment by karyon** [comment]
may i ask, why do you have different `STATIC_URL`s?

**Comment by kottenator** [comment]
Sure, for example, I host my Django app on multiple sub-paths of the same domain, like:

* http://example.com/dev/my-app/
* http://example.com/staging/my-app/

Unfortunately, we can't use sub-domains for that. So the static files are hosted at:

* http://example.com/dev/my-app/static/
* http://example.com/staging/my-app/static/

I configure `STATIC_URL` via environment variable, so it's `/dev/my-app/static/` and `/staging/my-app/static/` correspondingly.

But `django-compressor` has generated static files with `STATIC_URL = '/static/'`.

**Comment by diox** [comment]
Can't you use a different offline manifest for both environments ?

**Comment by kottenator** [comment]
I build Django project distribution once and deploy it on multiple instances. The dist doesn't know about where it'll be deployed - it's a matter of configuration.

**Comment by kottenator** [comment]
I build Django project distribution once and then deploy it on multiple hosts. The dist doesn't know where it'll be deployed - it's a matter of configuration.

**Comment by Ashald** [comment]
We have similar use-case - app is built completely once and then we need to deploy it at arbitrary locations (sub-paths) with different configuration (generally following 12factor approach). Hence we set `STATIC_URL` for each deployment via configuration and it doesn't work with `django-compressor` as it is now. Also we cannot 'pre-build' manifests for 'different environments' since (1) they're arbitrary and (2) we follow the policy of immutable artifacts (exactly the same code and files deployed each time).

Are there any issues with omitting `STATIC_URL` from values in manifests?..

**Comment by dsizomin** [comment]
Having same issue in similar use-case.

**Comment by illia-okonskyi** [comment]
+1 for my friend :)

**Comment by diox** [comment]
Please don't comment if you have nothing meaningful to add. If you care about this functionality, implement it, with good tests and care for backwards-compatibility, and submit a pull request.

**Comment by kottenator** [comment]
I'm going to prepare a PR on Thursday or Friday. It may look _hacky_ but it works :)

**Comment by kottenator** [comment]
Pull-request created.

**Comment by kottenator** [comment]
@karyon - I saw you've added `needinfo` label. Do you need any information from me? Can I help?

**Comment by karyon** [comment]
yeah i just wanted to follow up regarding the pull request. now you've created one :)
