### ISSUE TITLE
Request: version number caching css/js

### ISSUE THREAD

**Issue by rafalolszewskii** [django-compressor/django-compressor#783]
Not entirely sure, but I can guess that: `CSS_HASHING_METHOD = 'mtime/content/none'` is the only way to set the suffix for our output file.

It would be awesome if we could set at least version number like this:

```
<link rel="stylesheet" type="text/css" href="style.css?v=12345678" />
```

or

```
<link rel="stylesheet" type="text/css" href="style.css?v=1.1.3" />
```

**Comment by karyon** [comment]
what's your use case for this?

the way i see it, the compressed output can be re-generated from your (hopefully versioned :) ) source at any time and is not meant to be versioned or put into an archive or anything like that. think of it like a cached artifact to not re-compress everything on every page view.

**Comment by rafalolszewskii** [comment]
I'm using django-compressor only to version my css file (many of my web visitors are seeing old content - they have to use ctrl + f5 to refresh browser cache). What I woul'd like to get is an option to append different suffixes to my `style.css` file, right now it's giving me hash `3e5b38af6c14.css`

what I would like to get is for example:
`style.css?v=1.1.3`
Just a different type of suffix instead of hashed one.

**Comment by karyon** [comment]
yeah, but for what purpose? what practical benefit would a version number have? as i said, to me it's just a cached binary artifact, so i personally don't see the value in adding a version number yet, that's why i ask.

**Comment by karyon** [comment]
would you do one more attempt at explaining your use case? sorry it i'm being dumb here.

**Comment by karyon** [comment]
no answer for a while :(
