### ISSUE TITLE
Broken in 1.10 due to option_list (Deprecated Django 1.8)

### ISSUE THREAD

**Issue by jvc26** [django-compressor/django-compressor#784]
django_compressor appears broken in 1.10 due to the behaviour of the management command requiring ```BaseCommand.option_list```. This has been deprecated since Django 1.8, and consequently breaks on running in 1.10:

```
    class Command(BaseCommand):
  File "/usr/local/lib/python3.5/site-packages/compressor/management/commands/compress.py", line 39, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

[```BaseCommand.add_arguments()```](https://docs.djangoproject.com/en/1.10/howto/custom-management-commands/#django.core.management.BaseCommand.add_arguments) should be used instead.

**Comment by jvc26** [comment]
This was fixed and merged at django-compressor/django-compressor@86ccfd29c3a4695f315637295c3d5ab20484e6c, but doesn't appear to have been released on PyPI

**Comment by scop** [comment]
Any ETA for a new release with this fix included?

**Comment by diox** [comment]
I'll look into that this week.

**Comment by diox** [comment]
https://pypi.python.org/pypi/django_compressor/2.1 has been released.
