### ISSUE TITLE
SCSS compiler doesn't compile SCSS variable to CSS.

### ISSUE THREAD

**Issue by ronypur** [django-compressor/django-compressor#794]
Hi, i have some problems when using django-compressor v2.1. I don't know if these errors suppose to be like that or there are something that i'm missing.
1. When DEBUG = False, the SCSS files are compiled and compressed in the template but it couldn't be accessed (status 404). Here are my code:

settings.py

```
DEBUG = False
COMPRESS_OFFLINE = True
COMPRESS_ENABLED = True
COMPRESS_CACHE_BACKEND = 'compressor'
COMPRESS_COMPILERS = (
    'text/x-scss', 'django_libsass.SassCompiler',
)
```

base.html

```
{% load compress %}
{% load staticfiles %}
{% compress css %}
        <link rel="stylesheet" type="text/x-scss" href="{% static 'scss/style.scss' %}" charset="utf-8">
        <link rel="stylesheet" type="text/x-scss" href="{% static 'scss/lib.scss' %}" charset="utf-8">
  {% endcompress %}
```

base.html output

```
<link rel="stylesheet" href="/static/CACHE/css/b3dd48924908.css" type="text/css">
```
1. When DEBUG = True,  the cached CSS file doesn't fully compiled the SCSS file.

style.scss and style.css

```
$primary-color: #333;

body {
  color: $primary-color;
}
```

**Comment by karyon** [comment]
were you able to solve this?

could you paste your actual settings.py? at least the COMPRESS_COMPILERS part ist wrong in your snippet (it's COMPRESS_PRECOMPILERS)
with DEBUG=False, are there any output files in the cache directory? or rather, where does the compress command output its result?

**Comment by karyon** [comment]
not enough information, closing. feel free to reply and i'll reopen.
