### ISSUE TITLE
Running into OfflineGenerationError after successfull compress

### ISSUE THREAD

**Issue by bastbnl** [django-compressor/django-compressor#798]
Hi,

First of all I'd like to thank the maintainers for supporting and maintaining django-compressor. Thanks for this great app.

I ran into compressor.exceptions.OfflineGenerationError when using django-compressor 2.1 with Django 1.10.1 on python 2.7 using these compressor settings when started via manage.py compress:

```
# Settings for django-compressor
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_OFFLINE_CONTEXT = {}
COMPRESS_OUTPUT_DIR = 'c'
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',
]
```

`python manage.py compress --force` selects the templates I'd expect it to and appears to create the  content I expect it to:

```
(venv)bastb@141:/somewhere$ python manage.py compress --force
Found 'compress' tags in:
        /var/www/brownpapersession/dev/brownpapersession/templates/component/angular-bootstrap.html
        /var/www/brownpapersession/dev/brownpapersession/topic/templates/topicowner.html
        /var/www/brownpapersession/dev/brownpapersession/session/templates/session.html
        /var/www/brownpapersession/dev/brownpapersession/app/templates/home.html
Compressing... /var/www/brownpapersession/dev/brownpapersession/templates/component/angular-bootstrap.html
/var/www/brownpapersession/dev/brownpapersession/topic/templates/topicowner.html
/var/www/brownpapersession/dev/brownpapersession/session/templates/session.html
/var/www/brownpapersession/dev/brownpapersession/app/templates/home.html
done
Compressed 7 block(s) from 4 template(s) for 1 context(s).
```

The topicowner template is processed successfully, but the remaining templates cannot be loaded when served via runserver. The other pages run into an OfflineGenerationError.

Setting COMPRESS_ROOT to STATIC_ROOT and making sure it has an absolute path (as found on http://stackoverflow.com/a/28787622/4982251) resolved the issue. For reference: 

```
# Settings for django-compressor
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True
COMPRESS_OFFLINE_CONTEXT = {}
COMPRESS_ROOT = STATIC_ROOT
COMPRESS_OUTPUT_DIR = 'c'
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',
]

```

Note that `STATIC_ROOT` was set to a valid, existing and writable, absolute path.

Remaining question is why did I need to set COMPRESS_ROOT to get the two remaining templates to work properly?

**Comment by bastbnl** [comment]
That was a bit too optimistic, Just performed some minimal changes to learn the page is not rendered, but contains an HTTP 500 referencing the OfflineGenerationError exception

The pages are rendered correctly when runserver is stopped and started.

The templates mentioned in the previous content inherit from a template containing navigation. This navigation template inherits from the base template. The base template does not have any compress tags loaded.

Might be worth noting. I'm using channels version 0.17.2, which comes with an updated runserver.

**Comment by karyon** [comment]
i'm a bit confused what's going on. 

> So I stop runserver, generate the offline content and restart the development server to prevent the OfflineGenerationError

but... what exactly is broken then? it would be nice if you could provide steps to reproduce your problem.

**Comment by karyon** [comment]
one thing i just noticed is you're explicitly setting `COMPRESS_OFFLINE_CONTEXT` to be empty. by default it contains `{'STATIC_URL': settings.STATIC_URL}`. that might be part of the issue.

**Comment by bastbnl** [comment]
@karyon Feel free to close this issue. It looks as if the app is doing what it's supposed to do. I must have run into some getting started trouble (or ebkac) ...

**Comment by karyon** [comment]
no problem, thanks for checking back!
