### ISSUE TITLE
Cannot minify js from template tag

### ISSUE THREAD

**Issue by jasjuang** [django-compressor/django-compressor#800]
In my html file I have something like

```
{% load google_analytics %} 
{% load compress %}

<head>
    {% compress js %}
    {% google_analytics %}
    {% endcompress %}
</head>
```

However when I run it and look into it from view page source, the javascript snippet from `{% google_analytics %}` is not minified. Am I doing something wrong or is this not supported?

**Comment by karyon** [comment]
what google analytics library are you using? both that i could find don't have these templatetags.

**Comment by jasjuang** [comment]
It is django-analytical that I am using. http://django-analytical.readthedocs.io/en/latest/services/google_analytics.html

**Comment by karyon** [comment]
hey, could you post your settings.py (or the parts related to compression and google analytics). also, does this happen only when using offline compression or also during "regular" compression?

**Comment by jasjuang** [comment]
This happens when using both offline and online.

Here is my settings.py with related info, actually not much has to be added to it

``````
# Application definition

PREREQ_APPS = [
    ...
    'analytical',
    'compressor',
]

PROJECT_APPS = [
    'home',
]

INSTALLED_APPS = PROJECT_APPS + PREREQ_APPS

GOOGLE_ANALYTICS_PROPERTY_ID = 'UA-XXXXXXXX-X'
GOOGLE_ANALYTICS_DOMAIN = 'mysite.com'
GOOGLE_ANALYTICS_DISPLAY_ADVERTISING = False
GOOGLE_ANALYTICS_SITE_SPEED = True
``````

**Comment by imposeren** [comment]
@jasjuang, I was not able to reproduce your problem.

My config:
https://bitbucket.org/imposeren/tabletop-planning/commits/e4c5097c16f7f8cbb1c4a2e3fa1f2de0723fd3e2

Extra config info (not visible on previous url):
```python
COMPRESS_ENABLED = True
COMPRESS_OFFLINE = True

COMPRESS_PRECOMPILERS = (
    ('text/less', 'lessc {infile} {outfile}'),
)

COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',
]

COMPRESS_JS_FILTERS = [
    'compressor.filters.closure.ClosureCompilerFilter',
]

```

Resulting html:
```html
<script type="text/javascript" src="/static/CACHE/js/d4b6d170df7aXXXX.js"></script>
```

Contents of minified file:
```javascript
;var _gaq=_gaq||[];_gaq.push(['_setAccount','UA-XXXXXX-X']);_gaq.push(['_trackPageview']);(function(){var ga=document.createElement('script');ga.type='text/javascript';ga.async=true;ga.src=('https:'==document.location.protocol?'https://ssl':'http://www')+'.google-analytics.com/ga.js';var s=document.getElementsByTagName('script')[0];s.parentNode.insertBefore(ga,s);})();
```

**Comment by jasjuang** [comment]
@imposeren Thanks for the reply. I stopped django development a while back and this might be fixed by commits since the filing of this issue.
