### ISSUE TITLE
Document manifest key generation

### ISSUE THREAD

**Issue by kissgyorgy** [django-compressor/django-compressor#801]
The manifest keys generated by the static url.
I set up the `STATIC_URL` to `/assets/` during development and deployment, but it is `https://static.example.com/` on the production environment.
During deployment, the `compress` command generated different keys, so in production I got `compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "bb7b62c2390557063f2a4838992971ed" is missing from offline manifest. You may need to run "python manage.py compress"` errors. Took me hours to figure it out.

I suggest that this at least should be documented.

**Comment by karyon** [comment]
What exactly are you proposing? https://django-compressor.readthedocs.io/en/latest/behind-the-scenes says that the hash is based on the template code. So the information is there, although not obvious. Do you want that to be in a more prominent place? Or some general note that changing template contents are a common pitfall? I'd like to hear your opinion.

**Comment by karyon** [comment]
ping @kissgyorgy :)

**Comment by karyon** [comment]
ref #778

**Comment by kissgyorgy** [comment]
> ref #778

That's a better proposal than mine :)

**Comment by karyon** [comment]
we'll likely get the underlying issue #778 fixed soon, closing.

**Comment by karyon** [comment]
fyi, #778 has been fixed.
