### ISSUE TITLE
Strategy for minification, but not concatenation

### ISSUE THREAD

**Issue by chris-erickson** [django-compressor/django-compressor#816]
I haven't been able to locate the best way to accommodate the configuration that you want files to be processed, but not concatenated.  The reason for this setup being to let the server (using HTTP2) take advantage of other benefits of serving multiple small files vs a single large file.

**Comment by diox** [comment]
Hi,

I would recommend using something else than compressor in that scenario. It was not designed for this, and if you're at the point where you're using HTTP2, there are plenty of more flexible/modern tools around that will suit you better.
