### ISSUE TITLE
Compressor templates in 2.1 have incorrect permissions

### ISSUE THREAD

**Issue by ishirav** [django-compressor/django-compressor#819]
Looks like the issue in https://github.com/django-compressor/django-compressor/issues/719 happens again in v2.1

```
ll django_compressor-2.1*/compressor/templates/compressor
total 16K
-rw------- 1 root root 136 Jan 30 08:16 css_file.html
-rw------- 1 root root 127 Jan 30 08:16 css_inline.html
-rw------- 1 root root  89 Jan 30 08:16 js_file.html
-rw------- 1 root root  69 Jan 30 08:16 js_inline.html

```

**Comment by diox** [comment]
Sigh. I should have a linting rule or something to prevent this from happening...

**Comment by carltongibson** [comment]
Hmmm. This must be the packaging... I thought I'd fix it quick but there's nothing wrong in the repo:

```
~/Documents/Django-Stack/django-compressor (develop)$ find . -name *.html -print0 | xargs -0 chmod 644
~/Documents/Django-Stack/django-compressor (develop)$ git status
On branch develop
nothing to commit, working directory clean
```

**Comment by diox** [comment]
It is. Needs a new release to fix it in order not to mess with existing hashes on pypi.

**Comment by diox** [comment]
This should be fixed in https://github.com/django-compressor/django-compressor/commit/e2b7a3efdab733260da77d622d63748d48854fde https://pypi.python.org/pypi/django_compressor/
