### ISSUE TITLE
No changelog or git tag for version 2.1.1

### ISSUE THREAD

**Issue by intgr** [django-compressor/django-compressor#820]
Hi! I see on PyPI that version 2.1.1 was released yesterday, but there's no git tag for this version, nor a changelog entry. I assume that's a mistake?

**Comment by carltongibson** [comment]
2.1.1 just corrects a packaging issue. #819 — no changes. But yes...

**Comment by diox** [comment]
I had forgotten to push the tag. Yeah, I should have made a changelog...

**Comment by karyon** [comment]
Fixed by #821.
