### ISSUE TITLE
ld+json

### ISSUE THREAD

**Issue by darkkase** [django-compressor/django-compressor#829]
well  is not realy a issu, but is a nice to have.

if you use  application/ld+json ( https://developers.google.com/schemas/formats/json-ld )  and put the code inside  {%compress js inline%} {%endcompress%}    django-compressor change the  type "application/ld+json"  to "text/javascript"

**Comment by diox** [comment]
See https://github.com/django-compressor/django-compressor/pull/830#issuecomment-280890067
