### ISSUE TITLE
Can't get site to work on Heroku

### ISSUE THREAD

**Issue by paulnicholsen27** [django-compressor/django-compressor#831]
Been struggling with this for a week and hope you can help.  Not sure if it's a bug or if I'm dumb. My site works fine locally but I can't get it working through Heroku.  When I have `compress_offline` set to True, I get the error:

`OfflineGenerationError at /
You have offline compression enabled but key "e6c36496cd6e85aa473a6964e49a2d71" is missing from offline manifest. You may need to run "python manage.py compress".`

When I set it to False, the site loads but anything I have in an scss file does not.  There's some more details here http://stackoverflow.com/questions/42262463/cant-use-django-compress-with-heroku
and my site repo is at https://github.com/paulnicholsen27/within_reach.

**Comment by karyon** [comment]
does it work locally with Debug=False? Also, can you check out this part here http://whitenoise.evans.io/en/stable/django.html#using-whitenoise-in-development to force using whitenoise to serve files?

also, can you produce a complete dump of the settings (with their actual values) locally and in production, both with DEBUG=False? `python manage.py diffsettings --all` might work.

have you tried any of the workarounds in https://github.com/django-compressor/django-compressor/issues/486?

my feeling is this is an incompatibility of django-compressor and whitenoise. especially i'm unsure in which order the respective templatetags are executed, and how having two manifests, one for whitenoise and one for compressor, should work at all. any insights you gain would be appreciated. i would like to help but would need to reproduce that locally...

**Comment by carltongibson** [comment]
Hi @paulnicholsen27 — there's not really enough to go on here. You need to be running `compress` locally and uploading the output to Heroku. 

I don't use Heroku but I've occasionally seen your exception around a deploy — when a page is loading a fresh/stale manifest — essentially an invalidation issue. Maybe something similar occurs with Heroku?

Have a look at #486 and #443 as well as the [Heroku docs on using Django](https://devcenter.heroku.com/articles/getting-started-with-python#introduction). Hopefully you'll find what you need there. 

I'm going to close this as it's not really an actionable issue for compressor. (If you find a way we can improve, we're very happy to take suggestions, and PRs!)

**Comment by karyon** [comment]
@paulnicholsen27 nonetheless i'm interested in helping fixing this. if you find anything that's of interest, please keep me posted.

**Comment by paulnicholsen27** [comment]
Oh my god @carltongibson you gave me the clue--I hadn't been checking in my manifest to git (it was in a gitignore accidentally) and that fixed it.  Thank you all for your help--this has been endless hair pulling.

**Comment by carltongibson** [comment]
@paulnicholsen27 Good result! 👍

I think the underlying difficulty here is the number of moving parts — I don't think there's a **bug** per se. 

What we probably could do with is some kind of check-list in the docs, or such.
