### ISSUE TITLE
Release is not on pypi

### ISSUE THREAD

**Issue by inoks** [django-compressor/django-compressor#832]
Most of automatic tools for package update fails while checking for new version of Django-compressor, like:

>django-compressor 2.1.1                  release is not on pypi (check capitalization and/or --extra-index-url)

PyCharm does not see available release as well.

**Comment by diox** [comment]
It is on PyPI : https://pypi.python.org/pypi/django_compressor/2.1.1

Note that the package is called `django_compressor` with an underscore, not a dash.

**Comment by inoks** [comment]
Installing as `django_compressor` does not resolve that issue:

```
(app)air:src user$ pip install django_compressor==2.1.1
Collecting django_compressor==2.1.1
  Using cached django_compressor-2.1.1-py2.py3-none-any.whl
Requirement already satisfied: rjsmin==1.0.12 in /Users/user/ENV/app/lib/python2.7/site-packages (from django_compressor==2.1.1)
Requirement already satisfied: rcssmin==1.0.6 in /Users/user/ENV/app/lib/python2.7/site-packages (from django_compressor==2.1.1)
Requirement already satisfied: django-appconf>=1.0 in /Users/sergey/ENV/realty/lib/python2.7/site-packages (from django_compressor==2.1.1)
Installing collected packages: django-compressor
Successfully installed django-compressor-2.1.1
```


```
(app)air:src user$ python ./manage.py pipchecker
django-compressor 2.1.1          release is not on pypi (check capitalization and/or --extra-index-url)
```

**Comment by karyon** [comment]
seems to be a bug in django-extensions, i reported it here: https://github.com/django-extensions/django-extensions/issues/1025. no idea about pycharm though. btw pip converts underscores to dashes so using both is fine usually.
