### ISSUE TITLE
Should collectstatic be run before offline compress?

### ISSUE THREAD

**Issue by Sheepzez** [django-compressor/django-compressor#833]
As the title really. I can't see in the documentation if `manage.py compress` does the job of `manage.p collectstatic` implicitly, or if one should be run before the other.

**Comment by carltongibson** [comment]
Hi @Sheepzez, 

`compress` does not run `collectstatic` so a deploy script needs to do both. My playbook for this runs `collectstatic` first, but (IIRC—it's late) compress uses `STATICFILE_FINDERS` so the order shouldn't matter.
