### ISSUE TITLE
Feature request: inline output

### ISSUE THREAD

**Issue by nkuttler** [django-compressor/django-compressor#834]
I'd like to output the styles inline. The sites uses the stock `{% compress %}` tag for normal HTML pages and uses several sass files, but I want to implement [AMP](https://www.ampproject.org/) which [requires](https://www.ampproject.org/docs/get_started/create/presentation_layout) inlining the styles.

While looking at the code I saw that the tag already accepts up to four arguments, one of which is mode, which I thought would control the output. But it looks like the `CssCompressor.output` method doesn't use the mode? If that is just a missing feature I'd be happy to try to implement it myself.

Or did I miss something and there's already a way to do this?

**Comment by diox** [comment]
The `inline` parameter to the template tag works fine for both css and js content. `CssCompressor.output` calls its parent implementation, `Compressor.output`, which calls `handle_output()`, which calls the appropriate method depending on the mode.

**Comment by nkuttler** [comment]
Ah, it seems like the documentation is incorrect.

http://django-compressor.readthedocs.io/en/latest/usage/#examples

`{% compress js inline %}` should be `{% compress js 'inline' %}`

**Comment by diox** [comment]
It's not, `{% compress js inline %}` works fine for me ?

**Comment by nkuttler** [comment]
That's strange, it doesn't for me, and I don't really see why it should, doesn't the template engine interpret `inline` as a variable?

**Comment by diox** [comment]
I added a test to prove that it works fine: https://github.com/django-compressor/django-compressor/commit/3341918060427ede825978ea578b7822c69f87da

**Comment by karyon** [comment]
@nkuttler could you figure out what the problem was?

**Comment by karyon** [comment]
@nkuttler one last ping :) i'd really like to know if you found out anything.
