### ISSUE TITLE
Support custom attributes for (inline) styles

### ISSUE THREAD

**Issue by nkuttler** [django-compressor/django-compressor#839]
I need to add the `amp-custom` attribute to the style tag of inline css for some requests. There are issues that seem related, like #459 and #690. One easy solution for me would be to override the `css_inline.html` template, but I'd need to be able to pass request data into it.

The `{% compress %}` tag is confusing me a bit because of the undocumented (?) third argument `name`, but I think I should be able to modify it to pass data down to the template rendering.

Passing the template context would fix my problem, is that an acceptable approach?

I have seen there is also https://github.com/django-compressor/django-compressor/pull/294/ which looks like it addressed this problem as well.

**Comment by karyon** [comment]
unfortunately i don't know the code well enough and can't say whether that approach is good. you are very much welcome to implement this or take the relevant parts from #294 and make a PR. can you tell me whether this is another use case for the feature requested in #690? in that case i would close it as a duplicate.

**Comment by karyon** [comment]
ping :)

**Comment by nkuttler** [comment]
I ended up hardcoding the attribute into all templates because it's just a little invalid html, and have started a new job. Won't be able to do anything here anytime soon.

**Comment by karyon** [comment]
okay, thanks for the reply. i'll assume this is covered by #690 and close this.
