### ISSUE TITLE
Failed installed on Ubuntu

### ISSUE THREAD

**Issue by arita37** [django-compressor/django-compressor#845]
Hello,

Just wondering if one can do a Conda package since pip install failed on Ubuntu Ananconda...
With this message:

""""
Building wheels for collected packages: rjsmin, rcssmin
  Running setup.py bdist_wheel for rjsmin ... error
  Complete output from command /home/noel/anaconda2/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-VGLcQO/rjsmin/setup.py';f=getattr(tokenize
, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmppV2k7_pip-wheel- --python-tag c
p27:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-2.7
  copying ./rjsmin.py -> build/lib.linux-x86_64-2.7
  running build_ext
  building '_rjsmin' extension
  creating build/temp.linux-x86_64-2.7
  gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DEXT_MODULE=_rjsmin -UEXT_PACKAGE -I_setup/include -I/home/noel/a
naconda2/include/python2.7 -c rjsmin.c -o build/temp.linux-x86_64-2.7/rjsmin.o
  unable to execute 'gcc': No such file or directory
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for rjsmin
"""

Is there a way to install on linux ?
Thanks

**Comment by karyon** [comment]
similar to #807 i think
