### ISSUE TITLE
Cannot find module in windows

### ISSUE THREAD

**Issue by hmercade** [django-compressor/django-compressor#848]
Tested with python 3.5, django 1.11.0 and 1.11.1 and django compressor 2.1.1. This is on windows x64.

The following configuration:
```python
COMPRESS_PRECOMPILERS = (
    ('text/less', 'lesscpy {infile} > {outfile}'),
)
```
raises the following error:

```
Internal Server Error: /
Traceback (most recent call last):
  File "C:\Users\FlanDev\espanda-3.5\lib\site-packages\compressor\base.py", line 260, in precompile
    mod = import_module(mod_name)
  File "C:\Users\FlanDev\espanda-3.5\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'lesscpy {infile} > {outfile}'
```

This is the index.html file
```
   {% compress css %}
        <link rel="stylesheet" href="{% static 'bootstrap/dist/css/bootstrap.min.css' %}">
        <link type="text/less" rel="stylesheet" href="{% static 'panda/less/main.less' %}">
   {% endcompress %}
```

Despite the package lesscpy being installed and in path (I can import it without problems), inside and outside the virtualenv.
It looks to me as it is interpreting the whole string as a package, though this is just a guess.

The same exact thing happens if using lessc instead.

My apologies if this ends up being some mistake on my part during the setup.

**Comment by karyon** [comment]
Are you sure this is the complete stacktrace? because the `mod = import_module(mod_name)` is surrounded by a `try/except (ImportError, TypeError)`, so i would expect the except block to be executed. maybe it's actually about another exception inside that block.

**Comment by karyon** [comment]
ping :)

**Comment by karyon** [comment]
not enough information, closing. if you find anything, respond and i'll reopen!

**Comment by lestrato** [comment]
Hi! I'm getting the same error.
`No module named node_modules/stylus < {infile} > {outfile}`

I suspect that the npm call is being interpreted as calling the file at `node_modules/stylus < {infile} > {outfile}` instead of running the command literally to use the provided `infile` and `outfile` names.

Traceback:
```
env\lib\site-packages\compressor\base.py in precompile

       ...
                return False, content
            raise CompressorError("Couldn't find any precompiler in "
                                  "COMPRESS_PRECOMPILERS setting for "
                                  "mimetype '%s'." % mimetype)
        mod_name, cls_name = get_mod_func(filter_or_command)
        try:
>>>         mod = import_module(mod_name)  <<< The line that errors out !!
        except (ImportError, TypeError):
            filter = CachedCompilerFilter(
                content=content, filter_type=self.resource_kind, filename=filename,
                charset=charset, command=filter_or_command, mimetype=mimetype)
            return True, filter.input(**kwargs)
        try:
```
