### ISSUE TITLE
generate a cache file every time i visit the page

### ISSUE THREAD

**Issue by C1tas** [django-compressor/django-compressor#854]
This is my config 
```
STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    # other finders..
    'compressor.finders.CompressorFinder',
]

COMPRESS_PRECOMPILERS = (
    ('text/coffeescript', 'coffee --compile --stdio'),
    ('text/less', 'lessc {infile} {outfile}'),
    ('text/x-sass', 'sass {infile} {outfile}'),
    ('text/x-scss', 'sass --scss {infile} {outfile}'),
    ('text/stylus', 'stylus < {infile} > {outfile}'),
    ('text/foobar', 'path.to.MyPrecompilerFilter'),
)
```

![](https://django.c1tas.com/pic/orign/23)

a .css file is created as i refresh my django page

how can i make it only generate one file

**Comment by karyon** [comment]
you might have some changing data inside your compress tag. i would need to see your template to help you with this.

**Comment by C1tas** [comment]
```
- load compress
{% compress css %}
link(rel="stylesheet",href="/static/assets/css/wsm/sass/style.scss", type="text/x-scss", charset="utf-8")
{% endcompress %}

```
here is my template

i have use pypugjs 

style.scss
```
body {
    padding-top: 70px;
}

```

**Comment by karyon** [comment]
please check whether this still happens without pypugjs.

**Comment by C1tas** [comment]
yes i change to head.html
```
<head>
{% load compress %}
{% compress css %}
<link rel="stylesheet" href="/static/assets/css/wsm/sass/style.scss" type="text/x-scss" charset="utf-8" />
{% endcompress %}
</head>

```

view
```
def test_html(request):
    return render(request, 'wsm/head.html')

```

it still generate every time i refresh the page

**Comment by karyon** [comment]
my guess would be that the scss-compiler generates different output every time, although i don't know why it should do that. can you verify that by looking what the differences are between those files? you can try to configure the scss-compiler to stop doing that, but it probably makes more sense if you tell django-compressor to not re-compile your scss when the input file hasn't changed using the `CACHEABLE_PRECOMPILERS` setting.

**Comment by C1tas** [comment]
It's my fault.
I add `COMPRESS_ENABLED = True`
and it works well

Thanks for your patient :smiley:

**Comment by karyon** [comment]
alright, glad you found the cause.
