### ISSUE TITLE
Issues with two servers, same code

### ISSUE THREAD

**Issue by iMerica** [django-compressor/django-compressor#855]
Hi,

I have two Heroku Django apps running the same exact code, but with different settings config and I deploy using `git push {app-1} master && git push {app-2} master`. For each deploy, my Procfile release line includes: `python manage.py compress && python manage.py collectstatic --no-input`

This seems to cause some race conditions with Compression keys mismatching (creating `OfflineGenerationError`).

Can someone share some best practices for this? I finished reading the docs for "multi-server" scenarios, but I'm not able to distill anything actionable from it.

Thanks,

Michael

**Comment by karyon** [comment]
could you share what you found?

**Comment by iMerica** [comment]
Hi,

It appears that the issue was not related to my configuration or with Django Compressor, but with Heroku stalling on my release script and not successfully finishing the offline compression phase. 

For reference, the following configuration appears to works totally deterministically and idempotently on a multi-server setup:

## Procfile
```Procfile
release: python manage.py migrate --noinput && python manage.py compress && python manage.py collectstatic --no-input
web:  gunicorn my_app.wsgi:application  --log-file  -
celery: celery worker -A my_app -l info -B  -Q default -n default@%h --without-gossip --without-mingle --without-heartbeat
```
## settings.py 
```py
# Configuration requires boto3, django compressor, collect fast

import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
AWS_S3_CUSTOM_DOMAIN = '<cloudfront-url>'
S3DIRECT_REGION = '<region>'
AWS_PRELOAD_METADATA = True
AWS_S3_OBJECT_PARAMETERS = {
    'CacheControl': 'max-age=86400',
}
COLLECTFAST_THREADS = 20
COLLECTFAST_ENABLED = True
COMPRESS_ROOT = STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
COMPRESS_STORAGE = STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
COMPRESS_OFFLINE = True
STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
)
STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)
COMPRESS_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN
STATIC_URL = COMPRESS_URL
COMPRESS_ENABLED = True
GZIP_CONTENT_TYPES = (
    'text/css',
    'application/javascript',
    'application/x-javascript',
    'text/javascript'
)
COMPRESS_ENABLED = True
COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter',
                        'compressor.filters.cssmin.CSSMinFilter']
# ... other settings
```

Tweak to your liking. YMMV.

Best,

Michael

**Comment by karyon** [comment]
thanks!
