### ISSUE TITLE
compress js not working

### ISSUE THREAD

**Issue by mjdavies** [django-compressor/django-compressor#858]
Hello there

I'm obviously doing something stupid but can't work it out.

Django==1.10.5
django-compressor>=2.1
django-libsass>=0.7

settings.py

```
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)
COMPRESS_ENABLED = True
COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter',  'compressor.filters.cssmin.CSSMinFilter']
COMPRESS_JS_FILTERS = ['compressor.filters.jsmin.JSMinFilter']
```

base.html

```
{% compress js %}
        <script type="text/javascript" src="{% static "js/main.js" %}"></script>
 {% endcompress %}
```

The reference to the javascript disappears from the source of the page template, and there is no js folder created in the CACHE folder like the css folders are created.

Do I need to add a precompiler for js or something?

Any help, greatly appreciated.

**Comment by WoLpH** [comment]
Cross-posting from the stackoverflow question:

My guess would be that you don't have the `COMPRESS_ENABLED` flag set to true. Note that by default it's set to `not DEBUG`: http://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_ENABLED

So, do you have something like `DEBUG = True` in your settings?

**Comment by mjdavies** [comment]
Hi WoLpH

Thanks for getting back.

Yeah we got DEBUG=True and COMPRESS_ENABLED = True

It works fine for css

Should I change one of those settings?

**Comment by diox** [comment]
Please keep general questions like these to stackoverflow, thanks. File an issue if you identify an actual bug with clear steps to reproduce.

**Comment by WoLpH** [comment]
After re-reading your question I see my answer was wrong, you already have `COMPRESS_ENABLED` set to true.

**Comment by mjdavies** [comment]
Sorry diox, my bad.

https://stackoverflow.com/questions/44199032/using-django-compressor-does-not-compress-js
