### ISSUE TITLE
Get invalide value for bootstrap-v4 class 'navbar-toggler-icon'

### ISSUE THREAD

**Issue by changbindu** [django-compressor/django-compressor#864]
When work with the "navbar-toggler-icon" class, the background-image turn out be wrong which lead to the button cannot displayed. The background-image property has been inserted an additional '"'. Below is the compressed result, see the stroke='rgba(0, 0, 0, 0.5")' .

url("data:image/svg+xml;charset=utf8,%3Csvg viewBox='0 0 32 32' xmlns='http://www.w3.org/2000/svg'%3E%3Cpath stroke='rgba(0, 0, 0, 0.5")' stroke-width='2' stroke-linecap='round'

Ref:
http://v4-alpha.getbootstrap.com/examples/starter-template/

```
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
            <button class="navbar-toggler navbar-toggler-right collapsed" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="container main-container">
                <a class="navbar-brand" href="/">xxx</a>
                <div class="navbar-collapse collapse" id="navbarSupportedContent" aria-expanded="false">
                </div>
            </div>
</nav>
```

**Comment by karyon** [comment]
i think this is fixed by #828. until we release a new version, you can use the development branch.
