### ISSUE TITLE
Optimize compress offline loop(s)

### ISSUE THREAD

**Issue by Evelf** [django-compressor/django-compressor#870]
Multiple imbricated loops are needs to generate the compressed files and manifest, but the way it's currently done is wasteful in memory when we have multiple contexts.

With a few meticulous changes, it can be drastically improved, in my benchmarks it goes from \~2942Mb to \~174Mb in memory consumption with no impact on the execution time (\~ 3'15"). See the attached mprofile files.

[mprofile.zip](https://github.com/django-compressor/django-compressor/files/1228841/mprofile.zip)

**Comment by karyon** [comment]
closing, the PR is enough :)
