### ISSUE TITLE
Implement webp support

### ISSUE THREAD

**Issue by lcd1232** [django-compressor/django-compressor#872]
Right now webp [supports](https://caniuse.com/#feat=webp) by Chrome and provide the same quality with smaller size.
You can see comparsion here - https://optimus.keycdn.com/support/png-to-webp/

1. Add offline compress option to generate .webp images from .jpg or .png
2. Add templatetag (or improve current **compress**) `{% compress path/to/photo.png %}` which will be looking for `path/to/photo.webp` if browser send `Accept: ..., image/webp` else using `path/to/photo.png`

**Comment by diox** [comment]
Hi,

Thanks for submitting this feature request, but this is completely out of scope for compressor. Feel free to use more advanced tools for this.
