### ISSUE TITLE
How to use COMPRESS_CLEAN_CSS_BINARY

### ISSUE THREAD

**Issue by jarrekk** [django-compressor/django-compressor#873]
In document we can only see **The clean-css binary filesystem path.**, I am not sure how to config it.

I have installed **cleancss** with `npm install -g clean-css-cli` and in **settings.py**

```
COMPRESS_CLEAN_CSS_BINARY = '/usr/local/bin/cleancss'
COMPRESS_CLEAN_CSS_ARGUMENTS = ''
```

```
COMPRESS_CLEAN_CSS_BINARY = 'cleancss'
COMPRESS_CLEAN_CSS_ARGUMENTS = ''
```

CSS file doesn't become smaller.

**Comment by karyon** [comment]
my guess would be that you need to add `compressor.filters.cleancss.CleanCSSFilter` to `COMPRESS_CSS_FILTERS`. if that does not fix it, i'll have to ask you to post your question to e.g. stackoverflow, since this here is not a support forum.
