### ISSUE TITLE
Offline compression doesn't find templates using sekizai post processor

### ISSUE THREAD

**Issue by timothyshaw** [django-compressor/django-compressor#874]
I recently set up a workflow for a project where the base template only includes sekizai tags, which are then post-processed by django-compressor. It allowed me to get everything down to a single js / css file per request. Eg:

    
    {% render_block "css" postprocessor "compressor.contrib.sekizai.compress" %}

    {% addtoblock "css" %}
      <link type="text/x-scss" href="{{ STATIC_URL }}stylesheets/application.scss" rel="stylesheet" />
    {% endaddtoblock %}

    {% render_block "js" postprocessor "compressor.contrib.sekizai.compress" %}
    
    {% addtoblock "js" %}
      <script src="{{ STATIC_URL }}javascripts/application.js"></script>
    {% endaddtoblock %}

Then in child templates, I add css / js as needed with `{% addtoblock %}`'s.

I started using an autoprefixer css filter which works fine, but last time I deployed, node bogged down the server when autoprefixer was running. In order to make the workflow more efficient I decided to move to offline compression with django-compressor. However, it wasn't finding my templates. After debugging I realized that the offline compression is searching for templates that actually have the `{% compress %}` tag? So it skips templates that have the post-processor style of compressing.

Is it possible to add support for offline compression using postprocessing through sekizai? Or is there something wrong with my setup?

**Comment by karyon** [comment]
i'm afraid it's not supported, see #351. you are welcome to submit a PR, but i cannot say whether it's technically feasible at all.
