### ISSUE TITLE
Add cache file with the same filename

### ISSUE THREAD

**Issue by lcd1232** [django-compressor/django-compressor#877]
Right now every request you got new css file. It's pretty annoying because you need to clear css from time to time. I ask a feature where some files can be generated on the same name, so no need to clear files anymore.
```python
# settings.py
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'sassc {infile} {outfile}'),
)
```
```html
{% compress css %}
<link rel="stylesheet" href="{{ STATIC_URL }}scss/base.scss" type="text/x-scss">
{% endcompress %}
```

**Comment by diox** [comment]
See http://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_CACHEABLE_PRECOMPILERS

**Comment by lcd1232** [comment]
@diox yes I know, but if you read information about this setting:

> An iterable of precompiler mimetypes as defined in COMPRESS_PRECOMPILERS for which the compiler output can be cached based solely on the contents of the input file. This lets Django Compressor avoid recompiling unchanged files. Caching is appropriate for compilers such as CoffeeScript where files are compiled one-to-one, <em>**but not for compilers such as SASS**</em> that have an import mechanism for including one file from another. If caching is enabled for such a compiler, Django Compressor will not know to recompile files when a file they import is modified.

So this setting cannot help in this situation.

**Comment by diox** [comment]
You can't have it both way: either you want django-compressor to do caching, in which case the setting is there, but with that limitation, or you don't :)

**Comment by lcd1232** [comment]
@diox but what the problem to add this feature?
