### ISSUE TITLE
dont try to compress all templates

### ISSUE THREAD

**Issue by kakulukia** [django-compressor/django-compressor#881]
I just posted a bug for django rest framework only to find out its not really their fault.
They prepared a filter for crispy forms, which includes the crispy forms tags, which of cause might not be installed depending on the project. But still the compress command tries to find compress tags in all templates and thus triggers an invalid template exception:

    Invalid template .../site-packages/rest_framework/templates/rest_framework/filters/django_filter_crispyforms.html: 'crispy_forms_tags' is not a registered tag library. Must be one of:

Could that error be fixed by searching differently for templates with a compress tag?

**Comment by carltongibson** [comment]
@kakulukia It's possible... 

We'd have to skip an invalid template here: 

https://github.com/django-compressor/django-compressor/blob/49d303629a3f7d34572a2d00cc2e21e349cfadfc/compressor/management/commands/compress.py#L175-L195

Whether it'd be worth it I'm not sure. As I said on DRF, you're best bet is just to add crispy forms to your INSTALLED_APPS and all will be good. 

(You may think, "but I'm not using crispy forms" — but you are using compressor and DRF, and it seems, currently, there's an implicit dependency when used together there. Do `pip freeze` — there's lots there you have installed for the same reason...)

**Comment by kakulukia** [comment]
hahaa .. now i get you last statement :P
okay, since when using forms i prefer the crispy version anyways, its not much of a deal to add that to the project!

**Comment by aequitas** [comment]
Running into the same issue with django_uwsgi

```
Error parsing template /pyenv/lib/python3.6/site-packages/django_uwsgi/templates/uwsgi/wagtail_uwsgi.html: wagtailadmin/base.html
Invalid template /pyenv/lib/python3.6/site-packages/django_uwsgi/templates/uwsgi/wagtail_dashboard_item.html: 'wagtailadmin_tags' is not a registered tag library. Must be one of:
```

I might get away with it in this case by skipping django_uwsgi during the compress step, but it would be nice if compressor would gain a option to be more lenient about this.
