### ISSUE TITLE
Variables in COMPRESS_OFFLINE_CONTEXT not available to {% extends %} tag

### ISSUE THREAD

**Issue by natevw** [django-compressor/django-compressor#882]
I have a template that inherits from either a "web" or "pdf" base template:

```
{% extends base_template %}

{% block title %}Some document{% endblock %}
{% block body_content %}
…
{% endblock %}
```

Normally the view provides the appropriate path by setting `base_template` in the context for rendering the template. So when I use `./manage.py compress`, I get this error:

```
Error parsing template …/myproject/frontend/templates/frontend/printable.html: Invalid template name in 'extends' tag: ''. Got this from the 'base_template' variable.
```

This is somewhat expected, since I had not yet added any configuration for the offline compression.

However, I still get the same error even after I add this!

```
COMPRESS_OFFLINE_CONTEXT = [
    {'base_template': "frontend/_print_base.html"},
    {'base_template': "frontend/_browser_base.html"},
]
```

It looks like the problem is that [the command](https://github.com/django-compressor/django-compressor/blob/4a8e896c6335134a00759b1d7c3bd9677e0b368a/compressor/management/commands/compress.py) first runs `template = parser.parse(template_name)` raw, and then only later sets up and runs its `for context_dict in contexts` processing based on the parsed nodes!

**Comment by natevw** [comment]
Whoops, first I found a comment in compressor/offline/django.py (django-compressor==2.0):

>    # Note: we pass an empty context when we find the parent, this breaks
>    # inheritance using variables ({% extends template_var %}) but a refactor
>    # will be needed to support that use-case with multiple offline contexts.

But it looks like this has already been fixed on master for a while: https://github.com/django-compressor/django-compressor/commit/c0010bf2ae4064c11cfee2387f6e06c3880fc6d3#diff-01dc27e1db84256620f15d8a69b327ca

Thanks @grzegorzswica for tackling that, and sorry for the noise here!

**Comment by karyon** [comment]
just to make sure, this is included in the latest release :)

**Comment by natevw** [comment]
Yep, I just had to upgrade from 2.0 to version 2.2, thanks!
