### ISSUE TITLE
JS files are minified by default, but CSS files are not

### ISSUE THREAD

**Issue by badbye** [django-compressor/django-compressor#888]
Hi, I am using Django(1.8.2) and django-compressor(2.2). The compressed js works good, however, the css file is not compressed.

Here is part of my template:
```html
{% load staticfiles %}
{% load compress %}
{% compress css %}
<link rel="stylesheet" href="{% static 'landing/style.css' %}" type="text/css"></head>
{% endcompress %}
{% compress js %}
<script src="{% static 'landing/js/jquery.min.js' %}"></script>
<script src="{% static 'landing/js/ads.js' %}"></script>
<script src="{% static 'landing/js/ads.js' %}"></script>
{% endcompress %}
```
It do generate a css file, but it is exactly the same with the original file.

**Comment by karyon** [comment]
please post your settings.py.

**Comment by badbye** [comment]
```python
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'compressor',
)

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

STATICFILES_FINDERS = (
  'django.contrib.staticfiles.finders.FileSystemFinder',
  'django.contrib.staticfiles.finders.AppDirectoriesFinder',
  'compressor.finders.CompressorFinder',
)

COMPRESS_ENABLED = True
COMPRESS_OUTPUT_DIR = 'compress'
STATIC_ROOT = '/home/service/growth/static_file/static'
```

**Comment by karyon** [comment]
css is not compressed by default, see the default setting here: https://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_CSS_FILTERS. i admit it is weird that this is done for js by default and not for css. but we probably won't change that unless we do some release with other major breaking changes.

**Comment by badbye** [comment]
Sorry, I am not familiar with CSS. Should I set the `COMPRESS_CSS_FILTERS` variable to make it work for css? Which option should I use?

**Comment by badbye** [comment]
I see. This line works:
```
COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter', 'compressor.filters.cssmin.rCSSMinFilter']
```

Thank you.

**Comment by karyon** [comment]
i'll leave this open so we can discuss this in case we make such a release.

**Comment by dilyanpalauzov** [comment]
Under these circumstances I please remove rcssmin from setup.py:install_requires and state the current misconception in some obvious place in the documentation, like under 'Usage'.

**Comment by karyon** [comment]
@dilyanpalauzov you are welcome to create a pull request for that, i don't know when i will find the time to do it myself.

**Comment by ekerstein** [comment]
FYI. Just installed django-compressor and ended up here because I expected CSS to be minified as my JS was.

**Comment by Allan-Nava** [comment]
> I see. This line works:
> 
> ```
> COMPRESS_CSS_FILTERS = ['compressor.filters.css_default.CssAbsoluteFilter', 'compressor.filters.cssmin.rCSSMinFilter']
> ```
> 
> Thank you.

But how can I get the min.js or min.css for the compressed files?

**Comment by bittner** [comment]
Any new release in sight that would change the default for (not) minifying CSS?

**Comment by bittner** [comment]
Great! Thank you. :+1: 

Can we expect to see a release anytime soon, so we can use the new default with a version directly off PyPI? That would be helpful.

**Comment by diox** [comment]
Yes, there will be a new release soon (need to do https://github.com/django-compressor/django-compressor/issues/985 and prepare a nice changelog). In the meantime I encourage you to test the `develop` branch to see if it's working for you.
