### ISSUE TITLE
Add option to disable concat

### ISSUE THREAD

**Issue by Nirazul** [django-compressor/django-compressor#890]
I'm trying to use django-compressort exclusively to automatically hash and cache my javascript entry files. I'd like to disable concatenation as I'm separating more stable code such as vendor files from code that's changing more often.

Is there already a way to enable this or do I have to wrap every script file in a separate compress tag?

**Comment by karyon** [comment]
There is no such option as far as i am aware.

you might be able to hack it like this: You could try to `COMPRESS_ENABLES=False` and add a precompiler ([see docs](https://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_PRECOMPILERS)) for `text/javascript`, making django-compressor believe it needs to process (and thus apply the hash) javascript files even when COMPRESS is disabled. The filter would not process the js at all of course, maybe something like `cat {infile} > {outfile}`

but of course, if that works it would disable concatenation for every single file.

**Comment by diox** [comment]
> I'm trying to use django-compressort exclusively to automatically hash and cache my javascript entry files

I would recommend you stay away from compressor then, and just use [django static files storage options](https://docs.djangoproject.com/en/1.11/ref/contrib/staticfiles/#manifeststaticfilesstorage).

**Comment by mzgajner** [comment]
Would you consider re-opening this? I can think of two legit use cases:
- Same case as the OP, but I don't want to just hash+cache, I also want to compress/minify the files, so the suggestion with Django static files storage options isn't enough. HTTP2 is becoming very popular, [concatenation is no longer recommended](https://blog.cloudflare.com/http-2-for-web-developers/#bestpracticesforhttp2weboptimization), so this use case is becoming a very common one (and should provide best performance actually).
- [JS modules](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) are also becoming very popular and they must not be concatenated as you could end up with two occurrences of `export default ...` in a single file. This could be solved by providing an option to manually disable concat, but it'd be even better if `django-compressor` would automatically detect `<script type="module">` and decide not to concat it with others.

**Comment by diox** [comment]
Doing this would likely massively increase compressor's complexity, or at least require a big refactor. Ultimately compressor is a product of its time, and I'm fine with it being obsolete in the modern world.

Django static file storage class can be customized to run some post-processing, so minification can be re-implemented there if you don't need concatenation.

**Comment by mzgajner** [comment]
Totally understandable :). Thanks for the swift response!
