### ISSUE TITLE
Template cached loader results in OfflineGenerationError

### ISSUE THREAD

**Issue by EralpB** [django-compressor/django-compressor#898]
Hello, we are using Django 1.10 and after enabling cached template loader every page I visit gives the following error:

```
compressor.exceptions.OfflineGenerationError: 
You have offline compression enabled but key "xxxxxxxxxxxxxxxxx"
is missing from offline manifest. You may need to run "python manage.py compress".
```

Is this expected? I thought it should work seamlessly, does the hash keys somehow change because of this cached loader?

Additional info:

```
django-compressor==2.1

# This is how I enable:
'loaders': [
                ('django.template.loaders.cached.Loader', [
                    'django.template.loaders.filesystem.Loader',
                    'django.template.loaders.app_directories.Loader',
                    'core.base.loaders.Loader',
                ]),
            ],

# additional settings:

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

COMPRESS_ENABLED = True
COMPRESS_OUTPUT_DIR = '.'
COMPRESS_ROOT = STATIC_ROOT
COMPRESS_STORAGE = 'core.base.storages.LocalCompressorStorage'
COMPRESS_CACHE_BACKEND = 'compressor'
COMPRESS_PRECOMPILERS = [
    ('text/x-scss', 'core.base.precompilers.ScssFilter'),
    ('text/es6+javascript', 'core.base.precompilers.BabelFilter'),
    ('text/jsx+javascript', 'core.base.precompilers.BabelJsxFilter'),
]
COMPRESS_CSS_FILTERS = [
    # 'compressor.filters.cssmin.rCSSMinFilter',
    'core.base.precompilers.PostCssFilter',
]
COMPRESS_JS_FILTERS = [
    'compressor.filters.jsmin.JSMinFilter',
]
```

I've a duplicate question at https://stackoverflow.com/questions/48922346/django-cached-template-loader-offlinegenerationerror

**Comment by karyon** [comment]
this is certainly not expected, especially since the cached loader is the default since django 1.11.

are you sure that enabling the cached loader is causing the issue?

in the settings you posted i don't see any COMPRESS_OFFLINE, i suppose you have set that to true somewhere? and you have called `manage.py compress` like the error message says?

please try reducing the example e.g. by removing your custom loaders and precompilers.

i'm sure you are aware but still: please be aware that django 1.10 is EOL for three months already and you likely have known and unpatched security holes in your software.

**Comment by EralpB** [comment]
Thank you for the great reply, I will try to collect more information and come back. It is hard to pin down the issue as we have a very big codebase, but it's good that at least this fails on staging so I can experiment more.
I also was quite confident this wouldn't fail as you said this is default on Django 1.11.
I haven't done `manage.py compress` because I don't want to just run commands, I can run it though it this was expected that the caching loader somehow changes the signatures of the templates.. :)

Anyway thanks again!

**Comment by karyon** [comment]
you need to run `manage.py compress` if you have `COMPRESS_OFFLINE = True`. If you have not set that, then you shouldn't need to run `manage.py compress`, and also shouldn't see that error. see https://django-compressor.readthedocs.io/en/latest/usage/#offline-compression

**Comment by karyon** [comment]
have you found out anything?

**Comment by karyon** [comment]
not enough information and no reply, closing. let us know if you have found out anything!
