### ISSUE TITLE
Too big folder static/CASHE/js, more then 1 500 000 files. wtf?

### ISSUE THREAD

**Issue by dE1l** [django-compressor/django-compressor#902]
I have 8 GB, 1 500 000 same file in folder CACHE/js, why? How can i fix it? May be i need some settings?

django-compressor 2.2

-rw-rw-rw-  1 uwsgi  www   593B 20 марта 08:32 00000d68bb1d.js
-rw-rw-rw-  1 uwsgi  www   593B 16 марта 10:38 000012af0f8b.js
-rw-rw-rw-  1 uwsgi  www   593B 25 янв.  08:47 00004dc38d82.js
-rw-rw-rw-  1 uwsgi  www   593B  2 марта 16:15 0000841be19e.js
-rw-rw-rw-  1 uwsgi  www   593B  3 февр. 11:44 0000aad3800d.js
-rw-rw-rw-  1 uwsgi  www   593B 15 марта 09:03 0000ac3306cc.js
-rw-rw-rw-  1 uwsgi  www   593B  2 марта 18:21 00010e772e0b.js
-rw-rw-rw-  1 uwsgi  www   593B 23 февр. 13:37 00010f3deaf0.js
-rw-rw-rw-  1 uwsgi  www   593B 15 марта 10:33 0001255d7221.js
-rw-rw-rw-  1 uwsgi  www   593B 25 янв.  21:20 00018eef6e26.js
-rw-rw-rw-  1 uwsgi  www   593B 10 февр. 14:20 0001a9d6b92f.js
-rw-rw-rw-  1 uwsgi  www   593B 15 марта 05:21 0001d9d8600b.js
-rw-rw-rw-  1 uwsgi  www   593B  1 февр. 01:51 000224a371f7.js
-rw-rw-rw-  1 uwsgi  www   593B 27 янв.  05:34 00022a4d564e.js
-rw-rw-rw-  1 uwsgi  www   593B 11 марта 22:34 000249457c63.js
-rw-rw-rw-  1 uwsgi  www   593B 17 марта 03:46 0002627cdf5c.js
-rw-rw-rw-  1 uwsgi  www   593B 27 февр. 21:11 00026e1635a9.js

**Comment by karyon** [comment]
check whether you have any part in your template inside the {% compress %} block which might cause django-compressor to think it needs to re-generate that file.

if that does not help, you can try asking this on e.g. stackoverflow, but please include some more information :) at least your settings, and the template in question.

**Comment by dE1l** [comment]
it was problem with always generating {{ csrf_token }} in ajax. I must be used csrf_token from cookie

https://docs.djangoproject.com/en/2.0/ref/csrf/
