### ISSUE TITLE
Access Denied - CSS

### ISSUE THREAD

**Issue by pythoncreate** [django-compressor/django-compressor#905]
Just started using django compressor along with my AWS/Cloudfront setup on Heroku.

Having an issue where the compressed CSS is not loading for the page and when i view the source:

https://d3dycr1vdfv0cd.cloudfront.net/static/CACHE/css/50c1fe094e5d.css

its showing as access denied. 

any ideas?

**Comment by pythoncreate** [comment]
and same issue on the JS compression

**Comment by karyon** [comment]
well, that is not the output of django-compressor, but comes from your server provider. there's nothing we can do about that i think :) you can of course customize the output directory of django-compressor via the settings, if that helps.
