### ISSUE TITLE
Cannot compress external sources

### ISSUE THREAD

**Issue by demonno** [django-compressor/django-compressor#906]
## Example

```html
<script src="https://www.google.com/recaptcha/api.js" async defer></script>
````
## Command

    python manage.py compress --force

## Error 
    CommandError: An error occurred during rendering 
    'https://www.google.com/recaptcha/api.js' isn't accessible via COMPRESS_URL ('/static/') and can't be compressed

-----

The issue could be fixed if it was possible to define a block which will be ignored by `django-compressor`

**Comment by karyon** [comment]
i don't quite understand, the message correctly states that this file can't be compressed. the issue can be fixed by not trying to compress it by moving that line out of the `{% compress %}` block.

let me know if i misunderstood you and i'll reopen.
