### ISSUE TITLE
Update Pip Install command

### ISSUE THREAD

**Issue by scblur** [django-compressor/django-compressor#907]
The in-development version of Django Compressor can be installed with pip install http://github.com/django-compressor/django-compressor/tarball/develop.

The above command is not working and it's showing an error like this,
 Cannot unpack file /tmp/pip-unpack-_o51wqz5/develop.htm (downloaded from /tmp/pip-req-build-9werb_uw, content-type: text/html); cannot detect archive format
Cannot determine archive format of /tmp/pip-req-build-9werb_uw

Therefore, i tried the following command and it worked:
pip install git+https://github.com/django-compressor/django-compressor.git

**Comment by karyon** [comment]
that's the first time i see this approach, is there any documentation of anything that suggests the first way should work? I mean, it's a tarball generated by github, and it's not necessarily meant to be consumed by pip.

**Comment by karyon** [comment]
it *is* mentioned in our very own `README.rst`. thanks for reporting!
