### ISSUE TITLE
Deploying on Heroku just doesn't work

### ISSUE THREAD

**Issue by typistX** [django-compressor/django-compressor#913]
I'm at my wits-end as to the cause of my 500 Internal server error. Here's the traceback email I get:

> UncompressableFileError at /
> 'stylesheets/bootstrap.2cf288023762.scss' could not be found in the COMPRESS_ROOT '/static/artist_notify/sass' or with staticfiles.
> 
> Request Method: GET
> Request URL: http://namedomain.io/
> Django Version: 1.11.6
> Python Executable: /app/.heroku/python/bin/python
> Python Version: 3.6.5
> Python Path: ['/app', '/app', '/app/.heroku/python/lib/python36.zip', '/app/.heroku/python/lib/python3.6', '/app/.heroku/python/lib/python3.6/lib-dynload', '/app/.heroku/python/lib/python3.6/site-packages', '/app']
> Server time: Sat, 23 Jun 2018 22:25:22 +0300
> Installed Applications:
> ['core',
>  'accounts',
>  'notifications',
>  'faq',
>  'tinymce',
>  'dal',
>  'dal_select2',
>  'registration',
>  'django.contrib.admin',
>  'django.contrib.auth',
>  'django.contrib.contenttypes',
>  'django.contrib.sessions',
>  'django.contrib.messages',
>  'django.contrib.staticfiles',
>  'debug_toolbar',
>  'django_extensions',
>  'compressor',
>  'widget_tweaks',
>  'crispy_forms',
>  'channels']

Each time it's a slightly different file.

I set `heroku config:set DEBUG_COLLECTSTATIC=1` and it reported no errors:

```
remote: -----> $ python manage.py collectstatic --noinput
remote:        Found another file with the destination path 'admin/js/jquery.init.js'. It will be ignored since only the first encountered file is collected. If this is not what you want, make sure every static file has a unique path.
remote:        2065 static files copied to '/tmp/build_ad58ca3708156d7b52e9b35a7432aeee/staticfiles', 2173 post-processed.
```

As far as I know, I've got my settings structure just the way it's supposed to be:

```
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
    os.path.join(BASE_DIR, "static/artist_notify/sass/"),
)

STATICFILES_FINDERS =  [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
    'compressor.finders.CompressorFinder',
]

# SASS
COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

# STATIC ROOT
COMPRESS_ROOT = os.path.join(BASE_DIR, 'static/artist_notify/sass/')

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
```

I can't figure out what's causing this error.

**Comment by karyon** [comment]
have you checked this thread? https://github.com/django-compressor/django-compressor/issues/486

to me it looks like trying to deploy on heroku without offline compression is a non-starter, unfortunately.

**Comment by typistX** [comment]
That's a huge bummer. But anyway I've enabled Offline Compressing and now it complaints about something different.

> You have offline compression enabled but key "441007481f554f1ae783d2d9c33448c3" is missing from offline manifest. You may need to run "python manage.py compress".

But when I run that I get:

```
Invalid template /app/accounts/templates/registration/password_change_form.html: Invalid filter: 'attr'
Found 'compress' tags in:
        /app/accounts/templates/registration/login.html
        /app/templates/tos.html
        /app/templates/facebook_import.html
        /app/templates/spotify_import_menu.html
        /app/accounts/templates/email_change_result.html
        /app/templates/pending_additions_index.html
        /app/templates/admin_stats.html
        /app/templates/artist_results.html
        /app/accounts/templates/registration/activate.html
        /app/accounts/templates/change_password.html
        /app/accounts/templates/delete_account.html
        /app/templates/base.html
        /app/templates/lastfm_import_menu.html
        /app/accounts/templates/registration/password_reset_confirm.html
        /app/accounts/templates/registration/password_reset_done.html
        /app/accounts/templates/registration/registration_form.html
        /app/accounts/templates/registration/registration_complete.html
        /app/templates/faq.html
        /app/accounts/templates/registration/logout.html
        /app/templates/add_artist.html
        /app/accounts/templates/change_email.html
        /app/templates/releases_for_artist.html
        /app/accounts/templates/registration/password_reset_complete.html
        /app/templates/dashboard.html
        /app/accounts/templates/registration/registration_closed.html
        /app/accounts/templates/registration/password_change_done.html
        /app/accounts/templates/registration/activation_complete.html
        /app/templates/artists_for_user.html
        /app/accounts/templates/user_profile.html
        /app/accounts/templates/registration/password_reset_form.html
CommandError: An error occurred during rendering /app/accounts/templates/registration/login.html: 'stylesheets/bootstrap.2cf288023762.scss' could not be found in the COMPRESS_ROOT '/app/static/artist_notify/sass' or with staticfiles.

```

Which I don't understand at all

**Comment by typistX** [comment]
Now `manage.py compress` returns no errors. But I still get this error (traceback email after 500 internal server error):

> Internal Server Error: /
> 
> OfflineGenerationError at /
> You have offline compression enabled but key "441007481f554f1ae783d2d9c33448c3" is missing from offline manifest. You may need to run "python manage.py compress".

Stuck in a loop. Totally stumped.

**Comment by karyon** [comment]
does offline compression run locally for you? also, if you post the template in question that might help.

**Comment by typistX** [comment]
Strange, but a git push heroku master -f worked. I'm not even sure what was wrong.

**Comment by karyon** [comment]
i'm glad you were able to fix it!
