### ISSUE TITLE
module "compressor.storage" does not define a "brotlicompressorfilestorage" attribute/class

### ISSUE THREAD

**Issue by evilplanet** [django-compressor/django-compressor#914]
I'm using offline compression in conjunction with whitenoise on heroku and everything works fine before I overrode `COMPRESS_STORAGE` to enable broli compression as below:

```
INSTALLED_APPS += ['compressor', ]
STATICFILES_FINDERS += ['compressor.finders.CompressorFinder',]
COMPRESS_STORAGE = 'compressor.storage.BrotliCompressorFileStorage'
COMPRESS_ENABLED = env.bool('COMPRESS_ENABLED', default=True)
COMPRESS_OFFLINE = env.bool('COMPRESS_OFFLINE', default=True)
```

I have `brolipy` installed and added to requirements.txt.

But django-compressor gives me this error message: 

`module "compressor.storage" does not define a "BrotliCompressorFileStorage" attribute/class`

**Comment by evilplanet** [comment]
Any idea why? The spelling seems correct. I checked the source code, and there is indeed a class named `BrotliCompressorFileStorage` in the `compressor.storage` module.

**Comment by evilplanet** [comment]
I switched to `gzip`, and now it works. This seems to be a bug.

**Comment by karyon** [comment]
the brotli storage is not contained in the latest release yet, so unless you installed the develop branch, you won't have that. our readthedocs page is unfortunately unclear about the versions, i opened #915 for that.

closing, assuming that was the issue. if not, please let me know :)
