### ISSUE TITLE
ReadTheDocs opens 'latest' by default, not 'stable', plus other issues

### ISSUE THREAD

**Issue by karyon** [django-compressor/django-compressor#915]
`stable` would make more sense in my opinion, since that is what people will use by default. probably led to #914.

additionally, i think it's weird that when opening `latest`, it still says "Django Compressor 2.2 Documentation', not `develop`.

Also, it's weird that there is both `latest` and `develop` in the version selector.

Also, versions after 1.3 are missing from the version selector. When accessing them by typing the version number into the url manually, i get a 403.

**Comment by jezdez** [comment]
Added @diox and you (@karyon) to the RTD project. Apologies for having missed that. Let me know if you need any help or info abouut the RTD setup.

**Comment by karyon** [comment]
thanks!

fwiw, i fixed most of the issues i listed, except it still says "Django Compressor 2.2 Documentation" when opening "latest". i guess we could fix that by setting our current version to 2.3dev or something like that, but oh well.
