### ISSUE TITLE
Improve the html output of django-compressor

### ISSUE THREAD

**Issue by geoffroy-noel-ddh** [django-compressor/django-compressor#916]
Although not strictly invalid, the format of the html generated by django-compressor could be improved to meet best practices in Html 5 web design.

For *JS* it adds `type="text/javascript"` which is now unnecessary (and it comes up as a warning when running the code through W3C validator).

For *CSS* it still outputs XHTML tags rather than HTML `/>` which could mix up how the browser reads the document (it passes W3C though).

**Comment by diox** [comment]
XHTML style tags with `/>` are valid HTML5 on void elements - browsers deal with it just fine. I agree both that slash and the `type` attribute on the `<script>` are not necessary, but I don't think it matters either... If that bothers you you can try submitting a pull request, or just changing the templates in your own django project.

**Comment by karyon** [comment]
https://github.com/django-compressor/django-compressor/pull/931 seems to fix exactly this.

**Comment by karyon** [comment]
fixed in #952.
