### ISSUE TITLE
Can't make css compression works with 'COMPRESS_FILTERS' setting variable

### ISSUE THREAD

**Issue by laurentbetti** [django-compressor/django-compressor#918]
I have v 2.2 and I cannot make compression works (i.e. pass filters of my choice to the compression process) by setting the `COMPRESS_FILTERS` variable in my settings.py as follows:

    COMPRESS_FILTERS = {
         'css': [
             'compressor.filters.cssmin.CSSMinFilter'
         ]
     }

Whereas it works just fine by setting the `COMPRESS_CSS_FILTERS` variable as follows:

    COMPRESS_CSS_FILTERS = [
        'compressor.filters.cssmin.CSSMinFilter'
    ]

Any clue of why this is happening ?

**Comment by karyon** [comment]
this is only in the development branch, not the 2.2 release. unfortunately, readthedocs automatically redirects to "latest", even though i have set "stable" to be the default...
