### ISSUE TITLE
Cache JS filter output across runs of the compress command

### ISSUE THREAD

**Issue by davidfstr** [django-compressor/django-compressor#921]
It appears that if I run `python3 manage.py compress` multiple times that it will repeatedly run the same imported JS files through the COMPRESS_JS_FILTERS even if they haven't been changed between calls to compress.

I would expect that if the input .js files did not change between calls that the compress command should avoid rerunning the filter and should instead use the same output as last time.

The lack of caching that I currently observe is not much a problem for the default JS filter (JSMinFilter) because that filter is extremely fast. However if I switch to a slower filter such as ClosureCompilerFilter then these repeated refilterings take a lot of time.

A few questions:

1. Am I correct in observing this current lack of caching behavior? (Or did I mess up in my instrumentation somewhere?)

2. Is there any known issue preventing this caching behavior from being introduced? (If not then I might propose a change to introduce such behavior.)

**Comment by diox** [comment]
Hi,

There should be some caching if you have a cache backend defined in django. See https://django-compressor.readthedocs.io/en/latest/behind-the-scenes/ for more information about how compressor works behind the scenes and https://django-compressor.readthedocs.io/en/latest/settings/#caching-settings for more documentation about the caching settings.

Do you have some precompilers maybe ? If so you'll need to look at [`COMPRESS_CACHEABLE_PRECOMPILERS`](https://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_CACHEABLE_PRECOMPILERS) but be aware of the drawback documented there.

**Comment by davidfstr** [comment]
I have a cache backend defined (Redis) and no precompilers, so there must be something I'm missing. I am running Django Compressor 2.1 rather than the latest stable 2.2 but I doubt that makes a difference.

Since it sounds like there is the intent to perform the caching behavior I described, there must be something wrong with my setup. I'll withdraw this issue for now.

**Comment by davidfstr** [comment]
Actually it looks like there might be a problem.

I believe I found the code that tries to check the cache: CompressorMixin.render_compressed() will try to check the cache if (settings.COMPRESS_ENABLED and not forced).

However `compressor/offline/django.py`'s DjangoParser.render_node() function always calls render_compressed() with forced=True. That is, it appears to always force the rerender, ignoring the cache. Thoughts?

**Comment by diox** [comment]
Sorry, I read your initial post too quickly and somehow missed the fact that you were actually running `compress`. Then it's by design, yes, although to be honest I don't remember why exactly (I don't use compressor day-to-day anymore)

**Comment by davidfstr** [comment]
Hmm. Well, it's unlikely that I'll have time to investigate further.

I'm planning to workaround by just sticking with JSMinFilter and ES2015 and give up on JS template strings for now, which JSMinFilter doesn't understand. :(
