### ISSUE TITLE
How add purifycss after compress?

### ISSUE THREAD

**Issue by lioshi** [django-compressor/django-compressor#924]
I search to add purifycss (https://github.com/purifycss/purifycss) at compressor works.
After offline compress I want to launch a purifycss command like this
`purifycss compressed_file.js compressed_file.css html_content_parsed --out compressed_file.css`
and then the compressed_file.css is rewrite with purified css...

How make that? An idea? 
Another external command after compressor? 
A custom filter for compressor? 
Is there a way in a custom compressor filter to get html parsed content and js compressed file content?

Thanks

**Comment by karyon** [comment]
i don't think that's possible with django-compressor, sorry.
