### ISSUE TITLE
OfflineGenerationError key missing from manifest.

### ISSUE THREAD

**Issue by xirdneh** [django-compressor/django-compressor#927]
I'm using django-compressor 2.2 and Django 1.11.15
I have a base template like so:
```html
{% load compress %}
<html>
<head>
    {% compress css %}
        {% block styles %}
        {% endblock styles %}
    {% endcompress %}
</head>
<body>

{% compress js %}
    <script src="require.js"></script>
    <script src="common.js"></script>
{% endcompress %}
<!-- Some other stuff -->
{% compress js %}
    {% block scripts %}
    {% endblock scripts %}
{% endcompress %}
</body>
</html>
```
And then I have another template like so:
```html
<!-- my_template.html -->
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <!-- stuff -->
{% endblock %}

{% block scripts %}
<script src="{% static 'js/app/script.js' %}"></script>
{% endblock scripts %}
```
When I run `python manage.py compress` I do see `my_template.html` in the list of files where compress tags appear but when the template is rendered I get the `OfflineGenerationError` where a key is missing from the manifest. 
I tried removing the `manifest.json` file and running `python manage.py compress` directly in production with no luck.
I can also do a `grep` on the files created by compress and I can see the javascript that's supposed to be compressed and cached there. So, seems like compress is doing its job but the manifest is not being updated correctly.
Any idea how to fix this?
Thanks.

**Comment by xirdneh** [comment]
@diox @karyon Any idea how to fix/debug this?
Thanks.

**Comment by xirdneh** [comment]
This was my bad. Apparently I was using a django app which modifies a static file path but it doesn't work within the context that `./manage.py compress` runs.
I've created a pull request that prints enough information to debug, hopefully, all of this `OfflineGenerationError`: https://github.com/django-compressor/django-compressor/pull/928

**Comment by karyon** [comment]
thanks for checking back and for the PR! i'll look into it, but i can't say when :)
