### ISSUE TITLE
please update dep on r{css,js}min

### ISSUE THREAD

**Issue by costela** [django-compressor/django-compressor#930]
hi,

[rjsmin's latest release](https://pypi.org/project/rjsmin/1.1.0/#files) now includes a wheel package. It would be nice to be able to make use of it :wink:

Cheers

**Comment by diox** [comment]
Hi,

We take pull requests :wink:

**Comment by costela** [comment]
ok, ok, you got me! PR incoming! :grin:

**Comment by costela** [comment]
FYI: I'll wait a bit for ndparker/rcssmin#10 and update both deps at once.

**Comment by ant6** [comment]
Rjsmin now fixed installation fails when c extensions unavailable https://github.com/ndparker/rjsmin/issues/7 so that's a great addition too :)

**Comment by karyon** [comment]
since rcssmin still doesn't have any release, and rjsmin got updated in #936, i'll close this. thanks for the reports!
