### ISSUE TITLE
Please release new version

### ISSUE THREAD

**Issue by jrief** [django-compressor/django-compressor#939]
I already asked this half a year ago, the issue was closed and we still go with version 2.2.
If you don't have enough time to do so, consider to hand over this project to [JazzBand](https://github.com/jazzband).

**Comment by karyon** [comment]
As stated then, please use the development branch if need be. Also please refrain from opening further issues on this matter. Handover to JazzBand was discussed [here](https://github.com/jazzband/roadies/issues/111), pip releases are the one thing that wouldn't be handed over.
