### ISSUE TITLE
Can we have a new release?

### ISSUE THREAD

**Issue by adamzap** [django-compressor/django-compressor#940]
The latest version of `django-compressor` on PyPI (v2.2) was released in August 2017. It'd be great to get latest changes in a new release, especially #861.

Is there anything I can do to help get a new release out, or does it just need to be cut and uploaded?

Thanks for `django-compressor`! It's a big help.

**Comment by diox** [comment]
It needs to be tested, cut, a changelog written, and uploaded. I might have time to take care of most of that tomorrow, I'd appreciate if anyone wanting a new release would test the develop version in the meantime.

**Comment by adamzap** [comment]
That's a very fair request. I'll see what we can do!

Thanks so much!

**Comment by adamzap** [comment]
I'm not finding any issues in our use case on the `develop` branch. We can talk on over email or in another non-public way if you want more information about my setup.

**Comment by diox** [comment]
2.3 is now live on pypi: https://pypi.org/project/django-compressor/2.3/
Changelog is https://django-compressor.readthedocs.io/en/latest/changelog/#v2-3-2019-06-31

Let me know if you run into any problems.
