### ISSUE TITLE
Key exists in manifest but compressor can't see it ?

### ISSUE THREAD

**Issue by v9Chris** [django-compressor/django-compressor#943]
We're getting a manifest key missing error but I can see the key in the manifest.

Error
```
  File "/usr/local/lib/python3.5/site-packages/compressor/templatetags/compress.py", line 81, in render_offline
    'is the original content:\n\n%s' % (key, original_content))
compressor.exceptions.OfflineGenerationError: You have offline compression enabled but key "b38adbbca009d1853fc402dad46de0db7bdc629d6ff49845b1a9e82e94a4f211" is missing from offline manifest. You may need to run "python manage.py compress". Here is the original content:
```
  
Manifest
```
  "b38adbbca009d1853fc402dad46de0db7bdc629d6ff49845b1a9e82e94a4f211": "<link rel=\"stylesheet\" href=\"/__compressor_url_placeholder__/CACHE/css/output.c7eb864ea3e5.css\" type=\"text/css\" />"
```
  
Any idea why it wouldn't be able to see the key? Have tried messing with every setting under the sun that I'm aware of but still no change.

**Comment by karyon** [comment]
thanks for reporting. no sorry, i have no idea. you'd need to provide more information like all the settings, the template, and the full manifest. does offline compression not work for you at all or is there a scenario where it does work for you? what's the actual location of your manifest? does the server have read access to it?

**Comment by Krolken** [comment]
You don't happen to be using AWS Lambda? I am having a similar issue when using AWS lambda and django-storages with zappa.
Must be something in the execution environment of AWS Lambda because it works fine when I am running locally using the remote s3 bucket.

**Comment by karyon** [comment]
not enough information, closing.

I'd be happy to reopen it though!

**Comment by ecolss** [comment]
Same error, but on Gcloud App engine.

Django-compress worked correctly on my local dev-server, since I can see the static files' url has `CACHE` in it on local dev-server.
But when deployed to Gcloud, it failed with the above error.

**Comment by Navaneeth-Sharma** [comment]
Hi, I have facing similar issue.. Any solutions yet ?
Thanks
