### ISSUE TITLE
Compressor doesn't support defered css

### ISSUE THREAD

**Issue by pkqxdd** [django-compressor/django-compressor#944]
When I put 
```html
{% compress css %}
<link rel="preload" href="{{ static('home.css') }}" as="style" onload="this.rel='stylesheet'">
 {% endcompress %}
```
the line disappeared from the output html. I'm using jinja2 as the template language. Is there any way to work around this?

**Comment by diox** [comment]
Hi,

Set the `rel` attribute on your `<link>` normally and use the actual attribute meant for this, `defer`, instead of a javascript hack.
