### ISSUE TITLE
ImportError: No module named 'sass_processor'

### ISSUE THREAD

**Issue by miguelgavilan** [django-compressor/django-compressor#948]
Hi! I'm following the instructions in readme, I've succesfully installed django-sass-processor with pip, I'm trying to run server and getting the following error:

 ImportError: No module named 'sass_processor'

I'm using docker but i don't know if that's the problem.

That is my pip freeze:

> certifi==2019.3.9`
dj-database-url==0.5.0
Django==2.0.6
django-appconf==1.0.3
django-compressor==2.3
django-heroku==0.3.1
django-model-utils==3.1.2
django-sass-processor==0.7.3
gunicorn==19.9.0
libsass==0.19.2
pipenv==2018.11.26
psycopg2==2.7.7
pytz==2018.9
rcssmin==1.0.6
rjsmin==1.1.0
six==1.12.0
virtualenv==16.4.0
virtualenv-clone==0.5.1
whitenoise==4.1.2

**Comment by karyon** [comment]
i think you are referring to the instructions of django-sass-processor? I suggest you create a bug report there.
