### ISSUE TITLE
Defer Async script attributes doesn't apply.

### ISSUE THREAD

**Issue by trunkovich** [django-compressor/django-compressor#955]
As I understand it should work after this MR: https://github.com/django-compressor/django-compressor/pull/454/files

But we're still missing documentation. All my tries to make it work was unsuccessful. 
Here is my usage example: 
```
{% compress js %}
    <script type="text/javascript" defer src="{% static 'vendor/jquery/dist/jquery.js' %}"></script>
    <script type="text/javascript" defer src="{% static 'js/vendor/v1/libs/fancybox.js' %}"></script>
    <script type="text/javascript" async src="{% static 'js/vendor/v1/libs/jquery.mousewheel.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/v1/helpers/tabs.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/vendor/v1/helpers/dropdown.js' %}"></script>
{% endcompress %}
```
As a result we have all scripts combined into one without async/defer attribute.
I've also tried to split it into several files, based on attribute, but it doesn't help.

**Comment by karyon** [comment]
could you check what happens with the code in this unit test? https://github.com/django-compressor/django-compressor/blob/develop/compressor/tests/test_base.py#L337

could you create a unit test that demonstrates the problem?

**Comment by trunkovich** [comment]
@karyon It looks like it was version issue. After updating compressor to `2.3` version - it starts working.

**Comment by karyon** [comment]
thanks for reporting back!
