### ISSUE TITLE
Why is COMPRESS_CACHE_BACKEND still used with offline cache?

### ISSUE THREAD

**Issue by joriskoris** [django-compressor/django-compressor#970]
I may just not understand how things work behind the scenes, so if that's the case, please someone explain.

Anyways, it seems that when generating offline cache with `python manage.py compress` command, django-compressor still tries to connect to whatever default cache backend that is specified and throws a "connection refused" error if the backend (say redis) is unavailable at the time.

Is this intended, or am I completely off about the usecase?

Thanks!

**Comment by diox** [comment]
It's intended. Some people actually rely on this without actually using offline compression, to "prime" their cache. You can set a dummy cache backend if that bothers you.
