### ISSUE TITLE
[js] associated array compression error

### ISSUE THREAD

**Issue by rivmar** [django-compressor/django-compressor#974]
Hi.
a'm getting error 
> Uncaught SyntaxError: Unexpected token ':'
 if my javascript code contains associated array even in the simplest case:
`{% compress js %}<script>{"hello":"there"}</script>{% endcompress %}`
I use compressor version 2.3
Thank you.

**Comment by karyon** [comment]
This is indeed invalid syntax, you probably want `{hello:"there"}`. An easy way to check this is the javascript console of your favorite browser.

**Comment by rivmar** [comment]
This syntax works without compression. And in console it works too.
