### ISSUE TITLE
compress produces different results on different machines

### ISSUE THREAD

**Issue by drozdowsky** [django-compressor/django-compressor#975]
Running `compress` on the same codebase on two different machines produces different compressed static files (file names are not the same between machines). 
We use `compressor.cache.simple_cachekey'`, why is that?
We would like to run compress on both machines and avoid rsync.

**Comment by diox** [comment]
This is not a support forum, please head over stackoverflow or similar for questions. There are various things that could cause this depending on your setup, it's hard to say without knowing what settings you're using, so please have a look at the docs. It could be https://django-compressor.readthedocs.io/en/latest/settings/#django.conf.settings.COMPRESS_CSS_HASHING_METHOD
