### ISSUE TITLE
`Extends` tag offline processing fails on relative paths

### ISSUE THREAD

**Issue by kdickerson** [django-compressor/django-compressor#979]
Django 1.10 introduced relative paths for the `extends` tag, for example `{% extends '../base.html' %}`.  These fail to resolve during offline compression and `compress` catches a `TemplateDoesNotExist` exception at line 201 of `management/commands/compress.py`.

The reported path appears to be correct except that it isn't written absolutely (note that the first path starts with `/` while the failing 2nd path does not):

```
# my_app/templates/my_app/_base.html
....

# my_app/templates/my_app/show.html
{% extends './_base.html' %}
....

# compress-command error logging
Error parsing template /home/kdickerson/Code/my_project/my_app/templates/my_app/show.html: home/kdickerson/Code/my_project/my_app/templates/my_app/_base.html
```

It works correctly if I replace the relative path with a relative-to-template-loader-root path: `{% extends 'my_app/_base.html' %}`

**Comment by karyon** [comment]
thanks for the report! while i won't be able to fix this myself anytime soon, we take PRs :)

**Comment by kdickerson** [comment]
Whoops, mis-clicked - sorry, kids running around being crazy!

**Comment by kdickerson** [comment]
Here's what I've learned: Django's calculation of relative template paths is done in [loader_tags.py:construct_relative_path](https://github.com/django/django/blob/master/django/template/loader_tags.py#L220) which actually works off of a template `name` rather than a `path`.  The `name` is the relative-to-template-loader path to the template.  That is, it constructs a new relative-to-template-loader path based on the existing relative-to-template-loader path.  (This is the `template_name` property on the `Origin` instance within the `parser`.)

In my above example, I may have a `TemplateView` which sets `template_name = 'my_app/show.html'`.  When `construct_relative_path` is executed, the value of `current_template_name` is `my_app/show.html` (the value of `origin.template_name`) and not `/home/kdickerson/Code/my_project/my_app/templates/my_app/show.html` (the value of `origin.name`).

Django-Compressor, however, is looking for templates manually and finds them all by absolute filesystem path and doesn't know what their relative-to-template-loader paths are (so `origin.name` and `origin.template_name` are the same).  This happens in [compress.py:compress](https://github.com/django-compressor/django-compressor/blob/master/compressor/management/commands/compress.py#L106).  So when it reaches the extends tag in the template it sends the full filesystem path to `construct_relative_path` and it fails.

I believe the most localized fix would involve finding someway for Django-Compressor to generate relative-to-template-loader paths to pass to `parser.parse(template_name)` on line 168.  I will investigate this next week.  I wanted to get that captured while it was all in my head before taking off for the weekend.

**Comment by kdickerson** [comment]
I have a one-line fix for this with a few more lines for tests.  But, I'll need to jump through a corporate software-release process before I can submit the PR though.

**Comment by karyon** [comment]
@kdickerson it would be great to get that in!

**Comment by kdickerson** [comment]
Almost done being reviewed.  My group has never gone through the process before, so it's taking a little while longer than I expected.

**Comment by cclauss** [comment]
* Riverside-Healthcare/djLint#722
