### ISSUE TITLE
Deprecate COMPRESS_*_FILTERS settings

### ISSUE THREAD

**Issue by karyon** [django-compressor/django-compressor#985]
They were replaced by COMPRESS_FILTERS in #900, i would simplify that to only have one version of those settings.

**Comment by karyon** [comment]
also, we could remove references to JSMinFilter and CSSMinFilter, and only use rJSMinFilter and rCSSMinFilter instead.

**Comment by diox** [comment]
We announced in the changelog that `COMPRESS_CSS_FILTERS` and `COMPRESS_JS_FILTERS` were deprecated, but they aren't deprecated in the code, and also the docs encourage you to use `COMPRESS_FILTERS` instead, it doesn't say they are deprecated either.

So I think the first step would be to update raise a proper deprecation warning, update the docs, and then remove them in a future release.
