### ISSUE TITLE
Usage of COMPRESS_PRECOMPILERS and compiling files with lessc

### ISSUE THREAD

**Issue by franckbret** [django-compressor/django-compressor#99]
Hello, 
Pretty sure i'm missing something, but i'm trying COMPRESS_PRECOMPILERS settings to compile less.js files, and it doesn't...
I used too compile those kind of file with my own command script before, but as soon as I've seen it was possible with django compressor, I want it to do the job :-)

So in my settings I've something like this : 

```
COMPRESS_OUTPUT_DIR='cache' 
COMPRESS=True

COMPRESS_CSS_FILTERS = [
     'compressor.filters.cssmin.CSSMinFilter',
]
COMPRESS_JS_FILTERS = [
     'compressor.filters.jsmin.JSMinFilter'
]

COMPRESS_PRECOMPILERS = (
    ('stylesheet/less', '%s {infile} {outfile}' % os.path.abspath(os.path.join(PROJECT_DIR, "bin/src/less.js/bin/lessc"))),
)
```

And in my template :

```
{% compress css %}
<link type="stylesheet/less" rel="stylesheet" href="{{ STATIC_URL }}css/style.less" />
{% endcompress %}
```

I can compile the less file from command line with the lessc binary so my setup is ok.

When activating compress or when trying with ./manage.py compress I don't have any error throwed but no css file generated.
In the browser I just got same source code as template...

```
  <link type="stylesheet/less" rel="stylesheet" href="/media/static/css/style.less">
```

Any hints ?

**Comment by Satchitananda** [comment]
But not for OSX 10.11, ln: /usr/bin/node: Operation not permitted

**Comment by matiskay** [comment]
That solution doesn't work in OX 10.11

ln: /usr/bin/node: Operation not permitted

**Comment by matiskay** [comment]
The problem was related to `System Integrity Protection`. I rebooted my computer in recovery mode `(cmd + R)` then open the terminal and execute the command `csrutil disable` then restart the computer and finally make the symlink.
