### ISSUE TITLE
Can't run python manage.py collectstatic with compressor enable

### ISSUE THREAD

**Issue by florent6001** [django-compressor/django-compressor#993]
Hi all, 

Here is my settings.py : 
```python
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STATICFILES_FINDERS = [
    'compressor.finders.CompressorFinder',
]

COMPRESS_PRECOMPILERS = (
    ('text/x-scss', 'django_libsass.SassCompiler'),
)

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'compressor',

    'blog',
]
```

I don't know why, but if i start a collectstatic, i will have 0 static files copied, for run a collectstatic that will work, i have to comment :
- Compressor from installed_apps
- remove staticfiles_finder line
- remove compress_precompilers app.

I have to launch collectstatic for get the admin css into my static directory, and it's not working with compressor enabled.

**Comment by karyon** [comment]
although it looks to me like CompressorFinder should simply look into COMPRESS_ROOT which should be the same as STATIC_ROOT, i would still suggest to not remove django's default staticfiles finders, as per [the quickstart instructions](https://django-compressor.readthedocs.io/en/stable/quickstart/?highlight=compressorfinder#installation). 

(I'll close this as I assume that you don't have the problem anymore and that this is not a compressor bug. If you think it is, let me know!)
