### ISSUE TITLE
Default CSS template is incompatible with XHTML

### ISSUE THREAD

**Issue by tpwrules** [django-compressor/django-compressor#994]
I have a page whose resources I want compressed that must be served as XHTML in order to operate correctly. I've enabled offline compression to do this, but I get an XHTML syntax error. It looks like the CSS template outputs the compressed `<link>` element without a closing `</link>` or `/>`, producing the error.

It seems this change was made in #952 in order to optimize HTML5 compatibility. I installed my own template with the correct syntax so the issue is solved on my end, but it would be nice for it to work out of the box.

I also noticed that the offline compression command can't find my templates if they have an .xhtml extension. Perhaps the compressor could be amended to find .xhtml templates and then automatically insert the correct closing tag in this case only?

**Comment by diox** [comment]
Hi,

Sorry, this is too much of an edge case to deal with in compressor itself. You can customize the [compressor templates](https://github.com/django-compressor/django-compressor/tree/develop/compressor/templates/compressor) by overriding them in your project and pass `--extension` to the `compress` command to get it to find those `.xhtml` files.
