### ISSUE TITLE
Problem with <link> tag when generating XML / XSL content

### ISSUE THREAD

**Issue by ygwain** [django-compressor/django-compressor#996]
The [commit](https://github.com/django-compressor/django-compressor/commit/8f33c1753ac6aba2b2261e5a21d66623b71f88cd) makes it impossible to create the correct link tag in terms of XML / XSL markup.
In my case, I generate XSL content for [wkhtmltopdf](https://wkhtmltopdf.org/) TOC (table of contents). I spent a lot of time debugging the problem that the update brought.

**Comment by diox** [comment]
Hi,

You can override the templates in your project if you wish. compressor is not expected to generate valid XML / XSL content.

**Comment by ygwain** [comment]
Thanks. So I did. But IMHO compressor should not be restricted to generate only HTML content.
