### ISSUE TITLE
Version 2.2 install broken due to django-appconf update

### ISSUE THREAD

**Issue by flowersjg** [django-compressor/django-compressor#997]
Since version 2.2 of `django-compressor` lists requirement `'django-appconf >= 1.0'`, and since `django-appconf` appears to have removed support for Python 2 in its 1.0.4 release, I'm having to manually pin `django-appconf` at 1.0.3. I totally understand if you're not maintaining 2.2 anymore, but thought I'd let you know.

**Comment by carltongibson** [comment]
> I'm having to manually pin django-appconf at 1.0.3. 

That's the correct approach until you can update to a supported version of Python.
